//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 08:46:07 ÏÂÎç CST 
//


package com.xml.cnaps2.hvps.v71500101;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TxDwnldgRspnInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TxDwnldgRspnInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NPCPrcInf" type="{urn:cnaps:std:hvps:2010:tech:xsd:hvps.715.001.01}NPCPrcInf1"/>
 *         &lt;element name="OrgnlMsgCntt" type="{urn:cnaps:std:hvps:2010:tech:xsd:hvps.715.001.01}OrgnlMsgCntt1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TxDwnldgRspnInf1", propOrder = {
    "npcPrcInf",
    "orgnlMsgCntt"
})
public class TxDwnldgRspnInf1 {

    @XmlElement(name = "NPCPrcInf", required = true)
    protected NPCPrcInf1 npcPrcInf;
    @XmlElement(name = "OrgnlMsgCntt", required = true)
    protected OrgnlMsgCntt1 orgnlMsgCntt;

    /**
     * Gets the value of the npcPrcInf property.
     * 
     * @return
     *     possible object is
     *     {@link NPCPrcInf1 }
     *     
     */
    public NPCPrcInf1 getNPCPrcInf() {
        return npcPrcInf;
    }

    /**
     * Sets the value of the npcPrcInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link NPCPrcInf1 }
     *     
     */
    public void setNPCPrcInf(NPCPrcInf1 value) {
        this.npcPrcInf = value;
    }

    /**
     * Gets the value of the orgnlMsgCntt property.
     * 
     * @return
     *     possible object is
     *     {@link OrgnlMsgCntt1 }
     *     
     */
    public OrgnlMsgCntt1 getOrgnlMsgCntt() {
        return orgnlMsgCntt;
    }

    /**
     * Sets the value of the orgnlMsgCntt property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgnlMsgCntt1 }
     *     
     */
    public void setOrgnlMsgCntt(OrgnlMsgCntt1 value) {
        this.orgnlMsgCntt = value;
    }

}
