//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 08:45:39 ÏÂÎç CST 
//


package com.xml.cnaps2.ccms.v91300101;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChngInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChngInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChngCtrl" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.913.001.01}ChngCtrl1"/>
 *         &lt;element name="NcisBkCd" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.913.001.01}Max14Text"/>
 *         &lt;element name="BepsAgcyBkCd" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.913.001.01}Max14Text"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChngInf1", propOrder = {
    "chngCtrl",
    "ncisBkCd",
    "bepsAgcyBkCd"
})
public class ChngInf1 {

    @XmlElement(name = "ChngCtrl", required = true)
    protected ChngCtrl1 chngCtrl;
    @XmlElement(name = "NcisBkCd", required = true)
    protected String ncisBkCd;
    @XmlElement(name = "BepsAgcyBkCd", required = true)
    protected String bepsAgcyBkCd;

    /**
     * Gets the value of the chngCtrl property.
     * 
     * @return
     *     possible object is
     *     {@link ChngCtrl1 }
     *     
     */
    public ChngCtrl1 getChngCtrl() {
        return chngCtrl;
    }

    /**
     * Sets the value of the chngCtrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngCtrl1 }
     *     
     */
    public void setChngCtrl(ChngCtrl1 value) {
        this.chngCtrl = value;
    }

    /**
     * Gets the value of the ncisBkCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNcisBkCd() {
        return ncisBkCd;
    }

    /**
     * Sets the value of the ncisBkCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNcisBkCd(String value) {
        this.ncisBkCd = value;
    }

    /**
     * Gets the value of the bepsAgcyBkCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBepsAgcyBkCd() {
        return bepsAgcyBkCd;
    }

    /**
     * Sets the value of the bepsAgcyBkCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBepsAgcyBkCd(String value) {
        this.bepsAgcyBkCd = value;
    }

}
