//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.11 at 04:32:12 ���� CST 
//


package com.xml.cnaps2.beps.v12700101;

import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ChequeInformation1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChequeInformation1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IsseDt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.127.001.01}ISODate"/>
 *         &lt;element name="PayDT" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.127.001.01}ISODate"/>
 *         &lt;element name="Nb" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.127.001.01}Max32NumericText"/>
 *         &lt;element name="PmtPswd" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.127.001.01}Max512Text" minOccurs="0"/>
 *         &lt;element name="Purp" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.127.001.01}Max256Text" minOccurs="0"/>
 *         &lt;element name="NbOfEndrsr" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.127.001.01}Max2NumericText"/>
 *         &lt;element name="EndrsrDtl" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.127.001.01}EndorsorDetail1" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ImgTp" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.127.001.01}Max10Text"/>
 *         &lt;element name="ImgFrntLen" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.127.001.01}Max8NumericText"/>
 *         &lt;element name="ImgFrntData" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.127.001.01}Max400000Text"/>
 *         &lt;element name="ImgBckLen" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.127.001.01}Max8NumericText"/>
 *         &lt;element name="ImgBckData" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.127.001.01}Max200000Text"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChequeInformation1", propOrder = {
    "isseDt",
    "payDT",
    "nb",
    "pmtPswd",
    "purp",
    "nbOfEndrsr",
    "endrsrDtl",
    "imgTp",
    "imgFrntLen",
    "imgFrntData",
    "imgBckLen",
    "imgBckData"
})
public class ChequeInformation1 {

    @XmlElement(name = "IsseDt", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected Date isseDt;
    @XmlElement(name = "PayDT", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected Date payDT;
    @XmlElement(name = "Nb", required = true)
    protected String nb;
    @XmlElement(name = "PmtPswd")
    protected String pmtPswd;
    @XmlElement(name = "Purp")
    protected String purp;
    @XmlElement(name = "NbOfEndrsr", required = true)
    protected String nbOfEndrsr;
    @XmlElement(name = "EndrsrDtl")
    protected List<EndorsorDetail1> endrsrDtl = new Vector<EndorsorDetail1>();
    @XmlElement(name = "ImgTp", required = true)
    protected String imgTp;
    @XmlElement(name = "ImgFrntLen", required = true)
    protected String imgFrntLen;
    @XmlElement(name = "ImgFrntData", required = true)
    protected String imgFrntData;
    @XmlElement(name = "ImgBckLen", required = true)
    protected String imgBckLen;
    @XmlElement(name = "ImgBckData", required = true)
    protected String imgBckData;

    /**
     * Gets the value of the isseDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getIsseDt() {
        return isseDt;
    }

    /**
     * Sets the value of the isseDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsseDt(Date value) {
        this.isseDt = value;
    }

    /**
     * Gets the value of the payDT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getPayDT() {
        return payDT;
    }

    /**
     * Sets the value of the payDT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayDT(Date value) {
        this.payDT = value;
    }

    /**
     * Gets the value of the nb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNb() {
        return nb;
    }

    /**
     * Sets the value of the nb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNb(String value) {
        this.nb = value;
    }

    /**
     * Gets the value of the pmtPswd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtPswd() {
        return pmtPswd;
    }

    /**
     * Sets the value of the pmtPswd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtPswd(String value) {
        this.pmtPswd = value;
    }

    /**
     * Gets the value of the purp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurp() {
        return purp;
    }

    /**
     * Sets the value of the purp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurp(String value) {
        this.purp = value;
    }

    /**
     * Gets the value of the nbOfEndrsr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNbOfEndrsr() {
        return nbOfEndrsr;
    }

    /**
     * Sets the value of the nbOfEndrsr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNbOfEndrsr(String value) {
        this.nbOfEndrsr = value;
    }

    /**
     * Gets the value of the endrsrDtl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the endrsrDtl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEndrsrDtl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EndorsorDetail1 }
     * 
     * 
     */
    public List<EndorsorDetail1> getEndrsrDtl() {
        if (endrsrDtl == null) {
            endrsrDtl = new Vector<EndorsorDetail1>();
        }
        return this.endrsrDtl;
    }

    /**
     * Gets the value of the imgTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgTp() {
        return imgTp;
    }

    /**
     * Sets the value of the imgTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgTp(String value) {
        this.imgTp = value;
    }

    /**
     * Gets the value of the imgFrntLen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgFrntLen() {
        return imgFrntLen;
    }

    /**
     * Sets the value of the imgFrntLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgFrntLen(String value) {
        this.imgFrntLen = value;
    }

    /**
     * Gets the value of the imgFrntData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgFrntData() {
        return imgFrntData;
    }

    /**
     * Sets the value of the imgFrntData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgFrntData(String value) {
        this.imgFrntData = value;
    }

    /**
     * Gets the value of the imgBckLen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgBckLen() {
        return imgBckLen;
    }

    /**
     * Sets the value of the imgBckLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgBckLen(String value) {
        this.imgBckLen = value;
    }

    /**
     * Gets the value of the imgBckData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgBckData() {
        return imgBckData;
    }

    /**
     * Sets the value of the imgBckData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgBckData(String value) {
        this.imgBckData = value;
    }

}
