//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 08:44:58 ÏÂÎç CST 
//


package com.xml.cnaps2.camt.v01000104;

import java.util.List;
import java.util.Vector;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Limits3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Limits3">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CurLmt" type="{urn:swift:xsd:camt.010.001.04}LimitReport3" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DfltLmt" type="{urn:swift:xsd:camt.010.001.04}LimitReport3" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Limits3", propOrder = {
    "curLmt",
    "dfltLmt"
})
public class Limits3 {

    @XmlElement(name = "CurLmt")
    protected List<LimitReport3> curLmt = new Vector<LimitReport3>();
    @XmlElement(name = "DfltLmt")
    protected List<LimitReport3> dfltLmt = new Vector<LimitReport3>();

    /**
     * Gets the value of the curLmt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the curLmt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCurLmt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LimitReport3 }
     * 
     * 
     */
    public List<LimitReport3> getCurLmt() {
        if (curLmt == null) {
            curLmt = new Vector<LimitReport3>();
        }
        return this.curLmt;
    }

    /**
     * Gets the value of the dfltLmt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dfltLmt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDfltLmt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LimitReport3 }
     * 
     * 
     */
    public List<LimitReport3> getDfltLmt() {
        if (dfltLmt == null) {
            dfltLmt = new Vector<LimitReport3>();
        }
        return this.dfltLmt;
    }

}
