/*
 * Copyright (c) 2001-2009, TIBCO Software Inc.
 * Use, modification, and distribution subject to terms of license.
 */
jsx3.require("jsx3.gui.Painted","jsx3.gui.Interactive");jsx3.Class.defineClass("jsx3.gui.Sound",jsx3.gui.Painted,[jsx3.gui.Interactive],function(p,e){var
ub={a:"undefined",b:"Apple QuickTime",c:" ",d:"RealPlayer",e:"Windows Media Player",f:"Unknown Version",g:"WMPlayer.OCX.7",h:"Generic",i:'<embed id="',j:'" name="',k:'" class="jsx30sound" src="',l:'" enablejavascript="true" autostart="false" ',m:' volume="',n:'" prefetch="true"',o:"/>"};p.Vu={};p.Vu.ew=function(k){return typeof k.GetQuickTimeVersion!=ub.a;};p.Vu.wL=function(a){a.Play();};p.Vu.HS=function(k){k.Stop();};p.Vu.K9=function(g){g.Stop();g.Rewind();};p.Vu.TO=function(o){return o.GetDuration()/o.GetTimeScale();};p.Vu.fu=function(a){return a.GetTime()/a.GetTimeScale();};p.Vu.mK=function(f,i){f.SetTime(i*f.GetTimeScale());};p.Vu.g0=function(c,s){c.SetVolume(this.u5(s));};p.Vu.u5=function(g){return Math.round(g*255/100);};p.Vu.toString=function(){return ub.b;};p.Vu.qJ=function(b){return this+ub.c+b.GetQuickTimeVersion();};p.Vy={};p.Vy.ew=function(d){return typeof d.GetVersionInfo!=ub.a;};p.Vy.wL=function(a){if(a.CanPlay()){a.DoPlay();if(a.jsxlength==null){a.jsxlength=a.GetLength();a.SetPreFetch(false);}}};p.Vy.HS=function(c){if(c.CanPause())c.DoPause();};p.Vy.K9=function(k){if(k.CanStop())k.DoStop();};p.Vy.TO=function(m){if(m.GetPlayState()!=0||m.GetPreFetch()){return m.GetLength()/1000;}else return m.jsxlength!=null?m.jsxlength/1000:Number.NaN;};p.Vy.fu=function(a){return a.GetPosition()/1000;};p.Vy.mK=function(i,l){if(i.GetPlayState()!=0){i.SetPosition(l*1000);}else{i.DoPlay();i.SetPosition(l*1000);i.DoPause();}};p.Vy.YH=function(h){return h.GetPlayState()==3;};p.Vy.g0=function(b,r){b.SetVolume(this.u5(r));};p.Vy.u5=function(a){return Math.round(a);};p.Vy.toString=function(){return ub.d;};p.Vy.qJ=function(n){return this+ub.c+n.GetVersionInfo();};p.W0={};p.W0.ew=function(f){return typeof f.GetMediaInfoString!=ub.a;};p.W0.wL=function(a){a.Play();};p.W0.HS=function(j){j.Pause();};p.W0.K9=function(g){g.Stop();};p.W0.TO=function(a){return a.Duration;};p.W0.fu=function(q){return q.CurrentPosition;};p.W0.mK=function(c,f){c.CurrentPosition=f;};p.W0.YH=function(m){return m.PlayState==2;};p.W0.g0=function(b,r){b.Volume=this.u5(r);};p.W0.u5=function(n){return Math.max(-10000,Math.round(2500*Math.log(n*100)/Math.LN10-10000));};p.W0.toString=function(){return ub.e;};p.W0.qJ=function(j){if(this.VERSION==null)try{this.VERSION=ub.f;if(window.ActiveXObject){this.ACTIVEX=new
ActiveXObject(ub.g);this.VERSION=this.ACTIVEX.versionInfo;}}catch(Kb){}return this+ub.c+this.VERSION;};p.Gq={};p.Gq.ew=function(j){return true;};p.Gq.wL=function(o){if(typeof o.Play!=ub.a)o.Play();};p.Gq.HS=function(i){if(typeof i.Pause!=ub.a)i.Pause();};p.Gq.K9=function(k){if(typeof k.Stop!=ub.a)k.Stop();};p.Gq.TO=function(k){return Number.NaN;};p.Gq.fu=function(g){return Number.NaN;};p.Gq.mK=function(a,d){};p.Gq.YH=function(f){return false;};p.Gq.g0=function(k,h){if(typeof k.SetVolume!=ub.a)k.SetVolume(this.u5(h));};p.Gq.u5=function(r){return Math.round(r);};p.Gq.toString=function(){return ub.h;};p.Gq.qJ=function(d){return this.toString();};p._E=[p.Vu,p.Vy,p.W0,p.Gq];e.jsxurl=null;e.jsxvolume=50;e._jsxTu=null;e.init=function(s,b){this.jsxsuper(s);this.jsxurl=b;};e.getURL=function(){return this.jsxurl;};e.setURL=function(j){this.jsxurl=j;return this;};e.getVolume=function(){return this.jsxvolume;};e.ST=function(){var
x=this.jsxvolume!=null?this.jsxvolume:this.prototype.jsxvolume;return (this.Cu()).u5(x);};e.setVolume=function(q){this.jsxvolume=q==null?null:Math.max(0,Math.min(100,q));var
Ha=this.getRendered();if(Ha!=null){var
P=this.jsxvolume!=null?this.jsxvolume:this.prototype.jsxvolume;(this.Cu()).g0(Ha,P);}return this;};e.play=function(){var
Mb=this.getRendered();if(Mb!=null)(this.Cu()).wL(Mb);};e.pause=function(){var
H=this.getRendered();if(H!=null)(this.Cu()).HS(H);};e.rewind=function(){var
O=this.getRendered();if(O!=null)(this.Cu()).K9(O);};e.getLength=function(){var
da=this.getRendered();return da!=null?(this.Cu()).TO(da):Number.NaN;};e.getPosition=function(){var
db=this.getRendered();return db!=null?(this.Cu()).fu(db):Number.NaN;};e.setPosition=function(c){var
tb=this.getRendered();if(tb!=null)(this.Cu()).mK(tb,c);};e.getPluginVersion=function(){var
ha=this.getRendered();if(ha!=null)try{return (this.Cu()).qJ(ha);}catch(Kb){}return (this.Cu()).toString();};e.Cu=function(){if(this._jsxTu!=null)return this._jsxTu;var
mb=this.getRendered();if(mb!=null){for(var
Ra=0;Ra<p._E.length;Ra++){var
w=p._E[Ra];if(w.ew(mb)){this._jsxTu=w;break;}}return this._jsxTu;}else return p.Gq;};e.paint=function(){this.applyDynamicProperties();var
Z=this.ST();return ub.i+this.getId()+ub.j+this.getId()+ub.k+(this.getUriResolver()).resolveURI(this.getURL())+ub.l+this.renderAttributes()+ub.m+Z+ub.n+jsx3.html.pe+ub.o;};});
