//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.11 at 04:33:30 ÏÂÎç CST 
//


package com.xml.cnaps2.ccms.v91600101;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BkCdChngNtfctn" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.916.001.01}BkCdChngNtfctnV01"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "bkCdChngNtfctn"
})
public class Document {

    @XmlElement(name = "BkCdChngNtfctn", required = true)
    protected BkCdChngNtfctnV01 bkCdChngNtfctn;

    /**
     * Gets the value of the bkCdChngNtfctn property.
     * 
     * @return
     *     possible object is
     *     {@link BkCdChngNtfctnV01 }
     *     
     */
    public BkCdChngNtfctnV01 getBkCdChngNtfctn() {
        return bkCdChngNtfctn;
    }

    /**
     * Sets the value of the bkCdChngNtfctn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BkCdChngNtfctnV01 }
     *     
     */
    public void setBkCdChngNtfctn(BkCdChngNtfctnV01 value) {
        this.bkCdChngNtfctn = value;
    }

}
