-- ${table.tableName} generated by ParseSampleXml
 
DROP TABLE IF EXISTS ${table.tableName};

/*==============================================================*/
/* Table: ${table.tableName}                                             */
/*==============================================================*/
CREATE TABLE ${table.tableName}  (
<#list table.basicColumns as column>    
   ${column.dbName}			${column.dbTypeMysql}		${column.dbExtraMysql},
</#list>    
   INDEX PK_T_MSG_IBPS_101_001_01 (UUID)
)Type=InnoDB;

