//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.11 at 04:56:28 ÏÂÎç CST 
//


package com.xml.cnaps2.nets.v40700101;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NetgQMgmt" type="{urn:cnaps:std:nets:2010:tech:xsd:nets.407.001.01}NetgQMgmtV01"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "netgQMgmt"
})
public class Document {

    @XmlElement(name = "NetgQMgmt", required = true)
    protected NetgQMgmtV01 netgQMgmt;

    /**
     * Gets the value of the netgQMgmt property.
     * 
     * @return
     *     possible object is
     *     {@link NetgQMgmtV01 }
     *     
     */
    public NetgQMgmtV01 getNetgQMgmt() {
        return netgQMgmt;
    }

    /**
     * Sets the value of the netgQMgmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetgQMgmtV01 }
     *     
     */
    public void setNetgQMgmt(NetgQMgmtV01 value) {
        this.netgQMgmt = value;
    }

}
