//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 08:44:27 ÏÂÎç CST 
//


package com.xml.cnaps2.beps.v39400101;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OriginalTransactionInformation1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OriginalTransactionInformation1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrgnlCtgyPurpCd" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.394.001.01}Max5Text"/>
 *         &lt;element name="OrgnlChrgId" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.394.001.01}Max20Text"/>
 *         &lt;element name="OrgnlCorprtnId" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.394.001.01}Max20Text"/>
 *         &lt;element name="OrgnlUsrId" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.394.001.01}Max20Text"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OriginalTransactionInformation1", propOrder = {
    "orgnlCtgyPurpCd",
    "orgnlChrgId",
    "orgnlCorprtnId",
    "orgnlUsrId"
})
public class OriginalTransactionInformation1 {

    @XmlElement(name = "OrgnlCtgyPurpCd", required = true)
    protected String orgnlCtgyPurpCd;
    @XmlElement(name = "OrgnlChrgId", required = true)
    protected String orgnlChrgId;
    @XmlElement(name = "OrgnlCorprtnId", required = true)
    protected String orgnlCorprtnId;
    @XmlElement(name = "OrgnlUsrId", required = true)
    protected String orgnlUsrId;

    /**
     * Gets the value of the orgnlCtgyPurpCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgnlCtgyPurpCd() {
        return orgnlCtgyPurpCd;
    }

    /**
     * Sets the value of the orgnlCtgyPurpCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgnlCtgyPurpCd(String value) {
        this.orgnlCtgyPurpCd = value;
    }

    /**
     * Gets the value of the orgnlChrgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgnlChrgId() {
        return orgnlChrgId;
    }

    /**
     * Sets the value of the orgnlChrgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgnlChrgId(String value) {
        this.orgnlChrgId = value;
    }

    /**
     * Gets the value of the orgnlCorprtnId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgnlCorprtnId() {
        return orgnlCorprtnId;
    }

    /**
     * Sets the value of the orgnlCorprtnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgnlCorprtnId(String value) {
        this.orgnlCorprtnId = value;
    }

    /**
     * Gets the value of the orgnlUsrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgnlUsrId() {
        return orgnlUsrId;
    }

    /**
     * Sets the value of the orgnlUsrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgnlUsrId(String value) {
        this.orgnlUsrId = value;
    }

}
