//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 08:46:12 ÏÂÎç CST 
//


package com.xml.cnaps2.nets.v35300101;

import java.util.List;
import java.util.Vector;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NetDebitLimitDistributionManagementInformation1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetDebitLimitDistributionManagementInformation1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MgrId" type="{urn:cnaps:std:nets:2010:tech:xsd:nets.353.001.01}Max14Text" minOccurs="0"/>
 *         &lt;element name="OprClss" type="{urn:cnaps:std:nets:2010:tech:xsd:nets.353.001.01}OperationClassCode1"/>
 *         &lt;element name="OprTp" type="{urn:cnaps:std:nets:2010:tech:xsd:nets.353.001.01}OperationTypeCode1"/>
 *         &lt;element name="NbOfMmb" type="{urn:cnaps:std:nets:2010:tech:xsd:nets.353.001.01}Max8NumericText"/>
 *         &lt;element name="DstrbtnList" type="{urn:cnaps:std:nets:2010:tech:xsd:nets.353.001.01}DstrbtnList1" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetDebitLimitDistributionManagementInformation1", propOrder = {
    "mgrId",
    "oprClss",
    "oprTp",
    "nbOfMmb",
    "dstrbtnList"
})
public class NetDebitLimitDistributionManagementInformation1 {

    @XmlElement(name = "MgrId")
    protected String mgrId;
    @XmlElement(name = "OprClss", required = true)
    protected String oprClss;
    @XmlElement(name = "OprTp", required = true)
    protected String oprTp;
    @XmlElement(name = "NbOfMmb", required = true)
    protected String nbOfMmb;
    @XmlElement(name = "DstrbtnList", required = true)
    protected List<DstrbtnList1> dstrbtnList = new Vector<DstrbtnList1>();

    /**
     * Gets the value of the mgrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMgrId() {
        return mgrId;
    }

    /**
     * Sets the value of the mgrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMgrId(String value) {
        this.mgrId = value;
    }

    /**
     * Gets the value of the oprClss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOprClss() {
        return oprClss;
    }

    /**
     * Sets the value of the oprClss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOprClss(String value) {
        this.oprClss = value;
    }

    /**
     * Gets the value of the oprTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOprTp() {
        return oprTp;
    }

    /**
     * Sets the value of the oprTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOprTp(String value) {
        this.oprTp = value;
    }

    /**
     * Gets the value of the nbOfMmb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNbOfMmb() {
        return nbOfMmb;
    }

    /**
     * Sets the value of the nbOfMmb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNbOfMmb(String value) {
        this.nbOfMmb = value;
    }

    /**
     * Gets the value of the dstrbtnList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dstrbtnList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDstrbtnList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DstrbtnList1 }
     * 
     * 
     */
    public List<DstrbtnList1> getDstrbtnList() {
        if (dstrbtnList == null) {
            dstrbtnList = new Vector<DstrbtnList1>();
        }
        return this.dstrbtnList;
    }

}
