//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.11 at 04:34:10 ���� CST 
//


package com.xml.cnaps2.nets.v61800101;

import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for BEPSNettingResponseInformation1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BEPSNettingResponseInformation1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NetgDt" type="{urn:cnaps:std:nets:2010:tech:xsd:nets.618.001.01}ISODate" minOccurs="0"/>
 *         &lt;element name="NbOfTx" type="{urn:cnaps:std:nets:2010:tech:xsd:nets.618.001.01}Max8NumericText" minOccurs="0"/>
 *         &lt;element name="TxList" type="{urn:cnaps:std:nets:2010:tech:xsd:nets.618.001.01}TransactionList1" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BEPSNettingResponseInformation1", propOrder = {
    "netgDt",
    "nbOfTx",
    "txList"
})
public class BEPSNettingResponseInformation1 {

    @XmlElement(name = "NetgDt", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    protected Date netgDt;
    @XmlElement(name = "NbOfTx")
    protected String nbOfTx;
    @XmlElement(name = "TxList")
    protected List<TransactionList1> txList = new Vector<TransactionList1>();



	/**
     * Gets the value of the netgDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getNetgDt() {
        return netgDt;
    }

    /**
     * Sets the value of the netgDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetgDt(Date value) {
        this.netgDt = value;
    }

    /**
     * Gets the value of the nbOfTx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNbOfTx() {
        return nbOfTx;
    }

    /**
     * Sets the value of the nbOfTx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNbOfTx(String value) {
        this.nbOfTx = value;
    }

    /**
     * Gets the value of the txList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the txList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTxList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransactionList1 }
     * 
     * 
     */
    public List<TransactionList1> getTxList() {
        if (txList == null) {
            txList = new Vector<TransactionList1>();
        }
        return this.txList;
    }

    public void setTxList(List<TransactionList1> txList) {
		this.txList = txList;
	}
    
}
