package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Beps12800101TxInfAndSts generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_BEPS_128")
public class Beps12800101TxInfAndSts  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.orgnlGrpInfAndSts.nbOfTxsPerSts[0].dtldSts")
    private String dtldSts;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.txInfAndSts.orgnlTxId")
    private String orgnlTxId;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.txInfAndSts.stsRsnInf.rsn.prtry")
    private String prtryRejCd;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.txInfAndSts.stsRsnInf.addtlInf[0]")
    private String rejRsn;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.txInfAndSts.orgnlTxRef.intrBkSttlmAmt.value")
    private Double intrBkSttlmAmt;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.txInfAndSts.orgnlTxRef.pmtTpInf.ctgyPurp.prtry")
    private String orgnlTpCd;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.txInfAndSts.orgnlTxRef.mndtRltdInf.amdmntInfDtls.orgnlCdtrAgt.finInstnId.clrSysMmbId.mmbId")
    private String mmbId;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.txInfAndSts.orgnlTxRef.mndtRltdInf.amdmntInfDtls.orgnlCdtrAgt.brnchId.id")
    private String brnchId;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.txInfAndSts.orgnlTxRef.rmtInf.ustrd[0]")
    private String rmtInf;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.txInfAndSts.orgnlTxRef.rmtInf.ustrd[0]")
    private String ustrdFees;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.txInfAndSts.orgnlTxRef.dbtrAgt.finInstnId.clrSysMmbId.mmbId")
    private String dbtrClrSysMmbId;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.txInfAndSts.orgnlTxRef.dbtrAgt.brnchId.id")
    private String dbtrAgtBrnchId;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.txInfAndSts.orgnlTxRef.cdtrAgt.finInstnId.clrSysMmbId.mmbId")
    private String cdtrClrSysMmbId;
    
    @JaxbMapping(objPath="fiToFiPmtStsRpt.txInfAndSts.orgnlTxRef.cdtrAgt.brnchId.id")
    private String cdtrAgtBrnchId;
    
    private Beps12800101 fid;
	
    /** default constructor */
    public Beps12800101TxInfAndSts() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the dtldSts
   * 
   * @return the dtldSts
   */
    @Column(name = "DTLDSTS")
    public String getDtldSts() {
        return dtldSts;
    }	 
     
  /**
   * Sets the dtldSts
   *
   * @param newDtldSts the new dtldSts
   */

    public void  setDtldSts(String newDtldSts) {
        dtldSts = newDtldSts;
    }	  
  /**
   * Returns the orgnlTxId
   * 
   * @return the orgnlTxId
   */
    @Column(name = "ORGNLTXID")
    public String getOrgnlTxId() {
        return orgnlTxId;
    }	 
     
  /**
   * Sets the orgnlTxId
   *
   * @param newOrgnlTxId the new orgnlTxId
   */

    public void  setOrgnlTxId(String newOrgnlTxId) {
        orgnlTxId = newOrgnlTxId;
    }	  
  /**
   * Returns the prtryRejCd
   * 
   * @return the prtryRejCd
   */
    @Column(name = "PRTRYREJCD")
    public String getPrtryRejCd() {
        return prtryRejCd;
    }	 
     
  /**
   * Sets the prtryRejCd
   *
   * @param newPrtryRejCd the new prtryRejCd
   */

    public void  setPrtryRejCd(String newPrtryRejCd) {
        prtryRejCd = newPrtryRejCd;
    }	  
  /**
   * Returns the rejRsn
   * 
   * @return the rejRsn
   */
    @Column(name = "REJRSN")
    public String getRejRsn() {
        return rejRsn;
    }	 
     
  /**
   * Sets the rejRsn
   *
   * @param newRejRsn the new rejRsn
   */

    public void  setRejRsn(String newRejRsn) {
        rejRsn = newRejRsn;
    }	  
  /**
   * Returns the intrBkSttlmAmt
   * 
   * @return the intrBkSttlmAmt
   */
    @Column(name = "INTRBKSTTLMAMT")
    public Double getIntrBkSttlmAmt() {
        return intrBkSttlmAmt;
    }	 
     
  /**
   * Sets the intrBkSttlmAmt
   *
   * @param newIntrBkSttlmAmt the new intrBkSttlmAmt
   */

    public void  setIntrBkSttlmAmt(Double newIntrBkSttlmAmt) {
        intrBkSttlmAmt = newIntrBkSttlmAmt;
    }	  
  /**
   * Returns the orgnlTpCd
   * 
   * @return the orgnlTpCd
   */
    @Column(name = "ORGNLTPCD")
    public String getOrgnlTpCd() {
        return orgnlTpCd;
    }	 
     
  /**
   * Sets the orgnlTpCd
   *
   * @param newOrgnlTpCd the new orgnlTpCd
   */

    public void  setOrgnlTpCd(String newOrgnlTpCd) {
        orgnlTpCd = newOrgnlTpCd;
    }	  
  /**
   * Returns the mmbId
   * 
   * @return the mmbId
   */
    @Column(name = "MMBID")
    public String getMmbId() {
        return mmbId;
    }	 
     
  /**
   * Sets the mmbId
   *
   * @param newMmbId the new mmbId
   */

    public void  setMmbId(String newMmbId) {
        mmbId = newMmbId;
    }	  
  /**
   * Returns the brnchId
   * 
   * @return the brnchId
   */
    @Column(name = "BRNCHID")
    public String getBrnchId() {
        return brnchId;
    }	 
     
  /**
   * Sets the brnchId
   *
   * @param newBrnchId the new brnchId
   */

    public void  setBrnchId(String newBrnchId) {
        brnchId = newBrnchId;
    }	  
  /**
   * Returns the rmtInf
   * 
   * @return the rmtInf
   */
    @Column(name = "RMTINF")
    public String getRmtInf() {
        return rmtInf;
    }	 
     
  /**
   * Sets the rmtInf
   *
   * @param newRmtInf the new rmtInf
   */

    public void  setRmtInf(String newRmtInf) {
        rmtInf = newRmtInf;
    }	  
  /**
   * Returns the ustrdFees
   * 
   * @return the ustrdFees
   */
    @Column(name = "USTRDFEES")
    public String getUstrdFees() {
        return ustrdFees;
    }	 
     
  /**
   * Sets the ustrdFees
   *
   * @param newUstrdFees the new ustrdFees
   */

    public void  setUstrdFees(String newUstrdFees) {
        ustrdFees = newUstrdFees;
    }	  
  /**
   * Returns the dbtrClrSysMmbId
   * 
   * @return the dbtrClrSysMmbId
   */
    @Column(name = "DBTRCLRSYSMMBID")
    public String getDbtrClrSysMmbId() {
        return dbtrClrSysMmbId;
    }	 
     
  /**
   * Sets the dbtrClrSysMmbId
   *
   * @param newDbtrClrSysMmbId the new dbtrClrSysMmbId
   */

    public void  setDbtrClrSysMmbId(String newDbtrClrSysMmbId) {
        dbtrClrSysMmbId = newDbtrClrSysMmbId;
    }	  
  /**
   * Returns the dbtrAgtBrnchId
   * 
   * @return the dbtrAgtBrnchId
   */
    @Column(name = "DBTRAGTBRNCHID")
    public String getDbtrAgtBrnchId() {
        return dbtrAgtBrnchId;
    }	 
     
  /**
   * Sets the dbtrAgtBrnchId
   *
   * @param newDbtrAgtBrnchId the new dbtrAgtBrnchId
   */

    public void  setDbtrAgtBrnchId(String newDbtrAgtBrnchId) {
        dbtrAgtBrnchId = newDbtrAgtBrnchId;
    }	  
  /**
   * Returns the cdtrClrSysMmbId
   * 
   * @return the cdtrClrSysMmbId
   */
    @Column(name = "CDTRCLRSYSMMBID")
    public String getCdtrClrSysMmbId() {
        return cdtrClrSysMmbId;
    }	 
     
  /**
   * Sets the cdtrClrSysMmbId
   *
   * @param newCdtrClrSysMmbId the new cdtrClrSysMmbId
   */

    public void  setCdtrClrSysMmbId(String newCdtrClrSysMmbId) {
        cdtrClrSysMmbId = newCdtrClrSysMmbId;
    }	  
  /**
   * Returns the cdtrAgtBrnchId
   * 
   * @return the cdtrAgtBrnchId
   */
    @Column(name = "CDTRAGTBRNCHID")
    public String getCdtrAgtBrnchId() {
        return cdtrAgtBrnchId;
    }	 
     
  /**
   * Sets the cdtrAgtBrnchId
   *
   * @param newCdtrAgtBrnchId the new cdtrAgtBrnchId
   */

    public void  setCdtrAgtBrnchId(String newCdtrAgtBrnchId) {
        cdtrAgtBrnchId = newCdtrAgtBrnchId;
    }

	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
	public Beps12800101 getFid() {
		return fid;
	}
	
	
	public void setFid(Beps12800101 fid) {
		this.fid = fid;
	}	  
    
    
}    
    
