package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Beps72200101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_BEPS_722_HDR")
public class Beps72200101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="dtlChckReq.grpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="dtlChckReq.grpHdr.creDtTm")
    private Date creDtTm;
    
    @JaxbMapping(objPath="dtlChckReq.grpHdr.instgPty.instgDrctPty")
    private String instgDrctPty;
    
    @JaxbMapping(objPath="dtlChckReq.grpHdr.instgPty.instgPty")
    private String instgIndrctPty;
    
    @JaxbMapping(objPath="dtlChckReq.grpHdr.instdPty.instdDrctPty")
    private String instdDrctPty;
    
    @JaxbMapping(objPath="dtlChckReq.grpHdr.instdPty.instdPty")
    private String instdIndrctPty;
    
    @JaxbMapping(objPath="dtlChckReq.grpHdr.sysCd")
    private String sysCd;
    
    @JaxbMapping(objPath="dtlChckReq.grpHdr.rmk")
    private String rmk;
    
    @JaxbMapping(objPath="dtlChckReq.dtlChckReqInf.chckDt")
    private Date chckngDt;
    
    @JaxbMapping(objPath="dtlChckReq.dtlChckReqInf.dtlChckPmtInf.nbOfTxs")
    private String nbOfTxs;
    
    @JaxbMapping(objPath="dtlChckReq.dtlChckReqInf.dtlChckPmtInf.dtlChckPmtDtls[0]")
    private java.util.Set<Beps72200101DtlChckPmtDtls> dtlChckPmtDtls;
    
    @JaxbMapping(objPath="dtlChckReq.dtlChckReqInf.dtlChckMsg.dtlChckMsgDtls[0]")
    private java.util.Set<Beps72200101DtlChckMsgDtls> dtlChckMsgDtls;
    
    
	
    /** default constructor */
    public Beps72200101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public Date getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(Date newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the instgDrctPty
   * 
   * @return the instgDrctPty
   */
    @Column(name = "INSTGDRCTPTY")
    public String getInstgDrctPty() {
        return instgDrctPty;
    }	 
     
  /**
   * Sets the instgDrctPty
   *
   * @param newInstgDrctPty the new instgDrctPty
   */

    public void  setInstgDrctPty(String newInstgDrctPty) {
        instgDrctPty = newInstgDrctPty;
    }	  
  /**
   * Returns the instgIndrctPty
   * 
   * @return the instgIndrctPty
   */
    @Column(name = "INSTGINDRCTPTY")
    public String getInstgIndrctPty() {
        return instgIndrctPty;
    }	 
     
  /**
   * Sets the instgIndrctPty
   *
   * @param newInstgIndrctPty the new instgIndrctPty
   */

    public void  setInstgIndrctPty(String newInstgIndrctPty) {
        instgIndrctPty = newInstgIndrctPty;
    }	  
  /**
   * Returns the instdDrctPty
   * 
   * @return the instdDrctPty
   */
    @Column(name = "INSTDDRCTPTY")
    public String getInstdDrctPty() {
        return instdDrctPty;
    }	 
     
  /**
   * Sets the instdDrctPty
   *
   * @param newInstdDrctPty the new instdDrctPty
   */

    public void  setInstdDrctPty(String newInstdDrctPty) {
        instdDrctPty = newInstdDrctPty;
    }	  
  /**
   * Returns the instdIndrctPty
   * 
   * @return the instdIndrctPty
   */
    @Column(name = "INSTDINDRCTPTY")
    public String getInstdIndrctPty() {
        return instdIndrctPty;
    }	 
     
  /**
   * Sets the instdIndrctPty
   *
   * @param newInstdIndrctPty the new instdIndrctPty
   */

    public void  setInstdIndrctPty(String newInstdIndrctPty) {
        instdIndrctPty = newInstdIndrctPty;
    }	  
  /**
   * Returns the sysCd
   * 
   * @return the sysCd
   */
    @Column(name = "SYSCD")
    public String getSysCd() {
        return sysCd;
    }	 
     
  /**
   * Sets the sysCd
   *
   * @param newSysCd the new sysCd
   */

    public void  setSysCd(String newSysCd) {
        sysCd = newSysCd;
    }	  
  /**
   * Returns the rmk
   * 
   * @return the rmk
   */
    @Column(name = "RMK")
    public String getRmk() {
        return rmk;
    }	 
     
  /**
   * Sets the rmk
   *
   * @param newRmk the new rmk
   */

    public void  setRmk(String newRmk) {
        rmk = newRmk;
    }	  
  /**
   * Returns the chckngDt
   * 
   * @return the chckngDt
   */
    @Column(name = "CHCKNGDT")
    public Date getChckngDt() {
        return chckngDt;
    }	 
     
  /**
   * Sets the chckngDt
   *
   * @param newChckngDt the new chckngDt
   */

    public void  setChckngDt(Date newChckngDt) {
        chckngDt = newChckngDt;
    }	  
  /**
   * Returns the nbOfTxs
   * 
   * @return the nbOfTxs
   */
    @Column(name = "NBOFTXS")
    public String getNbOfTxs() {
        return nbOfTxs;
    }	 
     
  /**
   * Sets the nbOfTxs
   *
   * @param newNbOfTxs the new nbOfTxs
   */

    public void  setNbOfTxs(String newNbOfTxs) {
        nbOfTxs = newNbOfTxs;
    }	  
  /**
   * Returns the dtlChckPmtDtls
   * 
   * @return the dtlChckPmtDtls
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
    public java.util.Set<Beps72200101DtlChckPmtDtls> getDtlChckPmtDtls() {
        return dtlChckPmtDtls;
    }	 
     
  /**
   * Sets the dtlChckPmtDtls
   *
   * @param newDtlChckPmtDtls the new dtlChckPmtDtls
   */

    public void  setDtlChckPmtDtls(java.util.Set<Beps72200101DtlChckPmtDtls> newDtlChckPmtDtls) {
        dtlChckPmtDtls = newDtlChckPmtDtls;
    }	  
  /**
   * Returns the dtlChckMsgDtls
   * 
   * @return the dtlChckMsgDtls
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
    public java.util.Set<Beps72200101DtlChckMsgDtls> getDtlChckMsgDtls() {
        return dtlChckMsgDtls;
    }	 
     
  /**
   * Sets the dtlChckMsgDtls
   *
   * @param newDtlChckMsgDtls the new dtlChckMsgDtls
   */

    public void  setDtlChckMsgDtls(java.util.Set<Beps72200101DtlChckMsgDtls> newDtlChckMsgDtls) {
        dtlChckMsgDtls = newDtlChckMsgDtls;
    }	  
    
    
}    
    
