package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Beps40400101FldItmDtls generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_BEPS_404")
public class Beps40400101FldItmDtls  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="invcPrtRspn.invcPrtRspnInf.invcInf.fldItmDtls[0].nm")
    private String fNm;
    
    @JaxbMapping(objPath="invcPrtRspn.invcPrtRspnInf.invcInf.fldItmDtls[0].val")
    private String val;
    
    @JaxbMapping(objPath="invcPrtRspn.invcPrtRspnInf.invcInf.rmk")
    private String rmk;
    
    private Beps40400101 fid;
    
    
	
    /** default constructor */
    public Beps40400101FldItmDtls() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the fNm
   * 
   * @return the fNm
   */
    @Column(name = "FNM")
    public String getFNm() {
        return fNm;
    }	 
     
  /**
   * Sets the fNm
   *
   * @param newFNm the new fNm
   */

    public void  setFNm(String newFNm) {
        fNm = newFNm;
    }	  
  /**
   * Returns the val
   * 
   * @return the val
   */
    @Column(name = "VAL")
    public String getVal() {
        return val;
    }	 
     
  /**
   * Sets the val
   *
   * @param newVal the new val
   */

    public void  setVal(String newVal) {
        val = newVal;
    }	  
  /**
   * Returns the rmk
   * 
   * @return the rmk
   */
    @Column(name = "RMK")
    public String getRmk() {
        return rmk;
    }	 
     
  /**
   * Sets the rmk
   *
   * @param newRmk the new rmk
   */

    public void  setRmk(String newRmk) {
        rmk = newRmk;
    }

	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
	public Beps40400101 getFid() {
		return fid;
	}
	
	
	public void setFid(Beps40400101 fid) {
		this.fid = fid;
	}	  
    
    
}    
    
