package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Beps72100101ChckPmtInfDtls generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_BEPS_721_APX_YW")
public class Beps72100101ChckPmtInfDtls  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="ttlChck.ttlChckInf.chckPmtInf.chckPmtInfDtls[0].txNetgDt")
    private Date bizTxNetgDt;
    
    @JaxbMapping(objPath="ttlChck.ttlChckInf.chckPmtInf.chckPmtInfDtls[0].txNetgRnd")
    private String bizTxNetgRnd;
    
    @JaxbMapping(objPath="ttlChck.ttlChckInf.chckPmtInf.chckPmtInfDtls[0].mt")
    private String bizMT;
    
    @JaxbMapping(objPath="ttlChck.ttlChckInf.chckPmtInf.chckPmtInfDtls[0].sndTtlCnt")
    private String bizSndTtlCnt;
    
    @JaxbMapping(objPath="ttlChck.ttlChckInf.chckPmtInf.chckPmtInfDtls[0].sndTtlAmt.value")
    private Double bizSndTtlAmt;
    
    @JaxbMapping(objPath="ttlChck.ttlChckInf.chckPmtInf.chckPmtInfDtls[0].rcvTtlCnt")
    private String bizRcvTtlCnt;
    
    @JaxbMapping(objPath="ttlChck.ttlChckInf.chckPmtInf.chckPmtInfDtls[0].rcvTtlAmt.value")
    private Double bizRcvTtlAmt;
    
    @JaxbMapping(objPath="ttlChck.ttlChckInf.chckPmtInf.chckPmtInfDtls[0].prcSts")
    private String bizPrcSts;
    
    private Beps72100101 fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Beps72100101 getFid() {
		return fid;
	}


	public void setFid(Beps72100101 fid) {
		this.fid = fid;
	}
	
    /** default constructor */
    public Beps72100101ChckPmtInfDtls() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the bizTxNetgDt
   * 
   * @return the bizTxNetgDt
   */
    @Column(name = "BIZTXNETGDT")
    public Date getBizTxNetgDt() {
        return bizTxNetgDt;
    }	 
     
  /**
   * Sets the bizTxNetgDt
   *
   * @param newBizTxNetgDt the new bizTxNetgDt
   */

    public void  setBizTxNetgDt(Date newBizTxNetgDt) {
        bizTxNetgDt = newBizTxNetgDt;
    }	  
  /**
   * Returns the bizTxNetgRnd
   * 
   * @return the bizTxNetgRnd
   */
    @Column(name = "BIZTXNETGRND")
    public String getBizTxNetgRnd() {
        return bizTxNetgRnd;
    }	 
     
  /**
   * Sets the bizTxNetgRnd
   *
   * @param newBizTxNetgRnd the new bizTxNetgRnd
   */

    public void  setBizTxNetgRnd(String newBizTxNetgRnd) {
        bizTxNetgRnd = newBizTxNetgRnd;
    }	  
  /**
   * Returns the bizMT
   * 
   * @return the bizMT
   */
    @Column(name = "BIZMT")
    public String getBizMT() {
        return bizMT;
    }	 
     
  /**
   * Sets the bizMT
   *
   * @param newBizMT the new bizMT
   */

    public void  setBizMT(String newBizMT) {
        bizMT = newBizMT;
    }	  
  /**
   * Returns the bizSndTtlCnt
   * 
   * @return the bizSndTtlCnt
   */
    @Column(name = "BIZSNDTTLCNT")
    public String getBizSndTtlCnt() {
        return bizSndTtlCnt;
    }	 
     
  /**
   * Sets the bizSndTtlCnt
   *
   * @param newBizSndTtlCnt the new bizSndTtlCnt
   */

    public void  setBizSndTtlCnt(String newBizSndTtlCnt) {
        bizSndTtlCnt = newBizSndTtlCnt;
    }	  
  /**
   * Returns the bizSndTtlAmt
   * 
   * @return the bizSndTtlAmt
   */
    @Column(name = "BIZSNDTTLAMT")
    public Double getBizSndTtlAmt() {
        return bizSndTtlAmt;
    }	 
     
  /**
   * Sets the bizSndTtlAmt
   *
   * @param newBizSndTtlAmt the new bizSndTtlAmt
   */

    public void  setBizSndTtlAmt(Double newBizSndTtlAmt) {
        bizSndTtlAmt = newBizSndTtlAmt;
    }	  
  /**
   * Returns the bizRcvTtlCnt
   * 
   * @return the bizRcvTtlCnt
   */
    @Column(name = "BIZRCVTTLCNT")
    public String getBizRcvTtlCnt() {
        return bizRcvTtlCnt;
    }	 
     
  /**
   * Sets the bizRcvTtlCnt
   *
   * @param newBizRcvTtlCnt the new bizRcvTtlCnt
   */

    public void  setBizRcvTtlCnt(String newBizRcvTtlCnt) {
        bizRcvTtlCnt = newBizRcvTtlCnt;
    }	  
  /**
   * Returns the bizRcvTtlAmt
   * 
   * @return the bizRcvTtlAmt
   */
    @Column(name = "BIZRCVTTLAMT")
    public Double getBizRcvTtlAmt() {
        return bizRcvTtlAmt;
    }	 
     
  /**
   * Sets the bizRcvTtlAmt
   *
   * @param newBizRcvTtlAmt the new bizRcvTtlAmt
   */

    public void  setBizRcvTtlAmt(Double newBizRcvTtlAmt) {
        bizRcvTtlAmt = newBizRcvTtlAmt;
    }	  
  /**
   * Returns the bizPrcSts
   * 
   * @return the bizPrcSts
   */
    @Column(name = "BIZPRCSTS")
    public String getBizPrcSts() {
        return bizPrcSts;
    }	 
     
  /**
   * Sets the bizPrcSts
   *
   * @param newBizPrcSts the new bizPrcSts
   */

    public void  setBizPrcSts(String newBizPrcSts) {
        bizPrcSts = newBizPrcSts;
    }	  
    
    
}    
    
