package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Beps13300101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_BEPS_133_HDR")
public class Beps13300101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="fiToFiCstmrDrctDbt.grpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="fiToFiCstmrDrctDbt.grpHdr.creDtTm")
    private Date creDtTm;
    
    @JaxbMapping(objPath="fiToFiCstmrDrctDbt.grpHdr.nbOfTxs")
    private String nbOfTxs;
    
    @JaxbMapping(objPath="fiToFiCstmrDrctDbt.grpHdr.ctrlSum")
    private Double ctrlSum;
    
    @JaxbMapping(objPath="fiToFiCstmrDrctDbt.grpHdr.pmtTpInf.lclInstrm.prtry")
    private String prtryTpCd;
    
    @JaxbMapping(objPath="fiToFiCstmrDrctDbt.grpHdr.pmtTpInf.ctgyPurp.prtry")
    private String prtryPeriod;
    
    @JaxbMapping(objPath="fiToFiCstmrDrctDbt.drctDbtTxInf[0]")
    private java.util.Set<Beps13300101DrctDbtTxInf> drctDbtTxInf;
    
    
	
    /** default constructor */
    public Beps13300101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public Date getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(Date newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the nbOfTxs
   * 
   * @return the nbOfTxs
   */
    @Column(name = "NBOFTXS")
    public String getNbOfTxs() {
        return nbOfTxs;
    }	 
     
  /**
   * Sets the nbOfTxs
   *
   * @param newNbOfTxs the new nbOfTxs
   */

    public void  setNbOfTxs(String newNbOfTxs) {
        nbOfTxs = newNbOfTxs;
    }	  
  /**
   * Returns the ctrlSum
   * 
   * @return the ctrlSum
   */
    @Column(name = "CTRLSUM")
    public Double getCtrlSum() {
        return ctrlSum;
    }	 
     
  /**
   * Sets the ctrlSum
   *
   * @param newCtrlSum the new ctrlSum
   */

    public void  setCtrlSum(Double newCtrlSum) {
        ctrlSum = newCtrlSum;
    }	  
  /**
   * Returns the prtryTpCd
   * 
   * @return the prtryTpCd
   */
    @Column(name = "PRTRYTPCD")
    public String getPrtryTpCd() {
        return prtryTpCd;
    }	 
     
  /**
   * Sets the prtryTpCd
   *
   * @param newPrtryTpCd the new prtryTpCd
   */

    public void  setPrtryTpCd(String newPrtryTpCd) {
        prtryTpCd = newPrtryTpCd;
    }	  
  /**
   * Returns the prtryPeriod
   * 
   * @return the prtryPeriod
   */
    @Column(name = "PRTRYPERIOD")
    public String getPrtryPeriod() {
        return prtryPeriod;
    }	 
     
  /**
   * Sets the prtryPeriod
   *
   * @param newPrtryPeriod the new prtryPeriod
   */

    public void  setPrtryPeriod(String newPrtryPeriod) {
        prtryPeriod = newPrtryPeriod;
    }	  
  /**
   * Returns the drctDbtTxInf
   * 
   * @return the drctDbtTxInf
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
    public java.util.Set<Beps13300101DrctDbtTxInf> getDrctDbtTxInf() {
        return drctDbtTxInf;
    }	 
     
  /**
   * Sets the drctDbtTxInf
   *
   * @param newDrctDbtTxInf the new drctDbtTxInf
   */

    public void  setDrctDbtTxInf(java.util.Set<Beps13300101DrctDbtTxInf> newDrctDbtTxInf) {
        drctDbtTxInf = newDrctDbtTxInf;
    }


@Override
public String toString() {
	return "Beps13300101 [id=" + id + ", msgId=" + msgId + ", creDtTm="
			+ creDtTm + ", nbOfTxs=" + nbOfTxs + ", ctrlSum=" + ctrlSum
			+ ", prtryTpCd=" + prtryTpCd + ", prtryPeriod=" + prtryPeriod
			+ ", drctDbtTxInf=" + drctDbtTxInf + "]";
}	  
    
    
}    
    
