package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Beps41700101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_BEPS_417")
public class Beps41700101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.grpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.grpHdr.creDtTm")
    private Date creDtTm;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.grpHdr.instgPty.instgDrctPty")
    private String instgDrctPty;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.grpHdr.instgPty.instgPty")
    private String instgIndrctPty;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.grpHdr.instdPty.instdDrctPty")
    private String instdDrctPty;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.grpHdr.instdPty.instdPty")
    private String instdIndrctPty;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.grpHdr.sysCd")
    private String sysCd;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.grpHdr.rmk")
    private String rmk;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.orgnlGrpHdr.orgnlMsgId")
    private String orgnlMsgId;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.orgnlGrpHdr.orgnlInstgPty")
    private String orgnlInstgDrctPty;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.orgnlGrpHdr.orgnlMsgTp")
    private String orgnlMT;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.realTmInfRvslRspnInf.rspsnInf.sts")
    private String sts;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.realTmInfRvslRspnInf.rspsnInf.rjctCd")
    private String rjctCd;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.realTmInfRvslRspnInf.rspsnInf.rjctInf")
    private String rjctInf;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.realTmInfRvslRspnInf.rspsnInf.prcPty")
    private String prcPty;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.realTmInfRvslRspnInf.orgnlTx.orgnlGrpHdr.orgnlMsgId")
    private String pendOrgnlMsgId;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.realTmInfRvslRspnInf.orgnlTx.orgnlGrpHdr.orgnlInstgPty")
    private String pendOrgnlInstgDrctPty;
    
    @JaxbMapping(objPath="realTmInfRvslRspn.realTmInfRvslRspnInf.orgnlTx.orgnlGrpHdr.orgnlMsgTp")
    private String pendOrgnlMT;
    
    
	
    /** default constructor */
    public Beps41700101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
    @Id
	  @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	  @SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	  @GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public Date getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(Date newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the instgDrctPty
   * 
   * @return the instgDrctPty
   */
    @Column(name = "INSTGDRCTPTY")
    public String getInstgDrctPty() {
        return instgDrctPty;
    }	 
     
  /**
   * Sets the instgDrctPty
   *
   * @param newInstgDrctPty the new instgDrctPty
   */

    public void  setInstgDrctPty(String newInstgDrctPty) {
        instgDrctPty = newInstgDrctPty;
    }	  
  /**
   * Returns the instgIndrctPty
   * 
   * @return the instgIndrctPty
   */
    @Column(name = "INSTGINDRCTPTY")
    public String getInstgIndrctPty() {
        return instgIndrctPty;
    }	 
     
  /**
   * Sets the instgIndrctPty
   *
   * @param newInstgIndrctPty the new instgIndrctPty
   */

    public void  setInstgIndrctPty(String newInstgIndrctPty) {
        instgIndrctPty = newInstgIndrctPty;
    }	  
  /**
   * Returns the instdDrctPty
   * 
   * @return the instdDrctPty
   */
    @Column(name = "INSTDDRCTPTY")
    public String getInstdDrctPty() {
        return instdDrctPty;
    }	 
     
  /**
   * Sets the instdDrctPty
   *
   * @param newInstdDrctPty the new instdDrctPty
   */

    public void  setInstdDrctPty(String newInstdDrctPty) {
        instdDrctPty = newInstdDrctPty;
    }	  
  /**
   * Returns the instdIndrctPty
   * 
   * @return the instdIndrctPty
   */
    @Column(name = "INSTDINDRCTPTY")
    public String getInstdIndrctPty() {
        return instdIndrctPty;
    }	 
     
  /**
   * Sets the instdIndrctPty
   *
   * @param newInstdIndrctPty the new instdIndrctPty
   */

    public void  setInstdIndrctPty(String newInstdIndrctPty) {
        instdIndrctPty = newInstdIndrctPty;
    }	  
  /**
   * Returns the sysCd
   * 
   * @return the sysCd
   */
    @Column(name = "SYSCD")
    public String getSysCd() {
        return sysCd;
    }	 
     
  /**
   * Sets the sysCd
   *
   * @param newSysCd the new sysCd
   */

    public void  setSysCd(String newSysCd) {
        sysCd = newSysCd;
    }	  
  /**
   * Returns the rmk
   * 
   * @return the rmk
   */
    @Column(name = "RMK")
    public String getRmk() {
        return rmk;
    }	 
     
  /**
   * Sets the rmk
   *
   * @param newRmk the new rmk
   */

    public void  setRmk(String newRmk) {
        rmk = newRmk;
    }	  
  /**
   * Returns the orgnlMsgId
   * 
   * @return the orgnlMsgId
   */
    @Column(name = "ORGNLMSGID")
    public String getOrgnlMsgId() {
        return orgnlMsgId;
    }	 
     
  /**
   * Sets the orgnlMsgId
   *
   * @param newOrgnlMsgId the new orgnlMsgId
   */

    public void  setOrgnlMsgId(String newOrgnlMsgId) {
        orgnlMsgId = newOrgnlMsgId;
    }	  
  /**
   * Returns the orgnlInstgDrctPty
   * 
   * @return the orgnlInstgDrctPty
   */
    @Column(name = "ORGNLINSTGDRCTPTY")
    public String getOrgnlInstgDrctPty() {
        return orgnlInstgDrctPty;
    }	 
     
  /**
   * Sets the orgnlInstgDrctPty
   *
   * @param newOrgnlInstgDrctPty the new orgnlInstgDrctPty
   */

    public void  setOrgnlInstgDrctPty(String newOrgnlInstgDrctPty) {
        orgnlInstgDrctPty = newOrgnlInstgDrctPty;
    }	  
  /**
   * Returns the orgnlMT
   * 
   * @return the orgnlMT
   */
    @Column(name = "ORGNLMT")
    public String getOrgnlMT() {
        return orgnlMT;
    }	 
     
  /**
   * Sets the orgnlMT
   *
   * @param newOrgnlMT the new orgnlMT
   */

    public void  setOrgnlMT(String newOrgnlMT) {
        orgnlMT = newOrgnlMT;
    }	  
  /**
   * Returns the sts
   * 
   * @return the sts
   */
    @Column(name = "STS")
    public String getSts() {
        return sts;
    }	 
     
  /**
   * Sets the sts
   *
   * @param newSts the new sts
   */

    public void  setSts(String newSts) {
        sts = newSts;
    }	  
  /**
   * Returns the rjctCd
   * 
   * @return the rjctCd
   */
    @Column(name = "RJCTCD")
    public String getRjctCd() {
        return rjctCd;
    }	 
     
  /**
   * Sets the rjctCd
   *
   * @param newRjctCd the new rjctCd
   */

    public void  setRjctCd(String newRjctCd) {
        rjctCd = newRjctCd;
    }	  
  /**
   * Returns the rjctInf
   * 
   * @return the rjctInf
   */
    @Column(name = "RJCTINF")
    public String getRjctInf() {
        return rjctInf;
    }	 
     
  /**
   * Sets the rjctInf
   *
   * @param newRjctInf the new rjctInf
   */

    public void  setRjctInf(String newRjctInf) {
        rjctInf = newRjctInf;
    }	  
  /**
   * Returns the prcPty
   * 
   * @return the prcPty
   */
    @Column(name = "PRCPTY")
    public String getPrcPty() {
        return prcPty;
    }	 
     
  /**
   * Sets the prcPty
   *
   * @param newPrcPty the new prcPty
   */

    public void  setPrcPty(String newPrcPty) {
        prcPty = newPrcPty;
    }	  
  /**
   * Returns the pendOrgnlMsgId
   * 
   * @return the pendOrgnlMsgId
   */
    @Column(name = "PENDORGNLMSGID")
    public String getPendOrgnlMsgId() {
        return pendOrgnlMsgId;
    }	 
     
  /**
   * Sets the pendOrgnlMsgId
   *
   * @param newPendOrgnlMsgId the new pendOrgnlMsgId
   */

    public void  setPendOrgnlMsgId(String newPendOrgnlMsgId) {
        pendOrgnlMsgId = newPendOrgnlMsgId;
    }	  
  /**
   * Returns the pendOrgnlInstgDrctPty
   * 
   * @return the pendOrgnlInstgDrctPty
   */
    @Column(name = "PENDORGNLINSTGDRCTPTY")
    public String getPendOrgnlInstgDrctPty() {
        return pendOrgnlInstgDrctPty;
    }	 
     
  /**
   * Sets the pendOrgnlInstgDrctPty
   *
   * @param newPendOrgnlInstgDrctPty the new pendOrgnlInstgDrctPty
   */

    public void  setPendOrgnlInstgDrctPty(String newPendOrgnlInstgDrctPty) {
        pendOrgnlInstgDrctPty = newPendOrgnlInstgDrctPty;
    }	  
  /**
   * Returns the pendOrgnlMT
   * 
   * @return the pendOrgnlMT
   */
    @Column(name = "PENDORGNLMT")
    public String getPendOrgnlMT() {
        return pendOrgnlMT;
    }	 
     
  /**
   * Sets the pendOrgnlMT
   *
   * @param newPendOrgnlMT the new pendOrgnlMT
   */

    public void  setPendOrgnlMT(String newPendOrgnlMT) {
        pendOrgnlMT = newPendOrgnlMT;
    }	  
    
    
}    
    
