package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Beps12100101NtlTrsrInfDtls generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_BEPS_121_APX_GZZJ")
public class Beps12100101NtlTrsrInfDtls  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="cstmrCdtTrf.cstmrCdtTrfInf[0].cstmrCdtTrfAddtlInf.ntlTrsrInf.ntlTrsrInfDtls[0].tpCd")
    private String bankTpCd;
    
    @JaxbMapping(objPath="cstmrCdtTrf.cstmrCdtTrfInf[0].cstmrCdtTrfAddtlInf.ntlTrsrInf.ntlTrsrInfDtls[0].cptlCd")
    private String cptlCd;
    
    @JaxbMapping(objPath="cstmrCdtTrf.cstmrCdtTrfInf[0].cstmrCdtTrfAddtlInf.ntlTrsrInf.ntlTrsrInfDtls[0].cptlAmt")
    private Double cptlAmt;
    
    @JaxbMapping(objPath="cstmrCdtTrf.cstmrCdtTrfInf[0].cstmrCdtTrfAddtlInf.ntlTrsrInf.ntlTrsrInfDtls[0].acrlCd")
    private String acrlCd;
    
    @JaxbMapping(objPath="cstmrCdtTrf.cstmrCdtTrfInf[0].cstmrCdtTrfAddtlInf.ntlTrsrInf.ntlTrsrInfDtls[0].acrlAmt")
    private Double acrlAmt;
    
    private Beps12100101CstmrCdtTrfInf fid;
    
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Beps12100101CstmrCdtTrfInf getFid() {
		return fid;
	}


	public void setFid(Beps12100101CstmrCdtTrfInf fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Beps12100101NtlTrsrInfDtls() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the bankTpCd
   * 
   * @return the bankTpCd
   */
    @Column(name = "BANKTPCD")
    public String getBankTpCd() {
        return bankTpCd;
    }	 
     
  /**
   * Sets the bankTpCd
   *
   * @param newBankTpCd the new bankTpCd
   */

    public void  setBankTpCd(String newBankTpCd) {
        bankTpCd = newBankTpCd;
    }	  
  /**
   * Returns the cptlCd
   * 
   * @return the cptlCd
   */
    @Column(name = "CPTLCD")
    public String getCptlCd() {
        return cptlCd;
    }	 
     
  /**
   * Sets the cptlCd
   *
   * @param newCptlCd the new cptlCd
   */

    public void  setCptlCd(String newCptlCd) {
        cptlCd = newCptlCd;
    }	  
  /**
   * Returns the cptlAmt
   * 
   * @return the cptlAmt
   */
    @Column(name = "CPTLAMT")
    public Double getCptlAmt() {
        return cptlAmt;
    }	 
     
  /**
   * Sets the cptlAmt
   *
   * @param newCptlAmt the new cptlAmt
   */

    public void  setCptlAmt(Double newCptlAmt) {
        cptlAmt = newCptlAmt;
    }	  
  /**
   * Returns the acrlCd
   * 
   * @return the acrlCd
   */
    @Column(name = "ACRLCD")
    public String getAcrlCd() {
        return acrlCd;
    }	 
     
  /**
   * Sets the acrlCd
   *
   * @param newAcrlCd the new acrlCd
   */

    public void  setAcrlCd(String newAcrlCd) {
        acrlCd = newAcrlCd;
    }	  
  /**
   * Returns the acrlAmt
   * 
   * @return the acrlAmt
   */
    @Column(name = "ACRLAMT")
    public Double getAcrlAmt() {
        return acrlAmt;
    }	 
     
  /**
   * Sets the acrlAmt
   *
   * @param newAcrlAmt the new acrlAmt
   */

    public void  setAcrlAmt(Double newAcrlAmt) {
        acrlAmt = newAcrlAmt;
    }	  
    
    
}    
    
