package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Beps72200101DtlChckMsgDtls generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_BEPS_722_APX_XX")
public class Beps72200101DtlChckMsgDtls  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="dtlChckReq.dtlChckReqInf.dtlChckMsg.dtlChckMsgDtls[0].sndRcvTp")
    private String infoSndRcvTp;
    
    @JaxbMapping(objPath="dtlChckReq.dtlChckReqInf.dtlChckMsg.dtlChckMsgDtls[0].mt")
    private String infoMT;
    
    private Beps72200101 fid;
    
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Beps72200101 getFid() {
		return fid;
	}


	public void setFid(Beps72200101 fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Beps72200101DtlChckMsgDtls() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the infoSndRcvTp
   * 
   * @return the infoSndRcvTp
   */
    @Column(name = "INFOSNDRCVTP")
    public String getInfoSndRcvTp() {
        return infoSndRcvTp;
    }	 
     
  /**
   * Sets the infoSndRcvTp
   *
   * @param newInfoSndRcvTp the new infoSndRcvTp
   */

    public void  setInfoSndRcvTp(String newInfoSndRcvTp) {
        infoSndRcvTp = newInfoSndRcvTp;
    }	  
  /**
   * Returns the infoMT
   * 
   * @return the infoMT
   */
    @Column(name = "INFOMT")
    public String getInfoMT() {
        return infoMT;
    }	 
     
  /**
   * Sets the infoMT
   *
   * @param newInfoMT the new infoMT
   */

    public void  setInfoMT(String newInfoMT) {
        infoMT = newInfoMT;
    }	  
    
    
}    
    
