package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Beps72600101ChckInfDtls2 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_BEPS_726_APX_XX")
public class Beps72600101ChckInfDtls2  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="acctChck.acctChckInf.chckInfDtls2[0].txTpCd")
    private String infoCheckTxTpCd;
    
    @JaxbMapping(objPath="acctChck.acctChckInf.chckInfDtls2[0].sndTtlCnt")
    private String infoCheckSndgNbOfTxs;
    
    @JaxbMapping(objPath="acctChck.acctChckInf.chckInfDtls2[0].rcvTtlCnt")
    private String infoCheckRcvTtlCnt;
    
    @JaxbMapping(objPath="acctChck.acctChckInf.chckInfDtls2[0].sndDtls2[0]")
    private java.util.Set<Beps72600101SndDtls2> sndDtls2;
    
    @JaxbMapping(objPath="acctChck.acctChckInf.chckInfDtls2[0].rcvDtls2[0]")
    private java.util.Set<Beps72600101RcvDtls2> rcvDtls2;
    
    private Beps72600101 fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Beps72600101 getFid() {
		return fid;
	}


	public void setFid(Beps72600101 fid) {
		this.fid = fid;
	}
    
    
	
    /** default constructor */
    public Beps72600101ChckInfDtls2() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the infoCheckTxTpCd
   * 
   * @return the infoCheckTxTpCd
   */
    @Column(name = "INFOCHECKTXTPCD")
    public String getInfoCheckTxTpCd() {
        return infoCheckTxTpCd;
    }	 
     
  /**
   * Sets the infoCheckTxTpCd
   *
   * @param newInfoCheckTxTpCd the new infoCheckTxTpCd
   */

    public void  setInfoCheckTxTpCd(String newInfoCheckTxTpCd) {
        infoCheckTxTpCd = newInfoCheckTxTpCd;
    }	  
  /**
   * Returns the infoCheckSndgNbOfTxs
   * 
   * @return the infoCheckSndgNbOfTxs
   */
    @Column(name = "INFOCHECKSNDGNBOFTXS")
    public String getInfoCheckSndgNbOfTxs() {
        return infoCheckSndgNbOfTxs;
    }	 
     
  /**
   * Sets the infoCheckSndgNbOfTxs
   *
   * @param newInfoCheckSndgNbOfTxs the new infoCheckSndgNbOfTxs
   */

    public void  setInfoCheckSndgNbOfTxs(String newInfoCheckSndgNbOfTxs) {
        infoCheckSndgNbOfTxs = newInfoCheckSndgNbOfTxs;
    }	  
  /**
   * Returns the infoCheckRcvTtlCnt
   * 
   * @return the infoCheckRcvTtlCnt
   */
    @Column(name = "INFOCHECKRCVTTLCNT")
    public String getInfoCheckRcvTtlCnt() {
        return infoCheckRcvTtlCnt;
    }	 
     
  /**
   * Sets the infoCheckRcvTtlCnt
   *
   * @param newInfoCheckRcvTtlCnt the new infoCheckRcvTtlCnt
   */

    public void  setInfoCheckRcvTtlCnt(String newInfoCheckRcvTtlCnt) {
        infoCheckRcvTtlCnt = newInfoCheckRcvTtlCnt;
    }	  
  /**
   * Returns the sndDtls2
   * 
   * @return the sndDtls2
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
    public java.util.Set<Beps72600101SndDtls2> getSndDtls2() {
        return sndDtls2;
    }	 
     
  /**
   * Sets the sndDtls2
   *
   * @param newSndDtls2 the new sndDtls2
   */

    public void  setSndDtls2(java.util.Set<Beps72600101SndDtls2> newSndDtls2) {
        sndDtls2 = newSndDtls2;
    }	  
  /**
   * Returns the rcvDtls2
   * 
   * @return the rcvDtls2
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
    public java.util.Set<Beps72600101RcvDtls2> getRcvDtls2() {
        return rcvDtls2;
    }	 
     
  /**
   * Sets the rcvDtls2
   *
   * @param newRcvDtls2 the new rcvDtls2
   */

    public void  setRcvDtls2(java.util.Set<Beps72600101RcvDtls2> newRcvDtls2) {
        rcvDtls2 = newRcvDtls2;
    }	  
    
    
}    
    
