package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Beps72300101OrgnlPmtDtls generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_BEPS_723_APX_YW_MX")
public class Beps72300101OrgnlPmtDtls  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="dtlChckRspn.dtlChckRspnInf.dtlChckPmtRspnInf.dtlChckRspnDtls[0].orgnlPmtDtls[0].orgnlGrpHdr.orgnlMsgId")
    private String bizOrgnlMsgId;
    
    @JaxbMapping(objPath="dtlChckRspn.dtlChckRspnInf.dtlChckPmtRspnInf.dtlChckRspnDtls[0].orgnlPmtDtls[0].orgnlGrpHdr.orgnlInstgPty")
    private String bizOrgnlInstgDrctPty;
    
    @JaxbMapping(objPath="dtlChckRspn.dtlChckRspnInf.dtlChckPmtRspnInf.dtlChckRspnDtls[0].orgnlPmtDtls[0].orgnlGrpHdr.orgnlMsgTp")
    private String bizOrgnlMT;
    
    @JaxbMapping(objPath="dtlChckRspn.dtlChckRspnInf.dtlChckPmtRspnInf.dtlChckRspnDtls[0].orgnlPmtDtls[0].ttlCnt")
    private String bizTtlCnt;
    
    @JaxbMapping(objPath="dtlChckRspn.dtlChckRspnInf.dtlChckPmtRspnInf.dtlChckRspnDtls[0].orgnlPmtDtls[0].ctrlSum")
    private Double bizCtrlSum;
    
    @JaxbMapping(objPath="dtlChckRspn.dtlChckRspnInf.dtlChckPmtRspnInf.dtlChckRspnDtls[0].orgnlPmtDtls[0].prcSts")
    private String bizPrcSts;
    
    private Beps72300101DtlChckRspnDtls fid;
    
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Beps72300101DtlChckRspnDtls getFid() {
		return fid;
	}


	public void setFid(Beps72300101DtlChckRspnDtls fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Beps72300101OrgnlPmtDtls() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the bizOrgnlMsgId
   * 
   * @return the bizOrgnlMsgId
   */
    @Column(name = "BIZORGNLMSGID")
    public String getBizOrgnlMsgId() {
        return bizOrgnlMsgId;
    }	 
     
  /**
   * Sets the bizOrgnlMsgId
   *
   * @param newBizOrgnlMsgId the new bizOrgnlMsgId
   */

    public void  setBizOrgnlMsgId(String newBizOrgnlMsgId) {
        bizOrgnlMsgId = newBizOrgnlMsgId;
    }	  
  /**
   * Returns the bizOrgnlInstgDrctPty
   * 
   * @return the bizOrgnlInstgDrctPty
   */
    @Column(name = "BIZORGNLINSTGDRCTPTY")
    public String getBizOrgnlInstgDrctPty() {
        return bizOrgnlInstgDrctPty;
    }	 
     
  /**
   * Sets the bizOrgnlInstgDrctPty
   *
   * @param newBizOrgnlInstgDrctPty the new bizOrgnlInstgDrctPty
   */

    public void  setBizOrgnlInstgDrctPty(String newBizOrgnlInstgDrctPty) {
        bizOrgnlInstgDrctPty = newBizOrgnlInstgDrctPty;
    }	  
  /**
   * Returns the bizOrgnlMT
   * 
   * @return the bizOrgnlMT
   */
    @Column(name = "BIZORGNLMT")
    public String getBizOrgnlMT() {
        return bizOrgnlMT;
    }	 
     
  /**
   * Sets the bizOrgnlMT
   *
   * @param newBizOrgnlMT the new bizOrgnlMT
   */

    public void  setBizOrgnlMT(String newBizOrgnlMT) {
        bizOrgnlMT = newBizOrgnlMT;
    }	  
  /**
   * Returns the bizTtlCnt
   * 
   * @return the bizTtlCnt
   */
    @Column(name = "BIZTTLCNT")
    public String getBizTtlCnt() {
        return bizTtlCnt;
    }	 
     
  /**
   * Sets the bizTtlCnt
   *
   * @param newBizTtlCnt the new bizTtlCnt
   */

    public void  setBizTtlCnt(String newBizTtlCnt) {
        bizTtlCnt = newBizTtlCnt;
    }	  
  /**
   * Returns the bizCtrlSum
   * 
   * @return the bizCtrlSum
   */
    @Column(name = "BIZCTRLSUM")
    public Double getBizCtrlSum() {
        return bizCtrlSum;
    }	 
     
  /**
   * Sets the bizCtrlSum
   *
   * @param newBizCtrlSum the new bizCtrlSum
   */

    public void  setBizCtrlSum(Double newBizCtrlSum) {
        bizCtrlSum = newBizCtrlSum;
    }	  
  /**
   * Returns the bizPrcSts
   * 
   * @return the bizPrcSts
   */
    @Column(name = "BIZPRCSTS")
    public String getBizPrcSts() {
        return bizPrcSts;
    }	 
     
  /**
   * Sets the bizPrcSts
   *
   * @param newBizPrcSts the new bizPrcSts
   */

    public void  setBizPrcSts(String newBizPrcSts) {
        bizPrcSts = newBizPrcSts;
    }	  
    
    
}    
    
