package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Beps41100101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_BEPS_411_HDR")
public class Beps41100101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="cstmrPmtCxlReq.assgnmt.id")
    private String msgId;
    
    @JaxbMapping(objPath="cstmrPmtCxlReq.assgnmt.assgnr.agt.finInstnId.clrSysMmbId.mmbId")
    private String instgDrctPty;
    
    @JaxbMapping(objPath="cstmrPmtCxlReq.assgnmt.assgnr.agt.brnchId.id")
    private String instgIndrctPty;
    
    @JaxbMapping(objPath="cstmrPmtCxlReq.assgnmt.assgne.agt.finInstnId.clrSysMmbId.mmbId")
    private String instdDrctPty;
    
    @JaxbMapping(objPath="cstmrPmtCxlReq.assgnmt.assgne.agt.brnchId.id")
    private String instgIndrctPty1;
    
    @JaxbMapping(objPath="cstmrPmtCxlReq.assgnmt.creDtTm")
    private Date creDtTm;
    
    @JaxbMapping(objPath="cstmrPmtCxlReq.undrlyg.orgnlGrpInfAndCxl.grpCxlId")
    private String grpCxlId;
    
    @JaxbMapping(objPath="cstmrPmtCxlReq.undrlyg.orgnlGrpInfAndCxl.Case.id")
    private String identification;
    
    @JaxbMapping(objPath="cstmrPmtCxlReq.undrlyg.orgnlGrpInfAndCxl.Case.cretr.agt.finInstnId.clrSysMmbId.mmbId")
    private String mmbId;
    
    @JaxbMapping(objPath="cstmrPmtCxlReq.undrlyg.orgnlGrpInfAndCxl.orgnlMsgId")
    private String orgnlMsgId;
    
    @JaxbMapping(objPath="cstmrPmtCxlReq.undrlyg.orgnlGrpInfAndCxl.orgnlMsgNmId")
    private String orgnlMsgNmId;
    
    @JaxbMapping(objPath="cstmrPmtCxlReq.undrlyg.orgnlGrpInfAndCxl.cxlRsnInf.addtlInf")
    private String addtInf;
    
    @JaxbMapping(objPath="cstmrPmtCxlReq.undrlyg.orgnlPmtInfAndCxl[0]")
    private java.util.Set<Beps41100101OrgnlPmtInfId> orgnlPmtInfId1;
    
    
	
    /** default constructor */
    public Beps41100101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the instgDrctPty
   * 
   * @return the instgDrctPty
   */
    @Column(name = "INSTGDRCTPTY")
    public String getInstgDrctPty() {
        return instgDrctPty;
    }	 
     
  /**
   * Sets the instgDrctPty
   *
   * @param newInstgDrctPty the new instgDrctPty
   */

    public void  setInstgDrctPty(String newInstgDrctPty) {
        instgDrctPty = newInstgDrctPty;
    }	  
  /**
   * Returns the instgIndrctPty
   * 
   * @return the instgIndrctPty
   */
    @Column(name = "INSTGINDRCTPTY")
    public String getInstgIndrctPty() {
        return instgIndrctPty;
    }	 
     
  /**
   * Sets the instgIndrctPty
   *
   * @param newInstgIndrctPty the new instgIndrctPty
   */

    public void  setInstgIndrctPty(String newInstgIndrctPty) {
        instgIndrctPty = newInstgIndrctPty;
    }	  
  /**
   * Returns the instdDrctPty
   * 
   * @return the instdDrctPty
   */
    @Column(name = "INSTDDRCTPTY")
    public String getInstdDrctPty() {
        return instdDrctPty;
    }	 
     
  /**
   * Sets the instdDrctPty
   *
   * @param newInstdDrctPty the new instdDrctPty
   */

    public void  setInstdDrctPty(String newInstdDrctPty) {
        instdDrctPty = newInstdDrctPty;
    }	  
  /**
   * Returns the instgIndrctPty1
   * 
   * @return the instgIndrctPty1
   */
    @Column(name = "INSTDINDRCTPTY")
    public String getInstgIndrctPty1() {
        return instgIndrctPty1;
    }	 
     
  /**
   * Sets the instgIndrctPty1
   *
   * @param newInstgIndrctPty1 the new instgIndrctPty1
   */

    public void  setInstgIndrctPty1(String newInstgIndrctPty1) {
        instgIndrctPty1 = newInstgIndrctPty1;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public Date getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(Date newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the grpCxlId
   * 
   * @return the grpCxlId
   */
    @Column(name = "GRPCXLID")
    public String getGrpCxlId() {
        return grpCxlId;
    }	 
     
  /**
   * Sets the grpCxlId
   *
   * @param newGrpCxlId the new grpCxlId
   */

    public void  setGrpCxlId(String newGrpCxlId) {
        grpCxlId = newGrpCxlId;
    }	  
  /**
   * Returns the identification
   * 
   * @return the identification
   */
    @Column(name = "IDENTIFICATION")
    public String getIdentification() {
        return identification;
    }	 
     
  /**
   * Sets the identification
   *
   * @param newIdentification the new identification
   */

    public void  setIdentification(String newIdentification) {
        identification = newIdentification;
    }	  
  /**
   * Returns the mmbId
   * 
   * @return the mmbId
   */
    @Column(name = "MMBID")
    public String getMmbId() {
        return mmbId;
    }	 
     
  /**
   * Sets the mmbId
   *
   * @param newMmbId the new mmbId
   */

    public void  setMmbId(String newMmbId) {
        mmbId = newMmbId;
    }	  
  /**
   * Returns the orgnlMsgId
   * 
   * @return the orgnlMsgId
   */
    @Column(name = "ORGNLMSGID")
    public String getOrgnlMsgId() {
        return orgnlMsgId;
    }	 
     
  /**
   * Sets the orgnlMsgId
   *
   * @param newOrgnlMsgId the new orgnlMsgId
   */

    public void  setOrgnlMsgId(String newOrgnlMsgId) {
        orgnlMsgId = newOrgnlMsgId;
    }	  
  /**
   * Returns the orgnlMsgNmId
   * 
   * @return the orgnlMsgNmId
   */
    @Column(name = "ORGNLMSGNMID")
    public String getOrgnlMsgNmId() {
        return orgnlMsgNmId;
    }	 
     
  /**
   * Sets the orgnlMsgNmId
   *
   * @param newOrgnlMsgNmId the new orgnlMsgNmId
   */

    public void  setOrgnlMsgNmId(String newOrgnlMsgNmId) {
        orgnlMsgNmId = newOrgnlMsgNmId;
    }	  
  /**
   * Returns the addtInf
   * 
   * @return the addtInf
   */
    @Column(name = "ADDTINF")
    public String getOrgnlPmtInfId() {
        return addtInf;
    }	 
     
  /**
   * Sets the addtInf
   *
   * @param newAddtInf the new addtInf
   */

    public void  setOrgnlPmtInfId(String newAddtInf) {
    	addtInf = newAddtInf;
    }	  
  /**
   * Returns the orgnlPmtInfId1
   * 
   * @return the orgnlPmtInfId1
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
    public java.util.Set<Beps41100101OrgnlPmtInfId> getOrgnlPmtInfId1() {
        return orgnlPmtInfId1;
    }	 
     
  /**
   * Sets the orgnlPmtInfId1
   *
   * @param newOrgnlPmtInfId1 the new orgnlPmtInfId1
   */

    public void  setOrgnlPmtInfId1(java.util.Set<Beps41100101OrgnlPmtInfId> newOrgnlPmtInfId1) {
        orgnlPmtInfId1 = newOrgnlPmtInfId1;
    }	  
    
    
}    
    
