package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Beps13100101RealTmColltnInf generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_BEPS_131_APX_SSDS")
public class Beps13100101RealTmColltnInf  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="realTmCstmrDrctDbt.realTmCstmrDrctDbtInf.realTmCstmrDrctDbtAddtlInf.realTmColltnInf.orgnlGrpHdr.orgnlMsgId")
    private String orgnlMsgId;
    
    @JaxbMapping(objPath="realTmCstmrDrctDbt.realTmCstmrDrctDbtInf.realTmCstmrDrctDbtAddtlInf.realTmColltnInf.orgnlGrpHdr.orgnlInstgPty")
    private String orgnlInstgDrctPty;
    
    @JaxbMapping(objPath="realTmCstmrDrctDbt.realTmCstmrDrctDbtInf.realTmCstmrDrctDbtAddtlInf.realTmColltnInf.orgnlGrpHdr.orgnlMsgTp")
    private String orgnlMT;
    
    @JaxbMapping(objPath="realTmCstmrDrctDbt.realTmCstmrDrctDbtInf.realTmCstmrDrctDbtAddtlInf.realTmColltnInf.ctrctNb")
    private String ctrctNb;
    
    private Beps13100101 fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Beps13100101 getFid() {
		return fid;
	}


	public void setFid(Beps13100101 fid) {
		this.fid = fid;
	}
	
    /** default constructor */
    public Beps13100101RealTmColltnInf() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the orgnlMsgId
   * 
   * @return the orgnlMsgId
   */
    @Column(name = "ORGNLMSGID")
    public String getOrgnlMsgId() {
        return orgnlMsgId;
    }	 
     
  /**
   * Sets the orgnlMsgId
   *
   * @param newOrgnlMsgId the new orgnlMsgId
   */

    public void  setOrgnlMsgId(String newOrgnlMsgId) {
        orgnlMsgId = newOrgnlMsgId;
    }	  
  /**
   * Returns the orgnlInstgDrctPty
   * 
   * @return the orgnlInstgDrctPty
   */
    @Column(name = "ORGNLINSTGDRCTPTY")
    public String getOrgnlInstgDrctPty() {
        return orgnlInstgDrctPty;
    }	 
     
  /**
   * Sets the orgnlInstgDrctPty
   *
   * @param newOrgnlInstgDrctPty the new orgnlInstgDrctPty
   */

    public void  setOrgnlInstgDrctPty(String newOrgnlInstgDrctPty) {
        orgnlInstgDrctPty = newOrgnlInstgDrctPty;
    }	  
  /**
   * Returns the orgnlMT
   * 
   * @return the orgnlMT
   */
    @Column(name = "ORGNLMT")
    public String getOrgnlMT() {
        return orgnlMT;
    }	 
     
  /**
   * Sets the orgnlMT
   *
   * @param newOrgnlMT the new orgnlMT
   */

    public void  setOrgnlMT(String newOrgnlMT) {
        orgnlMT = newOrgnlMT;
    }	  
  /**
   * Returns the ctrctNb
   * 
   * @return the ctrctNb
   */
    @Column(name = "CTRCTNB")
    public String getCtrctNb() {
        return ctrctNb;
    }	 
     
  /**
   * Sets the ctrctNb
   *
   * @param newCtrctNb the new ctrctNb
   */

    public void  setCtrctNb(String newCtrctNb) {
        ctrctNb = newCtrctNb;
    }	  
    
    
}    
    
