package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Ccms91600101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_CCMS_916")
public class Ccms91600101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].chngCtrl.chngTp")
    private String chngTp;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].chngCtrl.fctvTp")
    private String fctvTp;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].chngCtrl.fctvDt")
    private Date fctvDt;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].chngCtrl.ifctvDt")
    private Date ifctvDt;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].bkCd")
    private String bkCd;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].ptcptTp")
    private String ptcptTp;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].bkCtgyCd")
    private String bkCtgyCd;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].drctBkCd")
    private String drctBkCd;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].lglPrsn")
    private String lglPrsn;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].hghPtcpt")
    private String hghPtcpt;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].brBkCd")
    private String brBkCd;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].chrgBkCd")
    private String chrgBkCd;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].ndCd")
    private String ndCd;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].cityCd")
    private String cityCd;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].ptcptNm")
    private String ptcptNm;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].ptcptShrtNm")
    private String ptcptShrtNm;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].sgn")
    private String sgn;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].adr")
    private String adr;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].pstCd")
    private String pstCd;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].email")
    private String email;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].email")
    private String tel;
    
    @JaxbMapping(objPath="bkCdChngNtfctn.chngInf[0].rmkInf")
    private String rmkInf;
    
    private Ccms91600101Hdr fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Ccms91600101Hdr getFid() {
		return fid;
	}


	public void setFid(Ccms91600101Hdr fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Ccms91600101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the chngTp
   * 
   * @return the chngTp
   */
    @Column(name = "CHNGTP")
    public String getChngTp() {
        return chngTp;
    }	 
     
  /**
   * Sets the chngTp
   *
   * @param newChngTp the new chngTp
   */

    public void  setChngTp(String newChngTp) {
        chngTp = newChngTp;
    }	  
  /**
   * Returns the fctvTp
   * 
   * @return the fctvTp
   */
    @Column(name = "FCTVTP")
    public String getFctvTp() {
        return fctvTp;
    }	 
     
  /**
   * Sets the fctvTp
   *
   * @param newFctvTp the new fctvTp
   */

    public void  setFctvTp(String newFctvTp) {
        fctvTp = newFctvTp;
    }	  
  /**
   * Returns the fctvDt
   * 
   * @return the fctvDt
   */
    @Column(name = "FCTVDT")
    public Date getFctvDt() {
        return fctvDt;
    }	 
     
  /**
   * Sets the fctvDt
   *
   * @param newFctvDt the new fctvDt
   */

    public void  setFctvDt(Date newFctvDt) {
        fctvDt = newFctvDt;
    }	  
  /**
   * Returns the ifctvDt
   * 
   * @return the ifctvDt
   */
    @Column(name = "IFCTVDT")
    public Date getIfctvDt() {
        return ifctvDt;
    }	 
     
  /**
   * Sets the ifctvDt
   *
   * @param newIfctvDt the new ifctvDt
   */

    public void  setIfctvDt(Date newIfctvDt) {
        ifctvDt = newIfctvDt;
    }	  
  /**
   * Returns the bkCd
   * 
   * @return the bkCd
   */
    @Column(name = "BKCD")
    public String getBkCd() {
        return bkCd;
    }	 
     
  /**
   * Sets the bkCd
   *
   * @param newBkCd the new bkCd
   */

    public void  setBkCd(String newBkCd) {
        bkCd = newBkCd;
    }	  
  /**
   * Returns the ptcptTp
   * 
   * @return the ptcptTp
   */
    @Column(name = "PTCPTTP")
    public String getPtcptTp() {
        return ptcptTp;
    }	 
     
  /**
   * Sets the ptcptTp
   *
   * @param newPtcptTp the new ptcptTp
   */

    public void  setPtcptTp(String newPtcptTp) {
        ptcptTp = newPtcptTp;
    }	  
  /**
   * Returns the bkCtgyCd
   * 
   * @return the bkCtgyCd
   */
    @Column(name = "BKCTGYCD")
    public String getBkCtgyCd() {
        return bkCtgyCd;
    }	 
     
  /**
   * Sets the bkCtgyCd
   *
   * @param newBkCtgyCd the new bkCtgyCd
   */

    public void  setBkCtgyCd(String newBkCtgyCd) {
        bkCtgyCd = newBkCtgyCd;
    }	  
  /**
   * Returns the drctBkCd
   * 
   * @return the drctBkCd
   */
    @Column(name = "DRCTBKCD")
    public String getDrctBkCd() {
        return drctBkCd;
    }	 
     
  /**
   * Sets the drctBkCd
   *
   * @param newDrctBkCd the new drctBkCd
   */

    public void  setDrctBkCd(String newDrctBkCd) {
        drctBkCd = newDrctBkCd;
    }	  
  /**
   * Returns the lglPrsn
   * 
   * @return the lglPrsn
   */
    @Column(name = "LGLPRSN")
    public String getLglPrsn() {
        return lglPrsn;
    }	 
     
  /**
   * Sets the lglPrsn
   *
   * @param newLglPrsn the new lglPrsn
   */

    public void  setLglPrsn(String newLglPrsn) {
        lglPrsn = newLglPrsn;
    }	  
  /**
   * Returns the hghPtcpt
   * 
   * @return the hghPtcpt
   */
    @Column(name = "HGHPTCPT")
    public String getHghPtcpt() {
        return hghPtcpt;
    }	 
     
  /**
   * Sets the hghPtcpt
   *
   * @param newHghPtcpt the new hghPtcpt
   */

    public void  setHghPtcpt(String newHghPtcpt) {
        hghPtcpt = newHghPtcpt;
    }	  
  /**
   * Returns the brBkCd
   * 
   * @return the brBkCd
   */
    @Column(name = "BRBKCD")
    public String getBrBkCd() {
        return brBkCd;
    }	 
     
  /**
   * Sets the brBkCd
   *
   * @param newBrBkCd the new brBkCd
   */

    public void  setBrBkCd(String newBrBkCd) {
        brBkCd = newBrBkCd;
    }	  
  /**
   * Returns the chrgBkCd
   * 
   * @return the chrgBkCd
   */
    @Column(name = "CHRGBKCD")
    public String getChrgBkCd() {
        return chrgBkCd;
    }	 
     
  /**
   * Sets the chrgBkCd
   *
   * @param newChrgBkCd the new chrgBkCd
   */

    public void  setChrgBkCd(String newChrgBkCd) {
        chrgBkCd = newChrgBkCd;
    }	  
  /**
   * Returns the ndCd
   * 
   * @return the ndCd
   */
    @Column(name = "NDCD")
    public String getNdCd() {
        return ndCd;
    }	 
     
  /**
   * Sets the ndCd
   *
   * @param newNdCd the new ndCd
   */

    public void  setNdCd(String newNdCd) {
        ndCd = newNdCd;
    }	  
  /**
   * Returns the cityCd
   * 
   * @return the cityCd
   */
    @Column(name = "CITYCD")
    public String getCityCd() {
        return cityCd;
    }	 
     
  /**
   * Sets the cityCd
   *
   * @param newCityCd1 the new cityCd
   */

    public void  setCityCd(String newCityCd) {
        cityCd = newCityCd;
    }	  
  /**
   * Returns the ptcptNm
   * 
   * @return the ptcptNm
   */
    @Column(name = "PTCPTNM")
    public String getPtcptNm() {
        return ptcptNm;
    }	 
     
  /**
   * Sets the ptcptNm
   *
   * @param newPtcptNm the new ptcptNm
   */

    public void  setPtcptNm(String newPtcptNm) {
        ptcptNm = newPtcptNm;
    }	  
  /**
   * Returns the ptcptShrtNm
   * 
   * @return the ptcptShrtNm
   */
    @Column(name = "PTCPTSHRTNM")
    public String getPtcptShrtNm() {
        return ptcptShrtNm;
    }	 
     
  /**
   * Sets the ptcptShrtNm
   *
   * @param newPtcptShrtNm the new ptcptShrtNm
   */

    public void  setPtcptShrtNm(String newPtcptShrtNm) {
        ptcptShrtNm = newPtcptShrtNm;
    }	  
  /**
   * Returns the sgn
   * 
   * @return the sgn
   */
    @Column(name = "SGN")
    public String getSgn() {
        return sgn;
    }	 
     
  /**
   * Sets the sgn
   *
   * @param newSgn the new sgn
   */

    public void  setSgn(String newSgn) {
        sgn = newSgn;
    }	  
  /**
   * Returns the adr
   * 
   * @return the adr
   */
    @Column(name = "ADR")
    public String getAdr() {
        return adr;
    }	 
     
  /**
   * Sets the adr
   *
   * @param newAdr the new adr
   */

    public void  setAdr(String newAdr) {
        adr = newAdr;
    }	  
  /**
   * Returns the pstCd
   * 
   * @return the pstCd
   */
    @Column(name = "PSTCD")
    public String getPstCd() {
        return pstCd;
    }	 
     
  /**
   * Sets the pstCd
   *
   * @param newPstCd the new pstCd
   */

    public void  setPstCd(String newPstCd) {
        pstCd = newPstCd;
    }	  
  /**
   * Returns the email
   * 
   * @return the email
   */
    @Column(name = "EMAIL")
    public String getEmail() {
        return email;
    }	 
     
  /**
   * Sets the email
   *
   * @param newEmail the new email
   */

    public void  setEmail(String newEmail) {
        email = newEmail;
    }	  
  /**
   * Returns the tel
   * 
   * @return the tel
   */
    @Column(name = "TEL")
    public String getTel() {
        return tel;
    }	 
     
  /**
   * Sets the tel
   *
   * @param newTel the new tel
   */

    public void  setTel(String newTel) {
        tel = newTel;
    }	  
  /**
   * Returns the rmkInf
   * 
   * @return the rmkInf
   */
    @Column(name = "RMKINF")
    public String getRmkInf() {
        return rmkInf;
    }	 
     
  /**
   * Sets the rmkInf
   *
   * @param newRmkInf the new rmkInf
   */

    public void  setRmkInf(String newRmkInf) {
        rmkInf = newRmkInf;
    }	  
    
    
}    
    
