package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Ccms99200101Hdr generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_CCMS_992_HDR")
public class Ccms99200101Hdr  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="chckRspn.chckRspnInf.origSndNd")
    private String origSndNd;
    
    @JaxbMapping(objPath="chckRspn.chckRspnInf.origSndSvsrNm")
    private String origSndSvsrNm;
    
    @JaxbMapping(objPath="chckRspn.chckRspnInf.origSndSvsrNm")
    private String origSndSvsrNm1;
    
    @JaxbMapping(objPath="chckRspn.chckRspnInf.rcvRoadNm")
    private String rcvRoadNm;
    
    @JaxbMapping(objPath="chckRspn.chckRspnInf.origSndDt")
    private String origSndDt;
    
    @JaxbMapping(objPath="chckRspn.chckRspnInf.rspnSvcrNm")
    private String rspnSvcrNm;
    
    @JaxbMapping(objPath="chckRspn.chckRspnInf.rspnSvcrNm")
    private String rspnSvcrNm1;
    
    @JaxbMapping(objPath="chckRspn.chckRspnInf.rspnLineMgr")
    private String rspnLineMgr;
    
    @JaxbMapping(objPath="chckRspn.chckRspnInf.rcvLineNm")
    private String rcvLineNm;
    
    @JaxbMapping(objPath="chckRspn.ldFctrInf[0]")
    private java.util.Set<Ccms99200101> ldFctrInf;
    
    
	
    /** default constructor */
    public Ccms99200101Hdr() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
    @Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the origSndNd
   * 
   * @return the origSndNd
   */
    @Column(name = "ORIGSNDND")
    public String getOrigSndNd() {
        return origSndNd;
    }	 
     
  /**
   * Sets the origSndNd
   *
   * @param newOrigSndNd the new origSndNd
   */

    public void  setOrigSndNd(String newOrigSndNd) {
        origSndNd = newOrigSndNd;
    }	  
  /**
   * Returns the origSndSvsrNm
   * 
   * @return the origSndSvsrNm
   */
    @Column(name = "ORIGSNDSVSRNM")
    public String getOrigSndSvsrNm() {
        return origSndSvsrNm;
    }	 
     
  /**
   * Sets the origSndSvsrNm
   *
   * @param newOrigSndSvsrNm the new origSndSvsrNm
   */

    public void  setOrigSndSvsrNm(String newOrigSndSvsrNm) {
        origSndSvsrNm = newOrigSndSvsrNm;
    }	  
  /**
   * Returns the origSndSvsrNm1
   * 
   * @return the origSndSvsrNm1
   */
    @Column(name = "ORIGSNDSVSRNM1")
    public String getOrigSndSvsrNm1() {
        return origSndSvsrNm1;
    }	 
     
  /**
   * Sets the origSndSvsrNm1
   *
   * @param newOrigSndSvsrNm1 the new origSndSvsrNm1
   */

    public void  setOrigSndSvsrNm1(String newOrigSndSvsrNm1) {
        origSndSvsrNm1 = newOrigSndSvsrNm1;
    }	  
  /**
   * Returns the rcvRoadNm
   * 
   * @return the rcvRoadNm
   */
    @Column(name = "RCVROADNM")
    public String getRcvRoadNm() {
        return rcvRoadNm;
    }	 
     
  /**
   * Sets the rcvRoadNm
   *
   * @param newRcvRoadNm the new rcvRoadNm
   */

    public void  setRcvRoadNm(String newRcvRoadNm) {
        rcvRoadNm = newRcvRoadNm;
    }	  
  /**
   * Returns the origSndDt
   * 
   * @return the origSndDt
   */
    @Column(name = "ORIGSNDDT")
    public String getOrigSndDt() {
        return origSndDt;
    }	 
     
  /**
   * Sets the origSndDt
   *
   * @param newOrigSndDt the new origSndDt
   */

    public void  setOrigSndDt(String newOrigSndDt) {
        origSndDt = newOrigSndDt;
    }	  
  /**
   * Returns the rspnSvcrNm
   * 
   * @return the rspnSvcrNm
   */
    @Column(name = "RSPNSVCRNM")
    public String getRspnSvcrNm() {
        return rspnSvcrNm;
    }	 
     
  /**
   * Sets the rspnSvcrNm
   *
   * @param newRspnSvcrNm the new rspnSvcrNm
   */

    public void  setRspnSvcrNm(String newRspnSvcrNm) {
        rspnSvcrNm = newRspnSvcrNm;
    }	  
  /**
   * Returns the rspnSvcrNm1
   * 
   * @return the rspnSvcrNm1
   */
    @Column(name = "RSPNSVCRNM1")
    public String getRspnSvcrNm1() {
        return rspnSvcrNm1;
    }	 
     
  /**
   * Sets the rspnSvcrNm1
   *
   * @param newRspnSvcrNm1 the new rspnSvcrNm1
   */

    public void  setRspnSvcrNm1(String newRspnSvcrNm1) {
        rspnSvcrNm1 = newRspnSvcrNm1;
    }	  
  /**
   * Returns the rspnLineMgr
   * 
   * @return the rspnLineMgr
   */
    @Column(name = "RSPNLINEMGR")
    public String getRspnLineMgr() {
        return rspnLineMgr;
    }	 
     
  /**
   * Sets the rspnLineMgr
   *
   * @param newRspnLineMgr the new rspnLineMgr
   */

    public void  setRspnLineMgr(String newRspnLineMgr) {
        rspnLineMgr = newRspnLineMgr;
    }	  
  /**
   * Returns the rcvLineNm
   * 
   * @return the rcvLineNm
   */
    @Column(name = "RCVLINENM")
    public String getRcvLineNm() {
        return rcvLineNm;
    }	 
     
  /**
   * Sets the rcvLineNm
   *
   * @param newRcvLineNm the new rcvLineNm
   */

    public void  setRcvLineNm(String newRcvLineNm) {
        rcvLineNm = newRcvLineNm;
    }	  
  /**
   * Returns the ldFctrInf
   * 
   * @return the ldFctrInf
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
    public java.util.Set<Ccms99200101> getLdFctrInf() {
        return ldFctrInf;
    }	 
     
  /**
   * Sets the ldFctrInf
   *
   * @param newLdFctrInf the new ldFctrInf
   */

    public void  setLdFctrInf(java.util.Set<Ccms99200101> newLdFctrInf) {
        ldFctrInf = newLdFctrInf;
    }	  
    
    
}    
    
