package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Ccms91300101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_CCMS_913")
public class Ccms91300101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="cisAgcyChngNtfctn.chngInf[0].chngCtrl.chngTp")
    private String chngTp;
    
    @JaxbMapping(objPath="cisAgcyChngNtfctn.chngInf[0].chngCtrl.fctvTp")
    private String fctvTp;
    
    @JaxbMapping(objPath="cisAgcyChngNtfctn.chngInf[0].chngCtrl.fctvDt")
    private Date fctvDt;
    
    @JaxbMapping(objPath="cisAgcyChngNtfctn.chngInf[0].chngCtrl.ifctvDt")
    private Date ifctvDt;
    
    @JaxbMapping(objPath="cisAgcyChngNtfctn.chngInf[0].ncisBkCd")
    private String ncisBkCd;
    
    @JaxbMapping(objPath="cisAgcyChngNtfctn.chngInf[0].bepsAgcyBkCd")
    private String bepsAgcyBkCd;
    
    private Ccms91300101Hdr fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Ccms91300101Hdr getFid() {
		return fid;
	}


	public void setFid(Ccms91300101Hdr fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Ccms91300101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the chngTp
   * 
   * @return the chngTp
   */
    @Column(name = "CHNGTP")
    public String getChngTp() {
        return chngTp;
    }	 
     
  /**
   * Sets the chngTp
   *
   * @param newChngTp the new chngTp
   */

    public void  setChngTp(String newChngTp) {
        chngTp = newChngTp;
    }	  
  /**
   * Returns the fctvTp
   * 
   * @return the fctvTp
   */
    @Column(name = "FCTVTP")
    public String getFctvTp() {
        return fctvTp;
    }	 
     
  /**
   * Sets the fctvTp
   *
   * @param newFctvTp the new fctvTp
   */

    public void  setFctvTp(String newFctvTp) {
        fctvTp = newFctvTp;
    }	  
  /**
   * Returns the fctvDt
   * 
   * @return the fctvDt
   */
    @Column(name = "FCTVDT")
    public Date getFctvDt() {
        return fctvDt;
    }	 
     
  /**
   * Sets the fctvDt
   *
   * @param newFctvDt the new fctvDt
   */

    public void  setFctvDt(Date newFctvDt) {
        fctvDt = newFctvDt;
    }	  
  /**
   * Returns the ifctvDt
   * 
   * @return the ifctvDt
   */
    @Column(name = "IFCTVDT")
    public Date getIfctvDt() {
        return ifctvDt;
    }	 
     
  /**
   * Sets the ifctvDt
   *
   * @param newIfctvDt the new ifctvDt
   */

    public void  setIfctvDt(Date newIfctvDt) {
        ifctvDt = newIfctvDt;
    }	  
  /**
   * Returns the ncisBkCd
   * 
   * @return the ncisBkCd
   */
    @Column(name = "NCISBKCD")
    public String getNcisBkCd() {
        return ncisBkCd;
    }	 
     
  /**
   * Sets the ncisBkCd
   *
   * @param newNcisBkCd the new ncisBkCd
   */

    public void  setNcisBkCd(String newNcisBkCd) {
        ncisBkCd = newNcisBkCd;
    }	  
  /**
   * Returns the bepsAgcyBkCd
   * 
   * @return the bepsAgcyBkCd
   */
    @Column(name = "BEPSAGCYBKCD")
    public String getBepsAgcyBkCd() {
        return bepsAgcyBkCd;
    }	 
     
  /**
   * Sets the bepsAgcyBkCd
   *
   * @param newBepsAgcyBkCd the new bepsAgcyBkCd
   */

    public void  setBepsAgcyBkCd(String newBepsAgcyBkCd) {
        bepsAgcyBkCd = newBepsAgcyBkCd;
    }	  
    
    
}    
    
