package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Ccms91500101BizAuthrtyInf generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_CCMS_915_APX_PRIV")
public class Ccms91500101BizAuthrtyInf  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="authrtyChngNtfctn.authrtyInf[0].bizAuthrtyInf[0].mt")
    private String mT;
    
    @JaxbMapping(objPath="authrtyChngNtfctn.authrtyInf[0].bizAuthrtyInf[0].txTpCd")
    private String txTpCd;
    
    @JaxbMapping(objPath="authrtyChngNtfctn.authrtyInf[0].bizAuthrtyInf[0].authrtySgnCd")
    private String authrtySgnCd;
    
    @JaxbMapping(objPath="authrtyChngNtfctn.authrtyInf[0].bizAuthrtyInf[0].authrtyWght")
    private String authrtyWght;
    
    private Ccms91500101AuthrtyInf fid;
    
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Ccms91500101AuthrtyInf getFid() {
		return fid;
	}


	public void setFid(Ccms91500101AuthrtyInf fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Ccms91500101BizAuthrtyInf() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the mT
   * 
   * @return the mT
   */
    @Column(name = "MT")
    public String getMT() {
        return mT;
    }	 
     
  /**
   * Sets the mT
   *
   * @param newMT the new mT
   */

    public void  setMT(String newMT) {
        mT = newMT;
    }	  
  /**
   * Returns the txTpCd
   * 
   * @return the txTpCd
   */
    @Column(name = "TXTPCD")
    public String getTxTpCd() {
        return txTpCd;
    }	 
     
  /**
   * Sets the txTpCd
   *
   * @param newTxTpCd the new txTpCd
   */

    public void  setTxTpCd(String newTxTpCd) {
        txTpCd = newTxTpCd;
    }	  
  /**
   * Returns the authrtySgnCd
   * 
   * @return the authrtySgnCd
   */
    @Column(name = "AUTHRTYSGNCD")
    public String getAuthrtySgnCd() {
        return authrtySgnCd;
    }	 
     
  /**
   * Sets the authrtySgnCd
   *
   * @param newAuthrtySgnCd the new authrtySgnCd
   */

    public void  setAuthrtySgnCd(String newAuthrtySgnCd) {
        authrtySgnCd = newAuthrtySgnCd;
    }	  
  /**
   * Returns the authrtyWght
   * 
   * @return the authrtyWght
   */
    @Column(name = "AUTHRTYWGHT")
    public String getAuthrtyWght() {
        return authrtyWght;
    }	 
     
  /**
   * Sets the authrtyWght
   *
   * @param newAuthrtyWght the new authrtyWght
   */

    public void  setAuthrtyWght(String newAuthrtyWght) {
        authrtyWght = newAuthrtyWght;
    }	  
    
    
}    
    
