package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Ccms31800101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_CCMS_318_HDR")
public class Ccms31800101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="pmtRtr.grpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="pmtRtr.grpHdr.creDtTm")
    private Date creDtTm;
    
    @JaxbMapping(objPath="pmtRtr.grpHdr.nbOfTxs")
    private String nbOfTxs;
    
    @JaxbMapping(objPath="pmtRtr.grpHdr.sttlmInf.sttlmMtd")
    private String sttlmMtd;
    
    @JaxbMapping(objPath="pmtRtr.grpHdr.instgAgt.finInstnId.clrSysMmbId.mmbId")
    private String sDMmbId;
    
    @JaxbMapping(objPath="pmtRtr.grpHdr.instgAgt.brnchId.id")
    private String sInDId;
    
    @JaxbMapping(objPath="pmtRtr.grpHdr.instdAgt.finInstnId.clrSysMmbId.mmbId")
    private String rDMmbId;
    
    @JaxbMapping(objPath="pmtRtr.grpHdr.instdAgt.brnchId.id")
    private String rInDId;
    
    @JaxbMapping(objPath="pmtRtr.orgnlGrpInf.orgnlMsgId")
    private String orgnlMsgId;
    
    @JaxbMapping(objPath="pmtRtr.orgnlGrpInf.orgnlMsgNmId")
    private String orgnlMsgNmId;
    
    @JaxbMapping(objPath="pmtRtr.orgnlGrpInf.rtrRsnInf.orgtr.id.orgId.othr.id")
    private String orgnlSen;
    
    @JaxbMapping(objPath="pmtRtr.orgnlGrpInf.rtrRsnInf.addtlInf")
    private String reTp;
    
    @JaxbMapping(objPath="pmtRtr.txInf[0]")
    private java.util.Set<Ccms31800101TxInf> txInf;
    
    
	
    /** default constructor */
    public Ccms31800101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public Date getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(Date newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the nbOfTxs
   * 
   * @return the nbOfTxs
   */
    @Column(name = "NBOFTXS")
    public String getNbOfTxs() {
        return nbOfTxs;
    }	 
     
  /**
   * Sets the nbOfTxs
   *
   * @param newNbOfTxs the new nbOfTxs
   */

    public void  setNbOfTxs(String newNbOfTxs) {
        nbOfTxs = newNbOfTxs;
    }	  
  /**
   * Returns the sttlmMtd
   * 
   * @return the sttlmMtd
   */
    @Column(name = "STTLMMTD")
    public String getSttlmMtd() {
        return sttlmMtd;
    }	 
     
  /**
   * Sets the sttlmMtd
   *
   * @param newSttlmMtd the new sttlmMtd
   */

    public void  setSttlmMtd(String newSttlmMtd) {
        sttlmMtd = newSttlmMtd;
    }	  
  /**
   * Returns the sDMmbId
   * 
   * @return the sDMmbId
   */
    @Column(name = "SDMMBID")
    public String getSDMmbId() {
        return sDMmbId;
    }	 
     
  /**
   * Sets the sDMmbId
   *
   * @param newSDMmbId the new sDMmbId
   */

    public void  setSDMmbId(String newSDMmbId) {
        sDMmbId = newSDMmbId;
    }	  
  /**
   * Returns the sInDId
   * 
   * @return the sInDId
   */
    @Column(name = "SINDID")
    public String getSInDId() {
        return sInDId;
    }	 
     
  /**
   * Sets the sInDId
   *
   * @param newSInDId the new sInDId
   */

    public void  setSInDId(String newSInDId) {
        sInDId = newSInDId;
    }	  
  /**
   * Returns the rDMmbId
   * 
   * @return the rDMmbId
   */
    @Column(name = "RDMMBID")
    public String getRDMmbId() {
        return rDMmbId;
    }	 
     
  /**
   * Sets the rDMmbId
   *
   * @param newRDMmbId the new rDMmbId
   */

    public void  setRDMmbId(String newRDMmbId) {
        rDMmbId = newRDMmbId;
    }	  
  /**
   * Returns the rInDId
   * 
   * @return the rInDId
   */
    @Column(name = "RINDID")
    public String getRInDId() {
        return rInDId;
    }	 
     
  /**
   * Sets the rInDId
   *
   * @param newRInDId the new rInDId
   */

    public void  setRInDId(String newRInDId) {
        rInDId = newRInDId;
    }	  
  /**
   * Returns the orgnlMsgId
   * 
   * @return the orgnlMsgId
   */
    @Column(name = "ORGNLMSGID")
    public String getOrgnlMsgId() {
        return orgnlMsgId;
    }	 
     
  /**
   * Sets the orgnlMsgId
   *
   * @param newOrgnlMsgId the new orgnlMsgId
   */

    public void  setOrgnlMsgId(String newOrgnlMsgId) {
        orgnlMsgId = newOrgnlMsgId;
    }	  
  /**
   * Returns the orgnlMsgNmId
   * 
   * @return the orgnlMsgNmId
   */
    @Column(name = "ORGNLMSGNMID")
    public String getOrgnlMsgNmId() {
        return orgnlMsgNmId;
    }	 
     
  /**
   * Sets the orgnlMsgNmId
   *
   * @param newOrgnlMsgNmId the new orgnlMsgNmId
   */

    public void  setOrgnlMsgNmId(String newOrgnlMsgNmId) {
        orgnlMsgNmId = newOrgnlMsgNmId;
    }	  
  /**
   * Returns the orgnlSen
   * 
   * @return the orgnlSen
   */
    @Column(name = "ORGNLSEN")
    public String getOrgnlSen() {
        return orgnlSen;
    }	 
     
  /**
   * Sets the orgnlSen
   *
   * @param newOrgnlSen the new orgnlSen
   */

    public void  setOrgnlSen(String newOrgnlSen) {
        orgnlSen = newOrgnlSen;
    }	  
  /**
   * Returns the reTp
   * 
   * @return the reTp
   */
    @Column(name = "RETP")
    public String getReTp() {
        return reTp;
    }	 
     
  /**
   * Sets the reTp
   *
   * @param newReTp the new reTp
   */

    public void  setReTp(String newReTp) {
        reTp = newReTp;
    }	  
  /**
   * Returns the txInf
   * 
   * @return the txInf
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
    public java.util.Set<Ccms31800101TxInf> getTxInf() {
        return txInf;
    }	 
     
  /**
   * Sets the txInf
   *
   * @param newTxInf the new txInf
   */

    public void  setTxInf(java.util.Set<Ccms31800101TxInf> newTxInf) {
        txInf = newTxInf;
    }	  
    
    
}    
    
