package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Ccms92100101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_CCMS_921")
public class Ccms92100101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="certDwnLdRspn.certfctnList[0].mmbCd")
    private String mmbCd;
    
    @JaxbMapping(objPath="certDwnLdRspn.certfctnList[0].dgtlSgntr")
    private String dgtlSgntr;
    
    private Ccms92100101Hdr fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Ccms92100101Hdr getFid() {
		return fid;
	}


	public void setFid(Ccms92100101Hdr fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Ccms92100101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the mmbCd
   * 
   * @return the mmbCd
   */
    @Column(name = "MMBCD")
    public String getMmbCd() {
        return mmbCd;
    }	 
     
  /**
   * Sets the mmbCd
   *
   * @param newMmbCd the new mmbCd
   */

    public void  setMmbCd(String newMmbCd) {
        mmbCd = newMmbCd;
    }	  
  /**
   * Returns the dgtlSgntr
   * 
   * @return the dgtlSgntr
   */
    @Column(name = "DGTLSGNTR")
    public String getDgtlSgntr() {
        return dgtlSgntr;
    }	 
     
  /**
   * Sets the dgtlSgntr
   *
   * @param newDgtlSgntr the new dgtlSgntr
   */

    public void  setDgtlSgntr(String newDgtlSgntr) {
        dgtlSgntr = newDgtlSgntr;
    }	  
    
    
}    
    
