package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Ccms90700102 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_CCMS_907")
public class Ccms90700102  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="sysParamNtfctn.sysParamInf[0].chgTp")
    private String chngTp;
    
    @JaxbMapping(objPath="sysParamNtfctn.sysParamInf[0].cmonDataTp")
    private String cmonDataTp;
    
    @JaxbMapping(objPath="sysParamNtfctn.sysParamInf[0].cmonDataCd")
    private String cmonDataCd;
    
    @JaxbMapping(objPath="sysParamNtfctn.sysParamInf[0].cmonDataNm")
    private String cmonDataNm;
    
    @JaxbMapping(objPath="sysParamNtfctn.sysParamInf[0].cmonDataVal")
    private String cmonDataVal;
    
    private Ccms90700102Hdr fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Ccms90700102Hdr getFid() {
		return fid;
	}


	public void setFid(Ccms90700102Hdr fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Ccms90700102() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the chngTp
   * 
   * @return the chngTp
   */
    @Column(name = "CHNGTP")
    public String getChngTp() {
        return chngTp;
    }	 
     
  /**
   * Sets the chngTp
   *
   * @param newChngTp the new chngTp
   */

    public void  setChngTp(String newChngTp) {
        chngTp = newChngTp;
    }	  
  /**
   * Returns the cmonDataTp
   * 
   * @return the cmonDataTp
   */
    @Column(name = "CMONDATATP")
    public String getCmonDataTp() {
        return cmonDataTp;
    }	 
     
  /**
   * Sets the cmonDataTp
   *
   * @param newCmonDataTp the new cmonDataTp
   */

    public void  setCmonDataTp(String newCmonDataTp) {
        cmonDataTp = newCmonDataTp;
    }	  
  /**
   * Returns the cmonDataCd
   * 
   * @return the cmonDataCd
   */
    @Column(name = "CMONDATACD")
    public String getCmonDataCd() {
        return cmonDataCd;
    }	 
     
  /**
   * Sets the cmonDataCd
   *
   * @param newCmonDataCd the new cmonDataCd
   */

    public void  setCmonDataCd(String newCmonDataCd) {
        cmonDataCd = newCmonDataCd;
    }	  
  /**
   * Returns the cmonDataNm
   * 
   * @return the cmonDataNm
   */
    @Column(name = "CMONDATANM")
    public String getCmonDataNm() {
        return cmonDataNm;
    }	 
     
  /**
   * Sets the cmonDataNm
   *
   * @param newCmonDataNm the new cmonDataNm
   */

    public void  setCmonDataNm(String newCmonDataNm) {
        cmonDataNm = newCmonDataNm;
    }	  
  /**
   * Returns the cmonDataVal
   * 
   * @return the cmonDataVal
   */
    @Column(name = "CMONDATAVAL")
    public String getCmonDataVal() {
        return cmonDataVal;
    }	 
     
  /**
   * Sets the cmonDataVal
   *
   * @param newCmonDataVal the new cmonDataVal
   */

    public void  setCmonDataVal(String newCmonDataVal) {
        cmonDataVal = newCmonDataVal;
    }	  
    
    
}    
    
