package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.SequenceGenerator;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ccms80100102 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_CCMS_801")
public class Ccms80100102  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="sysStsNtfctn.grpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="sysStsNtfctn.grpHdr.creDtTm")
    private String creDtTm;
    
    @JaxbMapping(objPath="sysStsNtfctn.grpHdr.instgPty.instgDrctPty")
    private String instgDrctPty;
    
    @JaxbMapping(objPath="sysStsNtfctn.grpHdr.instgPty.instgPty")
    private String instgIndrctPty;
    
    @JaxbMapping(objPath="sysStsNtfctn.grpHdr.instdPty.instdDrctPty")
    private String instdDrctPty;
    
    @JaxbMapping(objPath="sysStsNtfctn.grpHdr.instdPty.instdPty")
    private String instdIndrctPty;
    
    @JaxbMapping(objPath="sysStsNtfctn.grpHdr.sysCd")
    private String sysCd;
    
    @JaxbMapping(objPath="sysStsNtfctn.grpHdr.rmk")
    private String rmk;
    
    @JaxbMapping(objPath="sysStsNtfctn.sysStsInf.orgnlSysDt")
    private String orgnlSysDt;
    
    @JaxbMapping(objPath="sysStsNtfctn.sysStsInf.orgnlSysSts")
    private String orgnlSysSts;
    
    @JaxbMapping(objPath="sysStsNtfctn.sysStsInf.curSysDt")
    private String curSysDt;
    
    @JaxbMapping(objPath="sysStsNtfctn.sysStsInf.curSysSts")
    private String curSysSts;
    
    @JaxbMapping(objPath="sysStsNtfctn.sysStsInf.hldayFlg")
    private String hldayFlg;
    
    @JaxbMapping(objPath="sysStsNtfctn.sysStsInf.nxtSysDt")
    private String nxtSysDt;
    
    @JaxbMapping(objPath="sysStsNtfctn.sysStsInf.bkChngNb")
    private String bkChngNb;
    
    @JaxbMapping(objPath="sysStsNtfctn.sysStsInf.baseDataChngNb")
    private String baseDataChngNb;
    
    @JaxbMapping(objPath="sysStsNtfctn.sysStsInf.cisChngNb")
    private String cISChngNb;
    
    @JaxbMapping(objPath="sysStsNtfctn.sysStsInf.paramChngNb")
    private String paramChngNb;
    
    
	
    /** default constructor */
    public Ccms80100102() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
    @Id
	  @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	  @SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	  @GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public String getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(String newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the instgDrctPty
   * 
   * @return the instgDrctPty
   */
    @Column(name = "INSTGDRCTPTY")
    public String getInstgDrctPty() {
        return instgDrctPty;
    }	 
     
  /**
   * Sets the instgDrctPty
   *
   * @param newInstgDrctPty the new instgDrctPty
   */

    public void  setInstgDrctPty(String newInstgDrctPty) {
        instgDrctPty = newInstgDrctPty;
    }	  
  /**
   * Returns the instgIndrctPty
   * 
   * @return the instgIndrctPty
   */
    @Column(name = "INSTGINDRCTPTY")
    public String getInstgIndrctPty() {
        return instgIndrctPty;
    }	 
     
  /**
   * Sets the instgIndrctPty
   *
   * @param newInstgIndrctPty the new instgIndrctPty
   */

    public void  setInstgIndrctPty(String newInstgIndrctPty) {
        instgIndrctPty = newInstgIndrctPty;
    }	  
  /**
   * Returns the instdDrctPty
   * 
   * @return the instdDrctPty
   */
    @Column(name = "INSTDDRCTPTY")
    public String getInstdDrctPty() {
        return instdDrctPty;
    }	 
     
  /**
   * Sets the instdDrctPty
   *
   * @param newInstdDrctPty the new instdDrctPty
   */

    public void  setInstdDrctPty(String newInstdDrctPty) {
        instdDrctPty = newInstdDrctPty;
    }	  
  /**
   * Returns the instdIndrctPty
   * 
   * @return the instdIndrctPty
   */
    @Column(name = "INSTDINDRCTPTY")
    public String getInstdIndrctPty() {
        return instdIndrctPty;
    }	 
     
  /**
   * Sets the instdIndrctPty
   *
   * @param newInstdIndrctPty the new instdIndrctPty
   */

    public void  setInstdIndrctPty(String newInstdIndrctPty) {
        instdIndrctPty = newInstdIndrctPty;
    }	  
  /**
   * Returns the sysCd
   * 
   * @return the sysCd
   */
    @Column(name = "SYSCD")
    public String getSysCd() {
        return sysCd;
    }	 
     
  /**
   * Sets the sysCd
   *
   * @param newSysCd the new sysCd
   */

    public void  setSysCd(String newSysCd) {
        sysCd = newSysCd;
    }	  
  /**
   * Returns the rmk
   * 
   * @return the rmk
   */
    @Column(name = "RMK")
    public String getRmk() {
        return rmk;
    }	 
     
  /**
   * Sets the rmk
   *
   * @param newRmk the new rmk
   */

    public void  setRmk(String newRmk) {
        rmk = newRmk;
    }	  
  /**
   * Returns the orgnlSysDt
   * 
   * @return the orgnlSysDt
   */
    @Column(name = "ORGNLSYSDT")
    public String getOrgnlSysDt() {
        return orgnlSysDt;
    }	 
     
  /**
   * Sets the orgnlSysDt
   *
   * @param newOrgnlSysDt the new orgnlSysDt
   */

    public void  setOrgnlSysDt(String newOrgnlSysDt) {
        orgnlSysDt = newOrgnlSysDt;
    }	  
  /**
   * Returns the orgnlSysSts
   * 
   * @return the orgnlSysSts
   */
    @Column(name = "ORGNLSYSSTS")
    public String getOrgnlSysSts() {
        return orgnlSysSts;
    }	 
     
  /**
   * Sets the orgnlSysSts
   *
   * @param newOrgnlSysSts the new orgnlSysSts
   */

    public void  setOrgnlSysSts(String newOrgnlSysSts) {
        orgnlSysSts = newOrgnlSysSts;
    }	  
  /**
   * Returns the curSysDt
   * 
   * @return the curSysDt
   */
    @Column(name = "CURSYSDT")
    public String getCurSysDt() {
        return curSysDt;
    }	 
     
  /**
   * Sets the curSysDt
   *
   * @param newCurSysDt the new curSysDt
   */

    public void  setCurSysDt(String newCurSysDt) {
        curSysDt = newCurSysDt;
    }	  
  /**
   * Returns the curSysSts
   * 
   * @return the curSysSts
   */
    @Column(name = "CURSYSSTS")
    public String getCurSysSts() {
        return curSysSts;
    }	 
     
  /**
   * Sets the curSysSts
   *
   * @param newCurSysSts the new curSysSts
   */

    public void  setCurSysSts(String newCurSysSts) {
        curSysSts = newCurSysSts;
    }	  
  /**
   * Returns the hldayFlg
   * 
   * @return the hldayFlg
   */
    @Column(name = "HLDAYFLG")
    public String getHldayFlg() {
        return hldayFlg;
    }	 
     
  /**
   * Sets the hldayFlg
   *
   * @param newHldayFlg the new hldayFlg
   */

    public void  setHldayFlg(String newHldayFlg) {
        hldayFlg = newHldayFlg;
    }	  
  /**
   * Returns the nxtSysDt
   * 
   * @return the nxtSysDt
   */
    @Column(name = "NXTSYSDT")
    public String getNxtSysDt() {
        return nxtSysDt;
    }	 
     
  /**
   * Sets the nxtSysDt
   *
   * @param newNxtSysDt the new nxtSysDt
   */

    public void  setNxtSysDt(String newNxtSysDt) {
        nxtSysDt = newNxtSysDt;
    }	  
  /**
   * Returns the bkChngNb
   * 
   * @return the bkChngNb
   */
    @Column(name = "BKCHNGNB")
    public String getBkChngNb() {
        return bkChngNb;
    }	 
     
  /**
   * Sets the bkChngNb
   *
   * @param newBkChngNb the new bkChngNb
   */

    public void  setBkChngNb(String newBkChngNb) {
        bkChngNb = newBkChngNb;
    }	  
  /**
   * Returns the baseDataChngNb
   * 
   * @return the baseDataChngNb
   */
    @Column(name = "BASEDATACHNGNB")
    public String getBaseDataChngNb() {
        return baseDataChngNb;
    }	 
     
  /**
   * Sets the baseDataChngNb
   *
   * @param newBaseDataChngNb the new baseDataChngNb
   */

    public void  setBaseDataChngNb(String newBaseDataChngNb) {
        baseDataChngNb = newBaseDataChngNb;
    }	  
  /**
   * Returns the cISChngNb
   * 
   * @return the cISChngNb
   */
    @Column(name = "CISCHNGNB")
    public String getCISChngNb() {
        return cISChngNb;
    }	 
     
  /**
   * Sets the cISChngNb
   *
   * @param newCISChngNb the new cISChngNb
   */

    public void  setCISChngNb(String newCISChngNb) {
        cISChngNb = newCISChngNb;
    }	  
  /**
   * Returns the paramChngNb
   * 
   * @return the paramChngNb
   */
    @Column(name = "PARAMCHNGNB")
    public String getParamChngNb() {
        return paramChngNb;
    }	 
     
  /**
   * Sets the paramChngNb
   *
   * @param newParamChngNb the new paramChngNb
   */

    public void  setParamChngNb(String newParamChngNb) {
        paramChngNb = newParamChngNb;
    }	  
    
    
}    
    
