package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Ccms80300102 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_CCMS_803")
public class Ccms80300102  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="trblNtfctn.ndInf.ptyId[0]")
    private String ptyId;
    
    private Ccms80300102Hdr fid;


	/** default constructor */
    public Ccms80300102() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the ptyId
   * 
   * @return the ptyId
   */
    @Column(name = "PTYID")
    public String getPtyId() {
        return ptyId;
    }	 
     
  /**
   * Sets the ptyId
   *
   * @param newPtyId the new ptyId
   */

    public void  setPtyId(String newPtyId) {
        ptyId = newPtyId;
    }	  
    
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Ccms80300102Hdr getFid() {
		return fid;
	}


	public void setFid(Ccms80300102Hdr fid) {
		this.fid = fid;
	}
}    
    
