package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Ccms92600101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_CCMS_926")
public class Ccms92600101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="txAmtUpperLmt.txAmtUpperLmtInf[0].chngTp")
    private String chngTp;
    
    @JaxbMapping(objPath="txAmtUpperLmt.txAmtUpperLmtInf[0].mt")
    private String mT;
    
    @JaxbMapping(objPath="txAmtUpperLmt.txAmtUpperLmtInf[0].txTp")
    private String txTp;
    
    @JaxbMapping(objPath="txAmtUpperLmt.txAmtUpperLmtInf[0].sndrBk")
    private String sndrBk;
    
    @JaxbMapping(objPath="txAmtUpperLmt.txAmtUpperLmtInf[0].rcvBk")
    private String rcvBk;
    
    @JaxbMapping(objPath="txAmtUpperLmt.txAmtUpperLmtInf[0].chckLvl")
    private String chckLvl;
    
    @JaxbMapping(objPath="txAmtUpperLmt.txAmtUpperLmtInf[0].amtUpperLmt.value")
    private Double amtUpperLmt;
    
    private Ccms92600101Hdr fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Ccms92600101Hdr getFid() {
		return fid;
	}


	public void setFid(Ccms92600101Hdr fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Ccms92600101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the chngTp
   * 
   * @return the chngTp
   */
    @Column(name = "CHNGTP")
    public String getChngTp() {
        return chngTp;
    }	 
     
  /**
   * Sets the chngTp
   *
   * @param newChngTp the new chngTp
   */

    public void  setChngTp(String newChngTp) {
        chngTp = newChngTp;
    }	  
  /**
   * Returns the mT
   * 
   * @return the mT
   */
    @Column(name = "MT")
    public String getMT() {
        return mT;
    }	 
     
  /**
   * Sets the mT
   *
   * @param newMT the new mT
   */

    public void  setMT(String newMT) {
        mT = newMT;
    }	  
  /**
   * Returns the txTp
   * 
   * @return the txTp
   */
    @Column(name = "TXTP")
    public String getTxTp() {
        return txTp;
    }	 
     
  /**
   * Sets the txTp
   *
   * @param newTxTp the new txTp
   */

    public void  setTxTp(String newTxTp) {
        txTp = newTxTp;
    }	  
  /**
   * Returns the sndrBk
   * 
   * @return the sndrBk
   */
    @Column(name = "SNDRBK")
    public String getSndrBk() {
        return sndrBk;
    }	 
     
  /**
   * Sets the sndrBk
   *
   * @param newSndrBk the new sndrBk
   */

    public void  setSndrBk(String newSndrBk) {
        sndrBk = newSndrBk;
    }	  
  /**
   * Returns the rcvBk
   * 
   * @return the rcvBk
   */
    @Column(name = "RCVBK")
    public String getRcvBk() {
        return rcvBk;
    }	 
     
  /**
   * Sets the rcvBk
   *
   * @param newRcvBk the new rcvBk
   */

    public void  setRcvBk(String newRcvBk) {
        rcvBk = newRcvBk;
    }	  
  /**
   * Returns the chckLvl
   * 
   * @return the chckLvl
   */
    @Column(name = "CHCKLVL")
    public String getChckLvl() {
        return chckLvl;
    }	 
     
  /**
   * Sets the chckLvl
   *
   * @param newChckLvl the new chckLvl
   */

    public void  setChckLvl(String newChckLvl) {
        chckLvl = newChckLvl;
    }	  
  /**
   * Returns the amtUpperLmt
   * 
   * @return the amtUpperLmt
   */
    @Column(name = "AMTUPPERLMT")
    public Double getAmtUpperLmt() {
        return amtUpperLmt;
    }	 
     
  /**
   * Sets the amtUpperLmt
   *
   * @param newAmtUpperLmt the new amtUpperLmt
   */

    public void  setAmtUpperLmt(Double newAmtUpperLmt) {
        amtUpperLmt = newAmtUpperLmt;
    }	  
    
    
}    
    
