package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Ccms80900102 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_CCMS_809")
public class Ccms80900102  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="stopgNtfctn.ndInf.ndCd[0]")
    private String ndCd;

	@JaxbMapping(objPath="stopgNtfctn.ndInf.ptyId[0]")
    private String ptyId;
    
    private Ccms80900102Hdr fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Ccms80900102Hdr getFid() {
		return fid;
	}


	public void setFid(Ccms80900102Hdr fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Ccms80900102() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	
    
    /**
     * Returns the ndCd
     * 
     * @return the ndCd
     */
      @Column(name = "NDCD")
    public String getNdCd() {
		return ndCd;
	}

      /**
       * Sets the ndCd
       *
       * @param newNdCd the new ndCd
       */
	public void setNdCd(String newNdCd) {
		this.ndCd = newNdCd;
	}
	
  /**
   * Returns the ptyId
   * 
   * @return the ptyId
   */
    @Column(name = "PTYID")
    public String getPtyId() {
        return ptyId;
    }	 
     
  /**
   * Sets the ptyId
   *
   * @param newPtyId the new ptyId
   */

    public void  setPtyId(String newPtyId) {
        ptyId = newPtyId;
    }	  
    
    
}    
    
