package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Hvps71100101ChckPmtInfDtls generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_HVPS_711_EXT_BIZ")
public class Hvps71100101ChckPmtInfDtls  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="summryFile.summryFileInf.chckPmtInfDtls[0].txTpCd")
    private String bizTpCd;
    
    @JaxbMapping(objPath="summryFile.summryFileInf.chckPmtInfDtls[0].sndgNbOfTxs")
    private String bizSndgNbOfTxs;
    
    @JaxbMapping(objPath="summryFile.summryFileInf.chckPmtInfDtls[0].sndgCtrlSum.value")
    private Double bizSndgCtrlSum;
    
    @JaxbMapping(objPath="summryFile.summryFileInf.chckPmtInfDtls[0].rcvgNbOfTxs")
    private String bizRcvgNbOfTxs;
    
    @JaxbMapping(objPath="summryFile.summryFileInf.chckPmtInfDtls[0].rcvgCtrlSum.value")
    private Double bizRcvgCtrlSum;
    
    @JaxbMapping(objPath="summryFile.summryFileInf.chckPmtInfDtls[0].prcSts")
    private String bizPrcSts;
    
    private Hvps71100101 fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Hvps71100101 getFid() {
		return fid;
	}


	public void setFid(Hvps71100101 fid) {
		this.fid = fid;
	}
	
    /** default constructor */
    public Hvps71100101ChckPmtInfDtls() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the bizTpCd
   * 
   * @return the bizTpCd
   */
    @Column(name = "BIZTPCD")
    public String getBizTpCd() {
        return bizTpCd;
    }	 
     
  /**
   * Sets the bizTpCd
   *
   * @param newBizTpCd the new bizTpCd
   */

    public void  setBizTpCd(String newBizTpCd) {
        bizTpCd = newBizTpCd;
    }	  
  /**
   * Returns the bizSndgNbOfTxs
   * 
   * @return the bizSndgNbOfTxs
   */
    @Column(name = "BIZSNDGNBOFTXS")
    public String getBizSndgNbOfTxs() {
        return bizSndgNbOfTxs;
    }	 
     
  /**
   * Sets the bizSndgNbOfTxs
   *
   * @param newBizSndgNbOfTxs the new bizSndgNbOfTxs
   */

    public void  setBizSndgNbOfTxs(String newBizSndgNbOfTxs) {
        bizSndgNbOfTxs = newBizSndgNbOfTxs;
    }	  
  /**
   * Returns the bizSndgCtrlSum
   * 
   * @return the bizSndgCtrlSum
   */
    @Column(name = "BIZSNDGCTRLSUM")
    public Double getBizSndgCtrlSum() {
        return bizSndgCtrlSum;
    }	 
     
  /**
   * Sets the bizSndgCtrlSum
   *
   * @param newBizSndgCtrlSum the new bizSndgCtrlSum
   */

    public void  setBizSndgCtrlSum(Double newBizSndgCtrlSum) {
        bizSndgCtrlSum = newBizSndgCtrlSum;
    }	  
  /**
   * Returns the bizRcvgNbOfTxs
   * 
   * @return the bizRcvgNbOfTxs
   */
    @Column(name = "BIZRCVGNBOFTXS")
    public String getBizRcvgNbOfTxs() {
        return bizRcvgNbOfTxs;
    }	 
     
  /**
   * Sets the bizRcvgNbOfTxs
   *
   * @param newBizRcvgNbOfTxs the new bizRcvgNbOfTxs
   */

    public void  setBizRcvgNbOfTxs(String newBizRcvgNbOfTxs) {
        bizRcvgNbOfTxs = newBizRcvgNbOfTxs;
    }	  
  /**
   * Returns the bizRcvgCtrlSum
   * 
   * @return the bizRcvgCtrlSum
   */
    @Column(name = "BIZRCVGCTRLSUM")
    public Double getBizRcvgCtrlSum() {
        return bizRcvgCtrlSum;
    }	 
     
  /**
   * Sets the bizRcvgCtrlSum
   *
   * @param newBizRcvgCtrlSum the new bizRcvgCtrlSum
   */

    public void  setBizRcvgCtrlSum(Double newBizRcvgCtrlSum) {
        bizRcvgCtrlSum = newBizRcvgCtrlSum;
    }	  
  /**
   * Returns the bizPrcSts
   * 
   * @return the bizPrcSts
   */
    @Column(name = "BIZPRCSTS")
    public String getBizPrcSts() {
        return bizPrcSts;
    }	 
     
  /**
   * Sets the bizPrcSts
   *
   * @param newBizPrcSts the new bizPrcSts
   */

    public void  setBizPrcSts(String newBizPrcSts) {
        bizPrcSts = newBizPrcSts;
    }	  
    
    
}    
    
