package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Hvps11200101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_HVPS_112_HDR")
public class Hvps11200101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="finInstnCdtTrf.grpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="finInstnCdtTrf.grpHdr.creDtTm")
    private Date creDtTm;
    
    @JaxbMapping(objPath="finInstnCdtTrf.grpHdr.nbOfTxs")
    private String nbOfTxs;
    
    @JaxbMapping(objPath="finInstnCdtTrf.grpHdr.sttlmInf.sttlmMtd")
    private String sttlmMtd;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.pmtId")
    private String pmtId;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.pmtId.endToEndId")
    private String endToEndId;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.pmtId.txId")
    private String txId;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.pmtTpInf.svcLvl.prtry")
    private String bizTpCd;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.intrBkSttlmAmt.value")
    private Double intrBkSttlmAmt;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.sttlmPrty")
    private String sttlmPrty;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.dbtr.finInstnId.clrSysMmbId.mmbId")
    private String dbtrClrSysMmbId;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.dbtr.finInstnId.nm")
    private String dbtrNm;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.dbtr.finInstnId.pstlAdr.adrLine[0]")
    private String pyAdrLine;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.dbtr.brnchId")
    private String dbtrBrnchId;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.dbtr.brnchId.id")
    private String dbtrAgtBrnchId;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.dbtrAcct.id.othr.id")
    private String dbtrAcctId;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.dbtrAcct.id.othr.issr")
    private String dbtrAcctIssr;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.cdtr.finInstnId.clrSysMmbId.mmbId")
    private String cdtrClrSysMmbId;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.cdtr.finInstnId.nm")
    private String cdtrNm;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.cdtr.finInstnId.pstlAdr.adrLine[0]")
    private String recAdrLine;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.cdtr.brnchId")
    private String cdtrBrnchId;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.cdtr.brnchId.id")
    private String cdtrAgtBrnchId;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.cdtrAcct.id.othr.id")
    private String cdtrAcctId;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.cdtrAcct.id.othr.issr")
    private String cdtrAcctIssr;
    
    @JaxbMapping(objPath="finInstnCdtTrf.cdtTrfTxInf.rmtInf[0]")
    private java.util.Set<Hvps11200101RmtInf> rmtInf;
    
    
	
    /** default constructor */
    public Hvps11200101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public Date getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(Date newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the nbOfTxs
   * 
   * @return the nbOfTxs
   */
    @Column(name = "NBOFTXS")
    public String getNbOfTxs() {
        return nbOfTxs;
    }	 
     
  /**
   * Sets the nbOfTxs
   *
   * @param newNbOfTxs the new nbOfTxs
   */

    public void  setNbOfTxs(String newNbOfTxs) {
        nbOfTxs = newNbOfTxs;
    }	  
  /**
   * Returns the sttlmMtd
   * 
   * @return the sttlmMtd
   */
    @Column(name = "STTLMMTD")
    public String getSttlmMtd() {
        return sttlmMtd;
    }	 
     
  /**
   * Sets the sttlmMtd
   *
   * @param newSttlmMtd the new sttlmMtd
   */

    public void  setSttlmMtd(String newSttlmMtd) {
        sttlmMtd = newSttlmMtd;
    }	  
  /**
   * Returns the pmtId
   * 
   * @return the pmtId
   */
    @Column(name = "PMTID")
    public String getPmtId() {
        return pmtId;
    }	 
     
  /**
   * Sets the pmtId
   *
   * @param newPmtId the new pmtId
   */

    public void  setPmtId(String newPmtId) {
        pmtId = newPmtId;
    }	  
  /**
   * Returns the endToEndId
   * 
   * @return the endToEndId
   */
    @Column(name = "ENDTOENDID")
    public String getEndToEndId() {
        return endToEndId;
    }	 
     
  /**
   * Sets the endToEndId
   *
   * @param newEndToEndId the new endToEndId
   */

    public void  setEndToEndId(String newEndToEndId) {
        endToEndId = newEndToEndId;
    }	  
  /**
   * Returns the txId
   * 
   * @return the txId
   */
    @Column(name = "TXID")
    public String getTxId() {
        return txId;
    }	 
     
  /**
   * Sets the txId
   *
   * @param newTxId the new txId
   */

    public void  setTxId(String newTxId) {
        txId = newTxId;
    }	  
  /**
   * Returns the bizTpCd
   * 
   * @return the bizTpCd
   */
    @Column(name = "BIZTPCD")
    public String getBizTpCd() {
        return bizTpCd;
    }	 
     
  /**
   * Sets the bizTpCd
   *
   * @param newBizTpCd the new bizTpCd
   */

    public void  setBizTpCd(String newBizTpCd) {
        bizTpCd = newBizTpCd;
    }	  
  /**
   * Returns the intrBkSttlmAmt
   * 
   * @return the intrBkSttlmAmt
   */
    @Column(name = "INTRBKSTTLMAMT")
    public Double getIntrBkSttlmAmt() {
        return intrBkSttlmAmt;
    }	 
     
  /**
   * Sets the intrBkSttlmAmt
   *
   * @param newIntrBkSttlmAmt the new intrBkSttlmAmt
   */

    public void  setIntrBkSttlmAmt(Double newIntrBkSttlmAmt) {
        intrBkSttlmAmt = newIntrBkSttlmAmt;
    }	  
  /**
   * Returns the sttlmPrty
   * 
   * @return the sttlmPrty
   */
    @Column(name = "STTLMPRTY")
    public String getSttlmPrty() {
        return sttlmPrty;
    }	 
     
  /**
   * Sets the sttlmPrty
   *
   * @param newSttlmPrty the new sttlmPrty
   */

    public void  setSttlmPrty(String newSttlmPrty) {
        sttlmPrty = newSttlmPrty;
    }	  
  /**
   * Returns the dbtrClrSysMmbId
   * 
   * @return the dbtrClrSysMmbId
   */
    @Column(name = "DBTRCLRSYSMMBID")
    public String getDbtrClrSysMmbId() {
        return dbtrClrSysMmbId;
    }	 
     
  /**
   * Sets the dbtrClrSysMmbId
   *
   * @param newDbtrClrSysMmbId the new dbtrClrSysMmbId
   */

    public void  setDbtrClrSysMmbId(String newDbtrClrSysMmbId) {
        dbtrClrSysMmbId = newDbtrClrSysMmbId;
    }	  
  /**
   * Returns the dbtrNm
   * 
   * @return the dbtrNm
   */
    @Column(name = "DBTRNM")
    public String getDbtrNm() {
        return dbtrNm;
    }	 
     
  /**
   * Sets the dbtrNm
   *
   * @param newDbtrNm the new dbtrNm
   */

    public void  setDbtrNm(String newDbtrNm) {
        dbtrNm = newDbtrNm;
    }	  
  /**
   * Returns the pyAdrLine
   * 
   * @return the pyAdrLine
   */
    @Column(name = "PYADRLINE")
    public String getPyAdrLine() {
        return pyAdrLine;
    }	 
     
  /**
   * Sets the pyAdrLine
   *
   * @param newPyAdrLine the new pyAdrLine
   */

    public void  setPyAdrLine(String newPyAdrLine) {
        pyAdrLine = newPyAdrLine;
    }	  
  /**
   * Returns the dbtrBrnchId
   * 
   * @return the dbtrBrnchId
   */
    @Column(name = "DBTRBRNCHID")
    public String getDbtrBrnchId() {
        return dbtrBrnchId;
    }	 
     
  /**
   * Sets the dbtrBrnchId
   *
   * @param newDbtrBrnchId the new dbtrBrnchId
   */

    public void  setDbtrBrnchId(String newDbtrBrnchId) {
        dbtrBrnchId = newDbtrBrnchId;
    }	  
  /**
   * Returns the dbtrAgtBrnchId
   * 
   * @return the dbtrAgtBrnchId
   */
    @Column(name = "DBTRAGTBRNCHID")
    public String getDbtrAgtBrnchId() {
        return dbtrAgtBrnchId;
    }	 
     
  /**
   * Sets the dbtrAgtBrnchId
   *
   * @param newDbtrAgtBrnchId the new dbtrAgtBrnchId
   */

    public void  setDbtrAgtBrnchId(String newDbtrAgtBrnchId) {
        dbtrAgtBrnchId = newDbtrAgtBrnchId;
    }	  
  /**
   * Returns the dbtrAcctId
   * 
   * @return the dbtrAcctId
   */
    @Column(name = "DBTRACCTID")
    public String getDbtrAcctId() {
        return dbtrAcctId;
    }	 
     
  /**
   * Sets the dbtrAcctId
   *
   * @param newDbtrAcctId the new dbtrAcctId
   */

    public void  setDbtrAcctId(String newDbtrAcctId) {
        dbtrAcctId = newDbtrAcctId;
    }	  
  /**
   * Returns the dbtrAcctIssr
   * 
   * @return the dbtrAcctIssr
   */
    @Column(name = "DBTRACCTISSR")
    public String getDbtrAcctIssr() {
        return dbtrAcctIssr;
    }	 
     
  /**
   * Sets the dbtrAcctIssr
   *
   * @param newDbtrAcctIssr the new dbtrAcctIssr
   */

    public void  setDbtrAcctIssr(String newDbtrAcctIssr) {
        dbtrAcctIssr = newDbtrAcctIssr;
    }	  
  /**
   * Returns the cdtrClrSysMmbId
   * 
   * @return the cdtrClrSysMmbId
   */
    @Column(name = "CDTRCLRSYSMMBID")
    public String getCdtrClrSysMmbId() {
        return cdtrClrSysMmbId;
    }	 
     
  /**
   * Sets the cdtrClrSysMmbId
   *
   * @param newCdtrClrSysMmbId the new cdtrClrSysMmbId
   */

    public void  setCdtrClrSysMmbId(String newCdtrClrSysMmbId) {
        cdtrClrSysMmbId = newCdtrClrSysMmbId;
    }	  
  /**
   * Returns the cdtrNm
   * 
   * @return the cdtrNm
   */
    @Column(name = "CDTRNM")
    public String getCdtrNm() {
        return cdtrNm;
    }	 
     
  /**
   * Sets the cdtrNm
   *
   * @param newCdtrNm the new cdtrNm
   */

    public void  setCdtrNm(String newCdtrNm) {
        cdtrNm = newCdtrNm;
    }	  
  /**
   * Returns the recAdrLine
   * 
   * @return the recAdrLine
   */
    @Column(name = "RECADRLINE")
    public String getRecAdrLine() {
        return recAdrLine;
    }	 
     
  /**
   * Sets the recAdrLine
   *
   * @param newRecAdrLine the new recAdrLine
   */

    public void  setRecAdrLine(String newRecAdrLine) {
        recAdrLine = newRecAdrLine;
    }	  
  /**
   * Returns the cdtrBrnchId
   * 
   * @return the cdtrBrnchId
   */
    @Column(name = "CDTRBRNCHID")
    public String getCdtrBrnchId() {
        return cdtrBrnchId;
    }	 
     
  /**
   * Sets the cdtrBrnchId
   *
   * @param newCdtrBrnchId the new cdtrBrnchId
   */

    public void  setCdtrBrnchId(String newCdtrBrnchId) {
        cdtrBrnchId = newCdtrBrnchId;
    }	  
  /**
   * Returns the cdtrAgtBrnchId
   * 
   * @return the cdtrAgtBrnchId
   */
    @Column(name = "CDTRAGTBRNCHID")
    public String getCdtrAgtBrnchId() {
        return cdtrAgtBrnchId;
    }	 
     
  /**
   * Sets the cdtrAgtBrnchId
   *
   * @param newCdtrAgtBrnchId the new cdtrAgtBrnchId
   */

    public void  setCdtrAgtBrnchId(String newCdtrAgtBrnchId) {
        cdtrAgtBrnchId = newCdtrAgtBrnchId;
    }	  
  /**
   * Returns the cdtrAcctId
   * 
   * @return the cdtrAcctId
   */
    @Column(name = "CDTRACCTID")
    public String getCdtrAcctId() {
        return cdtrAcctId;
    }	 
     
  /**
   * Sets the cdtrAcctId
   *
   * @param newCdtrAcctId the new cdtrAcctId
   */

    public void  setCdtrAcctId(String newCdtrAcctId) {
        cdtrAcctId = newCdtrAcctId;
    }	  
  /**
   * Returns the cdtrAcctIssr
   * 
   * @return the cdtrAcctIssr
   */
    @Column(name = "CDTRACCTISSR")
    public String getCdtrAcctIssr() {
        return cdtrAcctIssr;
    }	 
     
  /**
   * Sets the cdtrAcctIssr
   *
   * @param newCdtrAcctIssr the new cdtrAcctIssr
   */

    public void  setCdtrAcctIssr(String newCdtrAcctIssr) {
        cdtrAcctIssr = newCdtrAcctIssr;
    }	  
  /**
   * Returns the rmtInf
   * 
   * @return the rmtInf
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
    public java.util.Set<Hvps11200101RmtInf> getRmtInf() {
        return rmtInf;
    }	 
     
  /**
   * Sets the rmtInf
   *
   * @param newRmtInf the new rmtInf
   */

    public void  setRmtInf(java.util.Set<Hvps11200101RmtInf> newRmtInf) {
        rmtInf = newRmtInf;
    }	  
    
    
}    
    
