package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Nets61800101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_NETS_618")
public class Nets61800101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="bepsNetgRspn.bepsNetgRspnInf.txList[0].netgRnd")
    private String netgRnd;
    
    @JaxbMapping(objPath="bepsNetgRspn.bepsNetgRspnInf.txList[0].netgTp")
    private String netgTp;
    
    @JaxbMapping(objPath="bepsNetgRspn.bepsNetgRspnInf.txList[0].mmbId")
    private String mmbId;
    
    @JaxbMapping(objPath="bepsNetgRspn.bepsNetgRspnInf.txList[0].dbtCdtId")
    private String dbtCdtId;
    
    @JaxbMapping(objPath="bepsNetgRspn.bepsNetgRspnInf.txList[0].amt.value")
    private Double amt;
    
    @JaxbMapping(objPath="bepsNetgRspn.bepsNetgRspnInf.txList[0].rspnSts")
    private String rspnSts;
    
    @JaxbMapping(objPath="bepsNetgRspn.bepsNetgRspnInf.txList[0].sttlmDt")
    private Date sttlmDt;
    
    private Nets61800101Hdr fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Nets61800101Hdr getFid() {
		return fid;
	}


	public void setFid(Nets61800101Hdr fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Nets61800101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the netgRnd
   * 
   * @return the netgRnd
   */
    @Column(name = "NETGRND")
    public String getNetgRnd() {
        return netgRnd;
    }	 
     
  /**
   * Sets the netgRnd
   *
   * @param newNetgRnd the new netgRnd
   */

    public void  setNetgRnd(String newNetgRnd) {
        netgRnd = newNetgRnd;
    }	  
  /**
   * Returns the netgTp
   * 
   * @return the netgTp
   */
    @Column(name = "NETGTP")
    public String getNetgTp() {
        return netgTp;
    }	 
     
  /**
   * Sets the netgTp
   *
   * @param newNetgTp the new netgTp
   */

    public void  setNetgTp(String newNetgTp) {
        netgTp = newNetgTp;
    }	  
  /**
   * Returns the mmbId
   * 
   * @return the mmbId
   */
    @Column(name = "MMBID")
    public String getMmbId() {
        return mmbId;
    }	 
     
  /**
   * Sets the mmbId
   *
   * @param newMmbId the new mmbId
   */

    public void  setMmbId(String newMmbId) {
        mmbId = newMmbId;
    }	  
  /**
   * Returns the dbtCdtId
   * 
   * @return the dbtCdtId
   */
    @Column(name = "DBTCDTID")
    public String getDbtCdtId() {
        return dbtCdtId;
    }	 
     
  /**
   * Sets the dbtCdtId
   *
   * @param newDbtCdtId the new dbtCdtId
   */

    public void  setDbtCdtId(String newDbtCdtId) {
        dbtCdtId = newDbtCdtId;
    }	  
  /**
   * Returns the amt
   * 
   * @return the amt
   */
    @Column(name = "AMT")
    public Double getAmt() {
        return amt;
    }	 
     
  /**
   * Sets the amt
   *
   * @param newAmt the new amt
   */

    public void  setAmt(Double newAmt) {
        amt = newAmt;
    }	  
  /**
   * Returns the rspnSts
   * 
   * @return the rspnSts
   */
    @Column(name = "RSPNSTS")
    public String getRspnSts() {
        return rspnSts;
    }	 
     
  /**
   * Sets the rspnSts
   *
   * @param newRspnSts the new rspnSts
   */

    public void  setRspnSts(String newRspnSts) {
        rspnSts = newRspnSts;
    }	  
  /**
   * Returns the sttlmDt
   * 
   * @return the sttlmDt
   */
    @Column(name = "STTLMDT")
    public Date getSttlmDt() {
        return sttlmDt;
    }	 
     
  /**
   * Sets the sttlmDt
   *
   * @param newSttlmDt the new sttlmDt
   */

    public void  setSttlmDt(Date newSttlmDt) {
        sttlmDt = newSttlmDt;
    }	  
    
    
}    
    
