package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Nets35600101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_NETS_356")
public class Nets35600101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="netDbtLmtMgmtNtfctn.ntfctnCntt.forceDwnErr.dstrbtnList[0].mmbId")
    private String fdMmbId;
    
    @JaxbMapping(objPath="netDbtLmtMgmtNtfctn.ntfctnCntt.forceDwnErr.dstrbtnList[0].dstrbtnAmt.value")
    private Double fdDstrbtnAmt;
    
    private Nets35600101Hdr fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Nets35600101Hdr getFid() {
		return fid;
	}


	public void setFid(Nets35600101Hdr fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Nets35600101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the fdMmbId
   * 
   * @return the fdMmbId
   */
    @Column(name = "FDMMBID")
    public String getFdMmbId() {
        return fdMmbId;
    }	 
     
  /**
   * Sets the fdMmbId
   *
   * @param newFdMmbId the new fdMmbId
   */

    public void  setFdMmbId(String newFdMmbId) {
        fdMmbId = newFdMmbId;
    }	  
  /**
   * Returns the fdDstrbtnAmt
   * 
   * @return the fdDstrbtnAmt
   */
    @Column(name = "FDDSTRBTNAMT")
    public Double getFdDstrbtnAmt() {
        return fdDstrbtnAmt;
    }	 
     
  /**
   * Sets the fdDstrbtnAmt
   *
   * @param newFdDstrbtnAmt the new fdDstrbtnAmt
   */

    public void  setFdDstrbtnAmt(Double newFdDstrbtnAmt) {
        fdDstrbtnAmt = newFdDstrbtnAmt;
    }	  
    
    
}    
    
