package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Nets35300101Hdr generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_NETS_353_HDR")
public class Nets35300101Hdr  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="netDbtLmtDstrbtnMgmt.grpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="netDbtLmtDstrbtnMgmt.grpHdr.creDtTm")
    private Date creDtTm;
    
    @JaxbMapping(objPath="netDbtLmtDstrbtnMgmt.grpHdr.instgPty.instgDrctPty")
    private String instgDrctPty;
    
    @JaxbMapping(objPath="netDbtLmtDstrbtnMgmt.grpHdr.instgPty.instgPty")
    private String instgIndrctPty;
    
    @JaxbMapping(objPath="netDbtLmtDstrbtnMgmt.grpHdr.instdPty.instdDrctPty")
    private String instdDrctPty;
    
    @JaxbMapping(objPath="netDbtLmtDstrbtnMgmt.grpHdr.instdPty.instdPty")
    private String instdIndrctPty;
    
    @JaxbMapping(objPath="netDbtLmtDstrbtnMgmt.grpHdr.sysCd")
    private String sysCd;
    
    @JaxbMapping(objPath="netDbtLmtDstrbtnMgmt.grpHdr.rmk")
    private String rmk;
    
    @JaxbMapping(objPath="netDbtLmtDstrbtnMgmt.netDbtLmtDstrbtnMgmtInf.mgrId")
    private String mgrId;
    
    @JaxbMapping(objPath="netDbtLmtDstrbtnMgmt.netDbtLmtDstrbtnMgmtInf.oprClss")
    private String oprClss;
    
    @JaxbMapping(objPath="netDbtLmtDstrbtnMgmt.netDbtLmtDstrbtnMgmtInf.oprTp")
    private String oprTp;
    
    @JaxbMapping(objPath="netDbtLmtDstrbtnMgmt.netDbtLmtDstrbtnMgmtInf.nbOfMmb")
    private String nbOfMmb;
    
    @JaxbMapping(objPath="netDbtLmtDstrbtnMgmt.netDbtLmtDstrbtnMgmtInf.dstrbtnList[0]")
    private java.util.Set<Nets35300101> dstrbtnList;
    
    
	
    /** default constructor */
    public Nets35300101Hdr() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
    @Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public Date getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(Date newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the instgDrctPty
   * 
   * @return the instgDrctPty
   */
    @Column(name = "INSTGDRCTPTY")
    public String getInstgDrctPty() {
        return instgDrctPty;
    }	 
     
  /**
   * Sets the instgDrctPty
   *
   * @param newInstgDrctPty the new instgDrctPty
   */

    public void  setInstgDrctPty(String newInstgDrctPty) {
        instgDrctPty = newInstgDrctPty;
    }	  
  /**
   * Returns the instgIndrctPty
   * 
   * @return the instgIndrctPty
   */
    @Column(name = "INSTGINDRCTPTY")
    public String getInstgIndrctPty() {
        return instgIndrctPty;
    }	 
     
  /**
   * Sets the instgIndrctPty
   *
   * @param newInstgIndrctPty the new instgIndrctPty
   */

    public void  setInstgIndrctPty(String newInstgIndrctPty) {
        instgIndrctPty = newInstgIndrctPty;
    }	  
  /**
   * Returns the instdDrctPty
   * 
   * @return the instdDrctPty
   */
    @Column(name = "INSTDDRCTPTY")
    public String getInstdDrctPty() {
        return instdDrctPty;
    }	 
     
  /**
   * Sets the instdDrctPty
   *
   * @param newInstdDrctPty the new instdDrctPty
   */

    public void  setInstdDrctPty(String newInstdDrctPty) {
        instdDrctPty = newInstdDrctPty;
    }	  
  /**
   * Returns the instdIndrctPty
   * 
   * @return the instdIndrctPty
   */
    @Column(name = "INSTDINDRCTPTY")
    public String getInstdIndrctPty() {
        return instdIndrctPty;
    }	 
     
  /**
   * Sets the instdIndrctPty
   *
   * @param newInstdIndrctPty the new instdIndrctPty
   */

    public void  setInstdIndrctPty(String newInstdIndrctPty) {
        instdIndrctPty = newInstdIndrctPty;
    }	  
  /**
   * Returns the sysCd
   * 
   * @return the sysCd
   */
    @Column(name = "SYSCD")
    public String getSysCd() {
        return sysCd;
    }	 
     
  /**
   * Sets the sysCd
   *
   * @param newSysCd the new sysCd
   */

    public void  setSysCd(String newSysCd) {
        sysCd = newSysCd;
    }	  
  /**
   * Returns the rmk
   * 
   * @return the rmk
   */
    @Column(name = "RMK")
    public String getRmk() {
        return rmk;
    }	 
     
  /**
   * Sets the rmk
   *
   * @param newRmk the new rmk
   */

    public void  setRmk(String newRmk) {
        rmk = newRmk;
    }	  
  /**
   * Returns the mgrId
   * 
   * @return the mgrId
   */
    @Column(name = "MGRID")
    public String getMgrId() {
        return mgrId;
    }	 
     
  /**
   * Sets the mgrId
   *
   * @param newMgrId the new mgrId
   */

    public void  setMgrId(String newMgrId) {
        mgrId = newMgrId;
    }	  
  /**
   * Returns the oprClss
   * 
   * @return the oprClss
   */
    @Column(name = "OPRCLSS")
    public String getOprClss() {
        return oprClss;
    }	 
     
  /**
   * Sets the oprClss
   *
   * @param newOprClss the new oprClss
   */

    public void  setOprClss(String newOprClss) {
        oprClss = newOprClss;
    }	  
  /**
   * Returns the oprTp
   * 
   * @return the oprTp
   */
    @Column(name = "OPRTP")
    public String getOprTp() {
        return oprTp;
    }	 
     
  /**
   * Sets the oprTp
   *
   * @param newOprTp the new oprTp
   */

    public void  setOprTp(String newOprTp) {
        oprTp = newOprTp;
    }	  
  /**
   * Returns the nbOfMmb
   * 
   * @return the nbOfMmb
   */
    @Column(name = "NBOFMMB")
    public String getNbOfMmb() {
        return nbOfMmb;
    }	 
     
  /**
   * Sets the nbOfMmb
   *
   * @param newNbOfMmb the new nbOfMmb
   */

    public void  setNbOfMmb(String newNbOfMmb) {
        nbOfMmb = newNbOfMmb;
    }	  
  /**
   * Returns the dstrbtnList
   * 
   * @return the dstrbtnList
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
    public java.util.Set<Nets35300101> getDstrbtnList() {
        return dstrbtnList;
    }	 
     
  /**
   * Sets the dstrbtnList
   *
   * @param newDstrbtnList the new dstrbtnList
   */

    public void  setDstrbtnList(java.util.Set<Nets35300101> newDstrbtnList) {
        dstrbtnList = newDstrbtnList;
    }	  
    
    
}    
    
