package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Pbcs60800101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_PBCS_608")
public class Pbcs60800101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="chrgAndRtrList.chrgAndRtrListInf.chrgInf[0].chrgSys")
    private String chrgSys;
    
    @JaxbMapping(objPath="chrgAndRtrList.chrgAndRtrListInf.chrgInf[0].amt.value")
    private Double amt;
    
    private Pbcs60800101Hdr fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Pbcs60800101Hdr getFid() {
		return fid;
	}


	public void setFid(Pbcs60800101Hdr fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Pbcs60800101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the chrgSys
   * 
   * @return the chrgSys
   */
    @Column(name = "CHRGSYS")
    public String getChrgSys() {
        return chrgSys;
    }	 
     
  /**
   * Sets the chrgSys
   *
   * @param newChrgSys the new chrgSys
   */

    public void  setChrgSys(String newChrgSys) {
        chrgSys = newChrgSys;
    }	  
  /**
   * Returns the amt
   * 
   * @return the amt
   */
    @Column(name = "AMT")
    public Double getAmt() {
        return amt;
    }	 
     
  /**
   * Sets the amt
   *
   * @param newAmt the new amt
   */

    public void  setAmt(Double newAmt) {
        amt = newAmt;
    }	  
    
    
}    
    
