package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Saps73600101Hdr generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_SAPS_736_HDR")
public class Saps73600101Hdr  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.grpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.grpHdr.creDtTm")
    private Date creDtTm;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.grpHdr.instgPty.instgDrctPty")
    private String instgDrctPty;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.grpHdr.instgPty.instgPty")
    private String instgIndrctPty;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.grpHdr.instdPty.instdDrctPty")
    private String instdDrctPty;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.grpHdr.instdPty.instdPty")
    private String instdIndrctPty;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.grpHdr.sysCd")
    private String sysCd;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.grpHdr.rmk")
    private String rmk;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.acctgDailyDwnLdInf.workDt")
    private Date workDt;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.acctgDailyDwnLdInf.initlAmt")
    private String initlAmt;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.acctgDailyDwnLdInf.dailyDbtrAmt")
    private String dailyDbtrAmt;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.acctgDailyDwnLdInf.dailyCdtrAmt")
    private String dailyCdtrAmt;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.acctgDailyDwnLdInf.fnlAmt")
    private String fnlAmt;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.acctgDailyDwnLdInf.nbOfTx")
    private String nbOfTxs;
    
    @JaxbMapping(objPath="acctgDailyDwnLd.acctgDailyDwnLdInf.txList[0]")
    private java.util.Set<Saps73600101> txList;
    
    
	
    /** default constructor */
    public Saps73600101Hdr() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
    @Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public Date getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(Date newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the instgDrctPty
   * 
   * @return the instgDrctPty
   */
    @Column(name = "INSTGDRCTPTY")
    public String getInstgDrctPty() {
        return instgDrctPty;
    }	 
     
  /**
   * Sets the instgDrctPty
   *
   * @param newInstgDrctPty the new instgDrctPty
   */

    public void  setInstgDrctPty(String newInstgDrctPty) {
        instgDrctPty = newInstgDrctPty;
    }	  
  /**
   * Returns the instgIndrctPty
   * 
   * @return the instgIndrctPty
   */
    @Column(name = "INSTGINDRCTPTY")
    public String getInstgIndrctPty() {
        return instgIndrctPty;
    }	 
     
  /**
   * Sets the instgIndrctPty
   *
   * @param newInstgIndrctPty the new instgIndrctPty
   */

    public void  setInstgIndrctPty(String newInstgIndrctPty) {
        instgIndrctPty = newInstgIndrctPty;
    }	  
  /**
   * Returns the instdDrctPty
   * 
   * @return the instdDrctPty
   */
    @Column(name = "INSTDDRCTPTY")
    public String getInstdDrctPty() {
        return instdDrctPty;
    }	 
     
  /**
   * Sets the instdDrctPty
   *
   * @param newInstdDrctPty the new instdDrctPty
   */

    public void  setInstdDrctPty(String newInstdDrctPty) {
        instdDrctPty = newInstdDrctPty;
    }	  
  /**
   * Returns the instdIndrctPty
   * 
   * @return the instdIndrctPty
   */
    @Column(name = "INSTDINDRCTPTY")
    public String getInstdIndrctPty() {
        return instdIndrctPty;
    }	 
     
  /**
   * Sets the instdIndrctPty
   *
   * @param newInstdIndrctPty the new instdIndrctPty
   */

    public void  setInstdIndrctPty(String newInstdIndrctPty) {
        instdIndrctPty = newInstdIndrctPty;
    }	  
  /**
   * Returns the sysCd
   * 
   * @return the sysCd
   */
    @Column(name = "SYSCD")
    public String getSysCd() {
        return sysCd;
    }	 
     
  /**
   * Sets the sysCd
   *
   * @param newSysCd the new sysCd
   */

    public void  setSysCd(String newSysCd) {
        sysCd = newSysCd;
    }	  
  /**
   * Returns the rmk
   * 
   * @return the rmk
   */
    @Column(name = "RMK")
    public String getRmk() {
        return rmk;
    }	 
     
  /**
   * Sets the rmk
   *
   * @param newRmk the new rmk
   */

    public void  setRmk(String newRmk) {
        rmk = newRmk;
    }	  
  /**
   * Returns the workDt
   * 
   * @return the workDt
   */
    @Column(name = "WORKDT")
    public Date getWorkDt() {
        return workDt;
    }	 
     
  /**
   * Sets the workDt
   *
   * @param newWorkDt the new workDt
   */

    public void  setWorkDt(Date newWorkDt) {
        workDt = newWorkDt;
    }	  
  /**
   * Returns the initlAmt
   * 
   * @return the initlAmt
   */
    @Column(name = "INITLAMT")
    public String getInitlAmt() {
        return initlAmt;
    }	 
     
  /**
   * Sets the initlAmt
   *
   * @param newInitlAmt the new initlAmt
   */

    public void  setInitlAmt(String newInitlAmt) {
        initlAmt = newInitlAmt;
    }	  
  /**
   * Returns the dailyDbtrAmt
   * 
   * @return the dailyDbtrAmt
   */
    @Column(name = "DAILYDBTRAMT")
    public String getDailyDbtrAmt() {
        return dailyDbtrAmt;
    }	 
     
  /**
   * Sets the dailyDbtrAmt
   *
   * @param newDailyDbtrAmt the new dailyDbtrAmt
   */

    public void  setDailyDbtrAmt(String newDailyDbtrAmt) {
        dailyDbtrAmt = newDailyDbtrAmt;
    }	  
  /**
   * Returns the dailyCdtrAmt
   * 
   * @return the dailyCdtrAmt
   */
    @Column(name = "DAILYCDTRAMT")
    public String getDailyCdtrAmt() {
        return dailyCdtrAmt;
    }	 
     
  /**
   * Sets the dailyCdtrAmt
   *
   * @param newDailyCdtrAmt the new dailyCdtrAmt
   */

    public void  setDailyCdtrAmt(String newDailyCdtrAmt) {
        dailyCdtrAmt = newDailyCdtrAmt;
    }	  
  /**
   * Returns the fnlAmt
   * 
   * @return the fnlAmt
   */
    @Column(name = "FNLAMT")
    public String getFnlAmt() {
        return fnlAmt;
    }	 
     
  /**
   * Sets the fnlAmt
   *
   * @param newFnlAmt the new fnlAmt
   */

    public void  setFnlAmt(String newFnlAmt) {
        fnlAmt = newFnlAmt;
    }	  
  /**
   * Returns the nbOfTxs
   * 
   * @return the nbOfTxs
   */
    @Column(name = "NBOFTXS")
    public String getNbOfTxs() {
        return nbOfTxs;
    }	 
     
  /**
   * Sets the nbOfTxs
   *
   * @param newNbOfTxs the new nbOfTxs
   */

    public void  setNbOfTxs(String newNbOfTxs) {
        nbOfTxs = newNbOfTxs;
    }	  
  /**
   * Returns the txList
   * 
   * @return the txList
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
    public java.util.Set<Saps73600101> getTxList() {
        return txList;
    }	 
     
  /**
   * Sets the txList
   *
   * @param newTxList the new txList
   */

    public void  setTxList(java.util.Set<Saps73600101> newTxList) {
        txList = newTxList;
    }	  
    
    
}    
    
