package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Saps73500101AcctList generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_SAPS_735")
public class Saps73500101AcctList  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="acctgDtlDwnLd.acctgDtlDwnLdInf.acctList[0].acctTp")
    private String acctTp;
    
    @JaxbMapping(objPath="acctgDtlDwnLd.acctgDtlDwnLdInf.acctList[0].acct")
    private String acct;
    
    @JaxbMapping(objPath="acctgDtlDwnLd.acctgDtlDwnLdInf.acctList[0].nbOfBookg")
    private String nbOfBookg;
    
    @JaxbMapping(objPath="acctgDtlDwnLd.acctgDtlDwnLdInf.acctList[0].bookgList[0]")
    private java.util.Set<Saps73500101BookgList> bookgList;
    
    private Saps73500101 fid;
    
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Saps73500101 getFid() {
		return fid;
	}


	public void setFid(Saps73500101 fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Saps73500101AcctList() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the acctTp
   * 
   * @return the acctTp
   */
    @Column(name = "ACCTTP")
    public String getAcctTp() {
        return acctTp;
    }	 
     
  /**
   * Sets the acctTp
   *
   * @param newAcctTp the new acctTp
   */

    public void  setAcctTp(String newAcctTp) {
        acctTp = newAcctTp;
    }	  
  /**
   * Returns the acct
   * 
   * @return the acct
   */
    @Column(name = "ACCT")
    public String getAcct() {
        return acct;
    }	 
     
  /**
   * Sets the acct
   *
   * @param newAcct the new acct
   */

    public void  setAcct(String newAcct) {
        acct = newAcct;
    }	  
  /**
   * Returns the nbOfBookg
   * 
   * @return the nbOfBookg
   */
    @Column(name = "NBOFBOOKG")
    public String getNbOfBookg() {
        return nbOfBookg;
    }	 
     
  /**
   * Sets the nbOfBookg
   *
   * @param newNbOfBookg the new nbOfBookg
   */

    public void  setNbOfBookg(String newNbOfBookg) {
        nbOfBookg = newNbOfBookg;
    }	  
    /**
     * Returns the bookgList
     * 
     * @return the bookgList
     */
    	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
      public java.util.Set<Saps73500101BookgList> getBookgList() {
          return bookgList;
      }	 
       
    /**
     * Sets the bookgList
     *
     * @param newBookgList the new bookgList
     */

      public void  setBookgList(java.util.Set<Saps73500101BookgList> newBookgList) {
          bookgList = newBookgList;
      }	  
    
    
}    
    
