package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Saps73400101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_SAPS_734")
public class Saps73400101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="acstcbsAnlAcctg.grpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="acstcbsAnlAcctg.grpHdr.creDtTm")
    private String creDtTm;
    
    @JaxbMapping(objPath="acstcbsAnlAcctg.grpHdr.instgPty.instgDrctPty")
    private String instgDrctPty;
    
    @JaxbMapping(objPath="acstcbsAnlAcctg.grpHdr.instgPty.instgPty")
    private String instgIndrctPty;
    
    @JaxbMapping(objPath="acstcbsAnlAcctg.grpHdr.instdPty.instdDrctPty")
    private String instdDrctPty;
    
    @JaxbMapping(objPath="acstcbsAnlAcctg.grpHdr.instdPty.instdPty")
    private String instdIndrctPty;
    
    @JaxbMapping(objPath="acstcbsAnlAcctg.grpHdr.sysCd")
    private String sysCd;
    
    @JaxbMapping(objPath="acstcbsAnlAcctg.grpHdr.rmk")
    private String rmk;
    
    @JaxbMapping(objPath="acstcbsAnlAcctg.acstcbsAnlAcctgInf.acct")
    private String acct;
    
    @JaxbMapping(objPath="acstcbsAnlAcctg.acstcbsAnlAcctgInf.initlAmt")
    private String initlAmt;
    
    @JaxbMapping(objPath="acstcbsAnlAcctg.acstcbsAnlAcctgInf.initlAmt")
    private String anlDbtrAmt;
    
    @JaxbMapping(objPath="acstcbsAnlAcctg.acstcbsAnlAcctgInf.anlCdtrAmt")
    private String anlCdtrAmt;
    
    @JaxbMapping(objPath="acstcbsAnlAcctg.acstcbsAnlAcctgInf.anlCdtrAmt")
    private String fnlAmt;
    
    
	
    /** default constructor */
    public Saps73400101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
    @Id
	  @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	  @SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	  @GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public String getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(String newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the instgDrctPty
   * 
   * @return the instgDrctPty
   */
    @Column(name = "INSTGDRCTPTY")
    public String getInstgDrctPty() {
        return instgDrctPty;
    }	 
     
  /**
   * Sets the instgDrctPty
   *
   * @param newInstgDrctPty the new instgDrctPty
   */

    public void  setInstgDrctPty(String newInstgDrctPty) {
        instgDrctPty = newInstgDrctPty;
    }	  
  /**
   * Returns the instgIndrctPty
   * 
   * @return the instgIndrctPty
   */
    @Column(name = "INSTGINDRCTPTY")
    public String getInstgIndrctPty() {
        return instgIndrctPty;
    }	 
     
  /**
   * Sets the instgIndrctPty
   *
   * @param newInstgIndrctPty the new instgIndrctPty
   */

    public void  setInstgIndrctPty(String newInstgIndrctPty) {
        instgIndrctPty = newInstgIndrctPty;
    }	  
  /**
   * Returns the instdDrctPty
   * 
   * @return the instdDrctPty
   */
    @Column(name = "INSTDDRCTPTY")
    public String getInstdDrctPty() {
        return instdDrctPty;
    }	 
     
  /**
   * Sets the instdDrctPty
   *
   * @param newInstdDrctPty the new instdDrctPty
   */

    public void  setInstdDrctPty(String newInstdDrctPty) {
        instdDrctPty = newInstdDrctPty;
    }	  
  /**
   * Returns the instdIndrctPty
   * 
   * @return the instdIndrctPty
   */
    @Column(name = "INSTDINDRCTPTY")
    public String getInstdIndrctPty() {
        return instdIndrctPty;
    }	 
     
  /**
   * Sets the instdIndrctPty
   *
   * @param newInstdIndrctPty the new instdIndrctPty
   */

    public void  setInstdIndrctPty(String newInstdIndrctPty) {
        instdIndrctPty = newInstdIndrctPty;
    }	  
  /**
   * Returns the sysCd
   * 
   * @return the sysCd
   */
    @Column(name = "SYSCD")
    public String getSysCd() {
        return sysCd;
    }	 
     
  /**
   * Sets the sysCd
   *
   * @param newSysCd the new sysCd
   */

    public void  setSysCd(String newSysCd) {
        sysCd = newSysCd;
    }	  
  /**
   * Returns the rmk
   * 
   * @return the rmk
   */
    @Column(name = "RMK")
    public String getRmk() {
        return rmk;
    }	 
     
  /**
   * Sets the rmk
   *
   * @param newRmk the new rmk
   */

    public void  setRmk(String newRmk) {
        rmk = newRmk;
    }	  
  /**
   * Returns the acct
   * 
   * @return the acct
   */
    @Column(name = "ACCT")
    public String getAcct() {
        return acct;
    }	 
     
  /**
   * Sets the acct
   *
   * @param newAcct the new acct
   */

    public void  setAcct(String newAcct) {
        acct = newAcct;
    }	  
  /**
   * Returns the initlAmt
   * 
   * @return the initlAmt
   */
    @Column(name = "INITLAMT")
    public String getInitlAmt() {
        return initlAmt;
    }	 
     
  /**
   * Sets the initlAmt
   *
   * @param newInitlAmt the new initlAmt
   */

    public void  setInitlAmt(String newInitlAmt) {
        initlAmt = newInitlAmt;
    }	  
  /**
   * Returns the anlDbtrAmt
   * 
   * @return the anlDbtrAmt
   */
    @Column(name = "ANLDBTRAMT")
    public String getAnlDbtrAmt() {
        return anlDbtrAmt;
    }	 
     
  /**
   * Sets the anlDbtrAmt
   *
   * @param newAnlDbtrAmt the new anlDbtrAmt
   */

    public void  setAnlDbtrAmt(String newAnlDbtrAmt) {
        anlDbtrAmt = newAnlDbtrAmt;
    }	  
  /**
   * Returns the anlCdtrAmt
   * 
   * @return the anlCdtrAmt
   */
    @Column(name = "ANLCDTRAMT")
    public String getAnlCdtrAmt() {
        return anlCdtrAmt;
    }	 
     
  /**
   * Sets the anlCdtrAmt
   *
   * @param newAnlCdtrAmt the new anlCdtrAmt
   */

    public void  setAnlCdtrAmt(String newAnlCdtrAmt) {
        anlCdtrAmt = newAnlCdtrAmt;
    }	  
  /**
   * Returns the fnlAmt
   * 
   * @return the fnlAmt
   */
    @Column(name = "FNLAMT")
    public String getFnlAmt() {
        return fnlAmt;
    }	 
     
  /**
   * Sets the fnlAmt
   *
   * @param newFnlAmt the new fnlAmt
   */

    public void  setFnlAmt(String newFnlAmt) {
        fnlAmt = newFnlAmt;
    }	  
    
    
}    
    
