package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Saps61100101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_SAPS_611")
public class Saps61100101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="intraCityNetgSttlm.intraCityNetgSttlmInf.bookgList[0].bookgId")
    private String bookgId;
    
    @JaxbMapping(objPath="intraCityNetgSttlm.intraCityNetgSttlmInf.bookgList[0].dbtCdtId")
    private String dbtCdtId;
    
    @JaxbMapping(objPath="intraCityNetgSttlm.intraCityNetgSttlmInf.bookgList[0].amt.value")
    private Double amt;
    
    private Saps61100101Hdr fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Saps61100101Hdr getFid() {
		return fid;
	}


	public void setFid(Saps61100101Hdr fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Saps61100101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the bookgId
   * 
   * @return the bookgId
   */
    @Column(name = "BOOKGID")
    public String getBookgId() {
        return bookgId;
    }	 
     
  /**
   * Sets the bookgId
   *
   * @param newBookgId the new bookgId
   */

    public void  setBookgId(String newBookgId) {
        bookgId = newBookgId;
    }	  
  /**
   * Returns the dbtCdtId
   * 
   * @return the dbtCdtId
   */
    @Column(name = "DBTCDTID")
    public String getDbtCdtId() {
        return dbtCdtId;
    }	 
     
  /**
   * Sets the dbtCdtId
   *
   * @param newDbtCdtId the new dbtCdtId
   */

    public void  setDbtCdtId(String newDbtCdtId) {
        dbtCdtId = newDbtCdtId;
    }	  
  /**
   * Returns the amt
   * 
   * @return the amt
   */
    @Column(name = "AMT")
    public Double getAmt() {
        return amt;
    }	 
     
  /**
   * Sets the amt
   *
   * @param newAmt the new amt
   */

    public void  setAmt(Double newAmt) {
        amt = newAmt;
    }	  
    
    
}    
    
