package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Saps73300101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_SAPS_733")
public class Saps73300101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="acstcbsDailyAcctg.acstcbsDailyAcctgInf.chckngList[0].acctTp")
    private String acctTp;
    
    @JaxbMapping(objPath="acstcbsDailyAcctg.acstcbsDailyAcctgInf.chckngList[0].acct")
    private String acct;
    
    @JaxbMapping(objPath="acstcbsDailyAcctg.acstcbsDailyAcctgInf.chckngList[0].initlAmt")
    private String initlAmt;
    
    @JaxbMapping(objPath="acstcbsDailyAcctg.acstcbsDailyAcctgInf.chckngList[0].fnlAmt")
    private String fnlAmt;
    
    @JaxbMapping(objPath="acstcbsDailyAcctg.acstcbsDailyAcctgInf.chckngList[0].dbtrAmt")
    private String hVPSDbtrAmt;
    
    @JaxbMapping(objPath="acstcbsDailyAcctg.acstcbsDailyAcctgInf.chckngList[0].cdtrAmt")
    private String hVPSCdtrAmt;
    
    private Saps73300101Hdr fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Saps73300101Hdr getFid() {
		return fid;
	}


	public void setFid(Saps73300101Hdr fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Saps73300101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the acctTp
   * 
   * @return the acctTp
   */
    @Column(name = "ACCTTP")
    public String getAcctTp() {
        return acctTp;
    }	 
     
  /**
   * Sets the acctTp
   *
   * @param newAcctTp the new acctTp
   */

    public void  setAcctTp(String newAcctTp) {
        acctTp = newAcctTp;
    }	  
  /**
   * Returns the acct
   * 
   * @return the acct
   */
    @Column(name = "ACCT")
    public String getAcct() {
        return acct;
    }	 
     
  /**
   * Sets the acct
   *
   * @param newAcct the new acct
   */

    public void  setAcct(String newAcct) {
        acct = newAcct;
    }	  
  /**
   * Returns the initlAmt
   * 
   * @return the initlAmt
   */
    @Column(name = "INITLAMT")
    public String getInitlAmt() {
        return initlAmt;
    }	 
     
  /**
   * Sets the initlAmt
   *
   * @param newInitlAmt the new initlAmt
   */

    public void  setInitlAmt(String newInitlAmt) {
        initlAmt = newInitlAmt;
    }	  
  /**
   * Returns the fnlAmt
   * 
   * @return the fnlAmt
   */
    @Column(name = "FNLAMT")
    public String getFnlAmt() {
        return fnlAmt;
    }	 
     
  /**
   * Sets the fnlAmt
   *
   * @param newFnlAmt the new fnlAmt
   */

    public void  setFnlAmt(String newFnlAmt) {
        fnlAmt = newFnlAmt;
    }	  
  /**
   * Returns the hVPSDbtrAmt
   * 
   * @return the hVPSDbtrAmt
   */
    @Column(name = "HVPSDBTRAMT")
    public String getHVPSDbtrAmt() {
        return hVPSDbtrAmt;
    }	 
     
  /**
   * Sets the hVPSDbtrAmt
   *
   * @param newHVPSDbtrAmt the new hVPSDbtrAmt
   */

    public void  setHVPSDbtrAmt(String newHVPSDbtrAmt) {
        hVPSDbtrAmt = newHVPSDbtrAmt;
    }	  
  /**
   * Returns the hVPSCdtrAmt
   * 
   * @return the hVPSCdtrAmt
   */
    @Column(name = "HVPSCDTRAMT")
    public String getHVPSCdtrAmt() {
        return hVPSCdtrAmt;
    }	 
     
  /**
   * Sets the hVPSCdtrAmt
   *
   * @param newHVPSCdtrAmt the new hVPSCdtrAmt
   */

    public void  setHVPSCdtrAmt(String newHVPSCdtrAmt) {
        hVPSCdtrAmt = newHVPSCdtrAmt;
    }	  
    
    
}    
    
