package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Saps61000101Hdr generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_SAPS_610_HDR")
public class Saps61000101Hdr  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.grpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.grpHdr.creDtTm")
    private Date creDtTm;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.grpHdr.instgPty.instgDrctPty")
    private String instgDrctPty;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.grpHdr.instgPty.instgPty")
    private String instgIndrctPty;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.grpHdr.instdPty.instdDrctPty")
    private String instdDrctPty;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.grpHdr.instdPty.instdPty")
    private String instdIndrctPty;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.grpHdr.sysCd")
    private String sysCd;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.grpHdr.rmk")
    private String rmk;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.orgnlGrpHdr.orgnlMsgId")
    private String orgnlMsgId;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.orgnlGrpHdr.orgnlInstgPty")
    private String orgnlInstgDrctPty;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.orgnlGrpHdr.orgnlMT")
    private String orgnlMT;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.npcPrcInf.prcSts")
    private String prcSts;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.npcPrcInf.prcCd")
    private String prcCd;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.npcPrcInf.rjctInf")
    private String rjctInf;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.npcPrcInf.netgDt")
    private Date netgDt;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.npcPrcInf.netgRnd")
    private String netgRnd;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.npcPrcInf.sttlmDt")
    private Date sttlmDt;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.npcPrcInf.rcvTm")
    private Date rcvTm;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.npcPrcInf.trnsmtTm")
    private Date trnsmtTm;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.intraCityNetgQryRspnInf.orgnlGrpHdr.orgnlMsgId")
    private String respOrgnlMsgId;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.intraCityNetgQryRspnInf.orgnlGrpHdr.orgnlInstgPty")
    private String respOrgnlInstgDrctPty;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.intraCityNetgQryRspnInf.orgnlGrpHdr.orgnlMT")
    private String respOrgnlMT;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.intraCityNetgQryRspnInf.rspnSts")
    private String rspnSts;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.intraCityNetgQryRspnInf.nbOfMmb")
    private String nbOfMmb;
    
    @JaxbMapping(objPath="intraCityNetgQryRspn.intraCityNetgQryRspnInf.bookgList[0]")
    private java.util.Set<Saps61000101> bookgList;
    
    
	
    /** default constructor */
    public Saps61000101Hdr() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
    @Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public Date getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(Date newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the instgDrctPty
   * 
   * @return the instgDrctPty
   */
    @Column(name = "INSTGDRCTPTY")
    public String getInstgDrctPty() {
        return instgDrctPty;
    }	 
     
  /**
   * Sets the instgDrctPty
   *
   * @param newInstgDrctPty the new instgDrctPty
   */

    public void  setInstgDrctPty(String newInstgDrctPty) {
        instgDrctPty = newInstgDrctPty;
    }	  
  /**
   * Returns the instgIndrctPty
   * 
   * @return the instgIndrctPty
   */
    @Column(name = "INSTGINDRCTPTY")
    public String getInstgIndrctPty() {
        return instgIndrctPty;
    }	 
     
  /**
   * Sets the instgIndrctPty
   *
   * @param newInstgIndrctPty the new instgIndrctPty
   */

    public void  setInstgIndrctPty(String newInstgIndrctPty) {
        instgIndrctPty = newInstgIndrctPty;
    }	  
  /**
   * Returns the instdDrctPty
   * 
   * @return the instdDrctPty
   */
    @Column(name = "INSTDDRCTPTY")
    public String getInstdDrctPty() {
        return instdDrctPty;
    }	 
     
  /**
   * Sets the instdDrctPty
   *
   * @param newInstdDrctPty the new instdDrctPty
   */

    public void  setInstdDrctPty(String newInstdDrctPty) {
        instdDrctPty = newInstdDrctPty;
    }	  
  /**
   * Returns the instdIndrctPty
   * 
   * @return the instdIndrctPty
   */
    @Column(name = "INSTDINDRCTPTY")
    public String getInstdIndrctPty() {
        return instdIndrctPty;
    }	 
     
  /**
   * Sets the instdIndrctPty
   *
   * @param newInstdIndrctPty the new instdIndrctPty
   */

    public void  setInstdIndrctPty(String newInstdIndrctPty) {
        instdIndrctPty = newInstdIndrctPty;
    }	  
  /**
   * Returns the sysCd
   * 
   * @return the sysCd
   */
    @Column(name = "SYSCD")
    public String getSysCd() {
        return sysCd;
    }	 
     
  /**
   * Sets the sysCd
   *
   * @param newSysCd the new sysCd
   */

    public void  setSysCd(String newSysCd) {
        sysCd = newSysCd;
    }	  
  /**
   * Returns the rmk
   * 
   * @return the rmk
   */
    @Column(name = "RMK")
    public String getRmk() {
        return rmk;
    }	 
     
  /**
   * Sets the rmk
   *
   * @param newRmk the new rmk
   */

    public void  setRmk(String newRmk) {
        rmk = newRmk;
    }	  
  /**
   * Returns the orgnlMsgId
   * 
   * @return the orgnlMsgId
   */
    @Column(name = "ORGNLMSGID")
    public String getOrgnlMsgId() {
        return orgnlMsgId;
    }	 
     
  /**
   * Sets the orgnlMsgId
   *
   * @param newOrgnlMsgId the new orgnlMsgId
   */

    public void  setOrgnlMsgId(String newOrgnlMsgId) {
        orgnlMsgId = newOrgnlMsgId;
    }	  
  /**
   * Returns the orgnlInstgDrctPty
   * 
   * @return the orgnlInstgDrctPty
   */
    @Column(name = "ORGNLINSTGDRCTPTY")
    public String getOrgnlInstgDrctPty() {
        return orgnlInstgDrctPty;
    }	 
     
  /**
   * Sets the orgnlInstgDrctPty
   *
   * @param newOrgnlInstgDrctPty the new orgnlInstgDrctPty
   */

    public void  setOrgnlInstgDrctPty(String newOrgnlInstgDrctPty) {
        orgnlInstgDrctPty = newOrgnlInstgDrctPty;
    }	  
  /**
   * Returns the orgnlMT
   * 
   * @return the orgnlMT
   */
    @Column(name = "ORGNLMT")
    public String getOrgnlMT() {
        return orgnlMT;
    }	 
     
  /**
   * Sets the orgnlMT
   *
   * @param newOrgnlMT the new orgnlMT
   */

    public void  setOrgnlMT(String newOrgnlMT) {
        orgnlMT = newOrgnlMT;
    }	  
  /**
   * Returns the prcSts
   * 
   * @return the prcSts
   */
    @Column(name = "PRCSTS")
    public String getPrcSts() {
        return prcSts;
    }	 
     
  /**
   * Sets the prcSts
   *
   * @param newPrcSts the new prcSts
   */

    public void  setPrcSts(String newPrcSts) {
        prcSts = newPrcSts;
    }	  
  /**
   * Returns the prcCd
   * 
   * @return the prcCd
   */
    @Column(name = "PRCCD")
    public String getPrcCd() {
        return prcCd;
    }	 
     
  /**
   * Sets the prcCd
   *
   * @param newPrcCd the new prcCd
   */

    public void  setPrcCd(String newPrcCd) {
        prcCd = newPrcCd;
    }	  
  /**
   * Returns the rjctInf
   * 
   * @return the rjctInf
   */
    @Column(name = "RJCTINF")
    public String getRjctInf() {
        return rjctInf;
    }	 
     
  /**
   * Sets the rjctInf
   *
   * @param newRjctInf the new rjctInf
   */

    public void  setRjctInf(String newRjctInf) {
        rjctInf = newRjctInf;
    }	  
  /**
   * Returns the netgDt
   * 
   * @return the netgDt
   */
    @Column(name = "NETGDT")
    public Date getNetgDt() {
        return netgDt;
    }	 
     
  /**
   * Sets the netgDt
   *
   * @param newNetgDt the new netgDt
   */

    public void  setNetgDt(Date newNetgDt) {
        netgDt = newNetgDt;
    }	  
  /**
   * Returns the netgRnd
   * 
   * @return the netgRnd
   */
    @Column(name = "NETGRND")
    public String getNetgRnd() {
        return netgRnd;
    }	 
     
  /**
   * Sets the netgRnd
   *
   * @param newNetgRnd the new netgRnd
   */

    public void  setNetgRnd(String newNetgRnd) {
        netgRnd = newNetgRnd;
    }	  
  /**
   * Returns the sttlmDt
   * 
   * @return the sttlmDt
   */
    @Column(name = "STTLMDT")
    public Date getSttlmDt() {
        return sttlmDt;
    }	 
     
  /**
   * Sets the sttlmDt
   *
   * @param newSttlmDt the new sttlmDt
   */

    public void  setSttlmDt(Date newSttlmDt) {
        sttlmDt = newSttlmDt;
    }	  
  /**
   * Returns the rcvTm
   * 
   * @return the rcvTm
   */
    @Column(name = "RCVTM")
    public Date getRcvTm() {
        return rcvTm;
    }	 
     
  /**
   * Sets the rcvTm
   *
   * @param newRcvTm the new rcvTm
   */

    public void  setRcvTm(Date newRcvTm) {
        rcvTm = newRcvTm;
    }	  
  /**
   * Returns the trnsmtTm
   * 
   * @return the trnsmtTm
   */
    @Column(name = "TRNSMTTM")
    public Date getTrnsmtTm() {
        return trnsmtTm;
    }	 
     
  /**
   * Sets the trnsmtTm
   *
   * @param newTrnsmtTm the new trnsmtTm
   */

    public void  setTrnsmtTm(Date newTrnsmtTm) {
        trnsmtTm = newTrnsmtTm;
    }	  
  /**
   * Returns the respOrgnlMsgId
   * 
   * @return the respOrgnlMsgId
   */
    @Column(name = "RESPORGNLMSGID")
    public String getRespOrgnlMsgId() {
        return respOrgnlMsgId;
    }	 
     
  /**
   * Sets the respOrgnlMsgId
   *
   * @param newRespOrgnlMsgId the new respOrgnlMsgId
   */

    public void  setRespOrgnlMsgId(String newRespOrgnlMsgId) {
        respOrgnlMsgId = newRespOrgnlMsgId;
    }	  
  /**
   * Returns the respOrgnlInstgDrctPty
   * 
   * @return the respOrgnlInstgDrctPty
   */
    @Column(name = "RESPORGNLINSTGDRCTPTY")
    public String getRespOrgnlInstgDrctPty() {
        return respOrgnlInstgDrctPty;
    }	 
     
  /**
   * Sets the respOrgnlInstgDrctPty
   *
   * @param newRespOrgnlInstgDrctPty the new respOrgnlInstgDrctPty
   */

    public void  setRespOrgnlInstgDrctPty(String newRespOrgnlInstgDrctPty) {
        respOrgnlInstgDrctPty = newRespOrgnlInstgDrctPty;
    }	  
  /**
   * Returns the respOrgnlMT
   * 
   * @return the respOrgnlMT
   */
    @Column(name = "RESPORGNLMT")
    public String getRespOrgnlMT() {
        return respOrgnlMT;
    }	 
     
  /**
   * Sets the respOrgnlMT
   *
   * @param newRespOrgnlMT the new respOrgnlMT
   */

    public void  setRespOrgnlMT(String newRespOrgnlMT) {
        respOrgnlMT = newRespOrgnlMT;
    }	  
  /**
   * Returns the rspnSts
   * 
   * @return the rspnSts
   */
    @Column(name = "RSPNSTS")
    public String getRspnSts() {
        return rspnSts;
    }	 
     
  /**
   * Sets the rspnSts
   *
   * @param newRspnSts the new rspnSts
   */

    public void  setRspnSts(String newRspnSts) {
        rspnSts = newRspnSts;
    }	  
  /**
   * Returns the nbOfMmb
   * 
   * @return the nbOfMmb
   */
    @Column(name = "NBOFMMB")
    public String getNbOfMmb() {
        return nbOfMmb;
    }	 
     
  /**
   * Sets the nbOfMmb
   *
   * @param newNbOfMmb the new nbOfMmb
   */

    public void  setNbOfMmb(String newNbOfMmb) {
        nbOfMmb = newNbOfMmb;
    }	  
  /**
   * Returns the bookgList
   * 
   * @return the bookgList
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
    public java.util.Set<Saps61000101> getBookgList() {
        return bookgList;
    }	 
     
  /**
   * Sets the bookgList
   *
   * @param newBookgList the new bookgList
   */

    public void  setBookgList(java.util.Set<Saps61000101> newBookgList) {
        bookgList = newBookgList;
    }	  
    
    
}    
    
