package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

/**
 * Saps60300102 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_SAPS_603")
public class Saps60300102  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="bkToCstmrStmt.grpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="bkToCstmrStmt.grpHdr.creDtTm")
    private Date creDtTm;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.id")
    private String sid;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.elctrncSeqNb")
    private String elctrncSeqNb;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.creDtTm")
    private Date staCreDtTm;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.rptgSrc.prtry")
    private String ntTp;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.acct.id.othr.id")
    private String netBankId;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.bal.tp.cdOrPrtry.prtry")
    private String prtry;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.bal.amt.value")
    private Double amt;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.bal.cdtDbtInd")
    private String cdtDbtInd;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.bal.dt.dt")
    private Date dt;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.txsSummry.ttlCdtNtries.sum")
    private Double cdtSum;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.txsSummry.ttlDbtNtries.sum")
    private Double dbtSum;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.ntry.amt.value")
    private Double ntAmt;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.ntry.cdtDbtInd")
    private String entryCdtDbtInd;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.ntry.sts")
    private String sts;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.ntry.bookgDt.dt")
    private Date bookgDt;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.ntry.valDt.dt")
    private Date valDt;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.ntry.bkTxCd.domn.cd")
    private String domainCd;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.ntry.bkTxCd.domn.fmly.cd")
    private String familyCd;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.ntry.bkTxCd.domn.fmly.subFmlyCd")
    private String subFmlyCd;
    
    @JaxbMapping(objPath="bkToCstmrStmt.stmt.ntry.ntryDtls.txDtls.refs.clrSysRef")
    private String clrSysRef;
    
    
	
    /** default constructor */
    public Saps60300102() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public Date getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(Date newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the iD
   * 
   * @return the iD
   */
    @Column(name = "SID")
    public String getSid() {
        return sid;
    }	 
     
  /**
   * Sets the iD
   *
   * @param newID the new iD
   */

    public void  setSid(String newID) {
    	sid = newID;
    }	  
  /**
   * Returns the elctrncSeqNb
   * 
   * @return the elctrncSeqNb
   */
    @Column(name = "ELCTRNCSEQNB")
    public String getElctrncSeqNb() {
        return elctrncSeqNb;
    }	 
     
  /**
   * Sets the elctrncSeqNb
   *
   * @param newElctrncSeqNb the new elctrncSeqNb
   */

    public void  setElctrncSeqNb(String newElctrncSeqNb) {
        elctrncSeqNb = newElctrncSeqNb;
    }	  
  /**
   * Returns the staCreDtTm
   * 
   * @return the staCreDtTm
   */
    @Column(name = "STACREDTTM")
    public Date getStaCreDtTm() {
        return staCreDtTm;
    }	 
     
  /**
   * Sets the staCreDtTm
   *
   * @param newStaCreDtTm the new staCreDtTm
   */

    public void  setStaCreDtTm(Date newStaCreDtTm) {
        staCreDtTm = newStaCreDtTm;
    }	  
  /**
   * Returns the ntTp
   * 
   * @return the ntTp
   */
    @Column(name = "NTTP")
    public String getNtTp() {
        return ntTp;
    }	 
     
  /**
   * Sets the ntTp
   *
   * @param newNtTp the new ntTp
   */

    public void  setNtTp(String newNtTp) {
        ntTp = newNtTp;
    }	  
  /**
   * Returns the netBankId
   * 
   * @return the netBankId
   */
    @Column(name = "NETBANKID")
    public String getNetBankId() {
        return netBankId;
    }	 
     
  /**
   * Sets the netBankId
   *
   * @param newNetBankId the new netBankId
   */

    public void  setNetBankId(String newNetBankId) {
        netBankId = newNetBankId;
    }	  
  /**
   * Returns the prtry
   * 
   * @return the prtry
   */
    @Column(name = "PRTRY")
    public String getPrtry() {
        return prtry;
    }	 
     
  /**
   * Sets the prtry
   *
   * @param newPrtry the new prtry
   */

    public void  setPrtry(String newPrtry) {
        prtry = newPrtry;
    }	  
  /**
   * Returns the amt
   * 
   * @return the amt
   */
    @Column(name = "AMT")
    public Double getAmt() {
        return amt;
    }	 
     
  /**
   * Sets the amt
   *
   * @param newAmt the new amt
   */

    public void  setAmt(Double newAmt) {
        amt = newAmt;
    }	  
  /**
   * Returns the cdtDbtInd
   * 
   * @return the cdtDbtInd
   */
    @Column(name = "CDTDBTIND")
    public String getCdtDbtInd() {
        return cdtDbtInd;
    }	 
     
  /**
   * Sets the cdtDbtInd
   *
   * @param newCdtDbtInd the new cdtDbtInd
   */

    public void  setCdtDbtInd(String newCdtDbtInd) {
        cdtDbtInd = newCdtDbtInd;
    }	  
  /**
   * Returns the dt
   * 
   * @return the dt
   */
    @Column(name = "DT")
    public Date getDt() {
        return dt;
    }	 
     
  /**
   * Sets the dt
   *
   * @param newDt the new dt
   */

    public void  setDt(Date newDt) {
        dt = newDt;
    }	  
  /**
   * Returns the cdtSum
   * 
   * @return the cdtSum
   */
    @Column(name = "CDTSUM")
    public Double getCdtSum() {
        return cdtSum;
    }	 
     
  /**
   * Sets the cdtSum
   *
   * @param newCdtSum the new cdtSum
   */

    public void  setCdtSum(Double newCdtSum) {
        cdtSum = newCdtSum;
    }	  
  /**
   * Returns the dbtSum
   * 
   * @return the dbtSum
   */
    @Column(name = "DBTSUM")
    public Double getDbtSum() {
        return dbtSum;
    }	 
     
  /**
   * Sets the dbtSum
   *
   * @param newDbtSum the new dbtSum
   */

    public void  setDbtSum(Double newDbtSum) {
        dbtSum = newDbtSum;
    }	  
  /**
   * Returns the ntAmt
   * 
   * @return the ntAmt
   */
    @Column(name = "NTAMT")
    public Double getNtAmt() {
        return ntAmt;
    }	 
     
  /**
   * Sets the ntAmt
   *
   * @param newNtAmt the new ntAmt
   */

    public void  setNtAmt(Double newNtAmt) {
        ntAmt = newNtAmt;
    }	  
  /**
   * Returns the entryCdtDbtInd
   * 
   * @return the entryCdtDbtInd
   */
    @Column(name = "ENTRYCDTDBTIND")
    public String getEntryCdtDbtInd() {
        return entryCdtDbtInd;
    }	 
     
  /**
   * Sets the entryCdtDbtInd
   *
   * @param newEntryCdtDbtInd the new entryCdtDbtInd
   */

    public void  setEntryCdtDbtInd(String newEntryCdtDbtInd) {
        entryCdtDbtInd = newEntryCdtDbtInd;
    }	  
  /**
   * Returns the sts
   * 
   * @return the sts
   */
    @Column(name = "STS")
    public String getSts() {
        return sts;
    }	 
     
  /**
   * Sets the sts
   *
   * @param newSts the new sts
   */

    public void  setSts(String newSts) {
        sts = newSts;
    }	  
  /**
   * Returns the bookgDt
   * 
   * @return the bookgDt
   */
    @Column(name = "BOOKGDT")
    public Date getBookgDt() {
        return bookgDt;
    }	 
     
  /**
   * Sets the bookgDt
   *
   * @param newBookgDt the new bookgDt
   */

    public void  setBookgDt(Date newBookgDt) {
        bookgDt = newBookgDt;
    }	  
  /**
   * Returns the valDt
   * 
   * @return the valDt
   */
    @Column(name = "VALDT")
    public Date getValDt() {
        return valDt;
    }	 
     
  /**
   * Sets the valDt
   *
   * @param newValDt the new valDt
   */

    public void  setValDt(Date newValDt) {
        valDt = newValDt;
    }	  
  /**
   * Returns the domainCd
   * 
   * @return the domainCd
   */
    @Column(name = "DOMAINCD")
    public String getDomainCd() {
        return domainCd;
    }	 
     
  /**
   * Sets the domainCd
   *
   * @param newDomainCd the new domainCd
   */

    public void  setDomainCd(String newDomainCd) {
        domainCd = newDomainCd;
    }	  
  /**
   * Returns the familyCd
   * 
   * @return the familyCd
   */
    @Column(name = "FAMILYCD")
    public String getFamilyCd() {
        return familyCd;
    }	 
     
  /**
   * Sets the familyCd
   *
   * @param newFamilyCd the new familyCd
   */

    public void  setFamilyCd(String newFamilyCd) {
        familyCd = newFamilyCd;
    }	  
  /**
   * Returns the subFmlyCd
   * 
   * @return the subFmlyCd
   */
    @Column(name = "SUBFMLYCD")
    public String getSubFmlyCd() {
        return subFmlyCd;
    }	 
     
  /**
   * Sets the subFmlyCd
   *
   * @param newSubFmlyCd the new subFmlyCd
   */

    public void  setSubFmlyCd(String newSubFmlyCd) {
        subFmlyCd = newSubFmlyCd;
    }	  
  /**
   * Returns the clrSysRef
   * 
   * @return the clrSysRef
   */
    @Column(name = "CLRSYSREF")
    public String getClrSysRef() {
        return clrSysRef;
    }	 
     
  /**
   * Sets the clrSysRef
   *
   * @param newClrSysRef the new clrSysRef
   */

    public void  setClrSysRef(String newClrSysRef) {
        clrSysRef = newClrSysRef;
    }	  
    
    
}    
    
