package com.topfinance.ebo.msg;

import java.util.Date;

import com.topfinance.ebo.msg.JaxbMapping;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Saps37200101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_SAPS_372")
public class Saps37200101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.grpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.grpHdr.creDtTm")
    private Date creDtTm;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.grpHdr.instgPty.instgDrctPty")
    private String instgDrctPty;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.grpHdr.instgPty.instgPty")
    private String instgIndrctPty;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.grpHdr.instdPty.instdDrctPty")
    private String instdDrctPty;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.grpHdr.instdPty.instdPty")
    private String instdIndrctPty;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.grpHdr.sysCd")
    private String sysCd;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.grpHdr.rmk")
    private String rmk;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.acctMgmtNtfctnInf.ntfctnTp")
    private String ntfctnTp;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.sttlmAcctSts.mmbId")
    private String ntMmbId;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.sttlmAcctSts.ptyCtgy")
    private String ptyCtgy;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.sttlmAcctSts.fctvDt")
    private Date ntFctvDt;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.sttlmAcctSts.acctSts")
    private String acctSts;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.sttlmAcctSts.bal")
    private String bal;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.sttlmAcctSts.rstrctAmtLwrLmt")
    private String rstrctAmtLwrLmt;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.acctMntncAppl.mmbId")
    private String netMmbId;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.acctMntncAppl.nm")
    private String nm;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.acctMntncAppl.overdrftUpperLmt")
    private Double overdrftUpperLmt;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.acctMntncAppl.rstrctAmtLwrLmt")
    private String ntRstrctAmtLwrLmt;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.acctMntncAppl.dbtRstrctSetng")
    private String dbtRstrctSetng;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.acctMntncAppl.cdtRstrctSetng")
    private String cdtRstrctSetng;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.fndsOfPoolMgmt.fctvDt")
    private Date fctvDt;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.fndsOfPoolMgmt.swtchTp")
    private String swtchPoolTp;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.amtWrngSetng.swtchTp")
    private String swtchTp;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.amtWrngSetng.mmbId")
    private String wtchMmbId;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.amtWrngSetng.avlblWrngVal")
    private Double avlblWrngVal;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.amtWrngSetng.wrngPlusMnsTp")
    private String wrngPlusMnsTp;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.pldgFincgIdMdl.mmbId")
    private String mmbId;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.pldgFincgIdMdl.pldgFincgId")
    private String pldgFincgId;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.pldgFincgIdMdl.startingPt")
    private Double startingPt;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.prtcolSts.dbtr")
    private String dbtr;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.prtcolSts.cdtr")
    private String cdtr;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.prtcolSts.prtcolNb")
    private String prtcolNb;
    
    @JaxbMapping(objPath="acctMgmtNtfctn.ntfctnCntt.prtcolSts.fctvId")
    private String fctvId;
    
    
	
    /** default constructor */
    public Saps37200101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
    @Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public Date getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(Date newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the instgDrctPty
   * 
   * @return the instgDrctPty
   */
    @Column(name = "INSTGDRCTPTY")
    public String getInstgDrctPty() {
        return instgDrctPty;
    }	 
     
  /**
   * Sets the instgDrctPty
   *
   * @param newInstgDrctPty the new instgDrctPty
   */

    public void  setInstgDrctPty(String newInstgDrctPty) {
        instgDrctPty = newInstgDrctPty;
    }	  
  /**
   * Returns the instgIndrctPty
   * 
   * @return the instgIndrctPty
   */
    @Column(name = "INSTGINDRCTPTY")
    public String getInstgIndrctPty() {
        return instgIndrctPty;
    }	 
     
  /**
   * Sets the instgIndrctPty
   *
   * @param newInstgIndrctPty the new instgIndrctPty
   */

    public void  setInstgIndrctPty(String newInstgIndrctPty) {
        instgIndrctPty = newInstgIndrctPty;
    }	  
  /**
   * Returns the instdDrctPty
   * 
   * @return the instdDrctPty
   */
    @Column(name = "INSTDDRCTPTY")
    public String getInstdDrctPty() {
        return instdDrctPty;
    }	 
     
  /**
   * Sets the instdDrctPty
   *
   * @param newInstdDrctPty the new instdDrctPty
   */

    public void  setInstdDrctPty(String newInstdDrctPty) {
        instdDrctPty = newInstdDrctPty;
    }	  
  /**
   * Returns the instdIndrctPty
   * 
   * @return the instdIndrctPty
   */
    @Column(name = "INSTDINDRCTPTY")
    public String getInstdIndrctPty() {
        return instdIndrctPty;
    }	 
     
  /**
   * Sets the instdIndrctPty
   *
   * @param newInstdIndrctPty the new instdIndrctPty
   */

    public void  setInstdIndrctPty(String newInstdIndrctPty) {
        instdIndrctPty = newInstdIndrctPty;
    }	  
  /**
   * Returns the sysCd
   * 
   * @return the sysCd
   */
    @Column(name = "SYSCD")
    public String getSysCd() {
        return sysCd;
    }	 
     
  /**
   * Sets the sysCd
   *
   * @param newSysCd the new sysCd
   */

    public void  setSysCd(String newSysCd) {
        sysCd = newSysCd;
    }	  
  /**
   * Returns the rmk
   * 
   * @return the rmk
   */
    @Column(name = "RMK")
    public String getRmk() {
        return rmk;
    }	 
     
  /**
   * Sets the rmk
   *
   * @param newRmk the new rmk
   */

    public void  setRmk(String newRmk) {
        rmk = newRmk;
    }	  
  /**
   * Returns the ntfctnTp
   * 
   * @return the ntfctnTp
   */
    @Column(name = "NTFCTNTP")
    public String getNtfctnTp() {
        return ntfctnTp;
    }	 
     
  /**
   * Sets the ntfctnTp
   *
   * @param newNtfctnTp the new ntfctnTp
   */

    public void  setNtfctnTp(String newNtfctnTp) {
        ntfctnTp = newNtfctnTp;
    }	  
  /**
   * Returns the ntMmbId
   * 
   * @return the ntMmbId
   */
    @Column(name = "NTMMBID")
    public String getNtMmbId() {
        return ntMmbId;
    }	 
     
  /**
   * Sets the ntMmbId
   *
   * @param newNtMmbId the new ntMmbId
   */

    public void  setNtMmbId(String newNtMmbId) {
        ntMmbId = newNtMmbId;
    }	  
  /**
   * Returns the ptyCtgy
   * 
   * @return the ptyCtgy
   */
    @Column(name = "PTYCTGY")
    public String getPtyCtgy() {
        return ptyCtgy;
    }	 
     
  /**
   * Sets the ptyCtgy
   *
   * @param newPtyCtgy the new ptyCtgy
   */

    public void  setPtyCtgy(String newPtyCtgy) {
        ptyCtgy = newPtyCtgy;
    }	  
  /**
   * Returns the ntFctvDt
   * 
   * @return the ntFctvDt
   */
    @Column(name = "NTFCTVDT")
    public Date getNtFctvDt() {
        return ntFctvDt;
    }	 
     
  /**
   * Sets the ntFctvDt
   *
   * @param newNtFctvDt the new ntFctvDt
   */

    public void  setNtFctvDt(Date newNtFctvDt) {
        ntFctvDt = newNtFctvDt;
    }	  
  /**
   * Returns the acctSts
   * 
   * @return the acctSts
   */
    @Column(name = "ACCTSTS")
    public String getAcctSts() {
        return acctSts;
    }	 
     
  /**
   * Sets the acctSts
   *
   * @param newAcctSts the new acctSts
   */

    public void  setAcctSts(String newAcctSts) {
        acctSts = newAcctSts;
    }	  
  /**
   * Returns the bal
   * 
   * @return the bal
   */
    @Column(name = "BAL")
    public String getBal() {
        return bal;
    }	 
     
  /**
   * Sets the bal
   *
   * @param newBal the new bal
   */

    public void  setBal(String newBal) {
        bal = newBal;
    }	  
  /**
   * Returns the rstrctAmtLwrLmt
   * 
   * @return the rstrctAmtLwrLmt
   */
    @Column(name = "RSTRCTAMTLWRLMT")
    public String getRstrctAmtLwrLmt() {
        return rstrctAmtLwrLmt;
    }	 
     
  /**
   * Sets the rstrctAmtLwrLmt
   *
   * @param newRstrctAmtLwrLmt the new rstrctAmtLwrLmt
   */

    public void  setRstrctAmtLwrLmt(String newRstrctAmtLwrLmt) {
        rstrctAmtLwrLmt = newRstrctAmtLwrLmt;
    }	  
  /**
   * Returns the netMmbId
   * 
   * @return the netMmbId
   */
    @Column(name = "NETMMBID")
    public String getNetMmbId() {
        return netMmbId;
    }	 
     
  /**
   * Sets the netMmbId
   *
   * @param newNetMmbId the new netMmbId
   */

    public void  setNetMmbId(String newNetMmbId) {
        netMmbId = newNetMmbId;
    }	  
  /**
   * Returns the nm
   * 
   * @return the nm
   */
    @Column(name = "NM")
    public String getNm() {
        return nm;
    }	 
     
  /**
   * Sets the nm
   *
   * @param newNm the new nm
   */

    public void  setNm(String newNm) {
        nm = newNm;
    }	  
  /**
   * Returns the overdrftUpperLmt
   * 
   * @return the overdrftUpperLmt
   */
    @Column(name = "OVERDRFTUPPERLMT")
    public Double getOverdrftUpperLmt() {
        return overdrftUpperLmt;
    }	 
     
  /**
   * Sets the overdrftUpperLmt
   *
   * @param newOverdrftUpperLmt the new overdrftUpperLmt
   */

    public void  setOverdrftUpperLmt(Double newOverdrftUpperLmt) {
        overdrftUpperLmt = newOverdrftUpperLmt;
    }	  
  /**
   * Returns the ntRstrctAmtLwrLmt
   * 
   * @return the ntRstrctAmtLwrLmt
   */
    @Column(name = "NTRSTRCTAMTLWRLMT")
    public String getNtRstrctAmtLwrLmt() {
        return ntRstrctAmtLwrLmt;
    }	 
     
  /**
   * Sets the ntRstrctAmtLwrLmt
   *
   * @param newNtRstrctAmtLwrLmt the new ntRstrctAmtLwrLmt
   */

    public void  setNtRstrctAmtLwrLmt(String newNtRstrctAmtLwrLmt) {
        ntRstrctAmtLwrLmt = newNtRstrctAmtLwrLmt;
    }	  
  /**
   * Returns the dbtRstrctSetng
   * 
   * @return the dbtRstrctSetng
   */
    @Column(name = "DBTRSTRCTSETNG")
    public String getDbtRstrctSetng() {
        return dbtRstrctSetng;
    }	 
     
  /**
   * Sets the dbtRstrctSetng
   *
   * @param newDbtRstrctSetng the new dbtRstrctSetng
   */

    public void  setDbtRstrctSetng(String newDbtRstrctSetng) {
        dbtRstrctSetng = newDbtRstrctSetng;
    }	  
  /**
   * Returns the cdtRstrctSetng
   * 
   * @return the cdtRstrctSetng
   */
    @Column(name = "CDTRSTRCTSETNG")
    public String getCdtRstrctSetng() {
        return cdtRstrctSetng;
    }	 
     
  /**
   * Sets the cdtRstrctSetng
   *
   * @param newCdtRstrctSetng the new cdtRstrctSetng
   */

    public void  setCdtRstrctSetng(String newCdtRstrctSetng) {
        cdtRstrctSetng = newCdtRstrctSetng;
    }	  
  /**
   * Returns the fctvDt
   * 
   * @return the fctvDt
   */
    @Column(name = "FCTVDT")
    public Date getFctvDt() {
        return fctvDt;
    }	 
     
  /**
   * Sets the fctvDt
   *
   * @param newFctvDt the new fctvDt
   */

    public void  setFctvDt(Date newFctvDt) {
        fctvDt = newFctvDt;
    }	  
  /**
   * Returns the swtchPoolTp
   * 
   * @return the swtchPoolTp
   */
    @Column(name = "SWTCHPOOLTP")
    public String getSwtchPoolTp() {
        return swtchPoolTp;
    }	 
     
  /**
   * Sets the swtchPoolTp
   *
   * @param newSwtchPoolTp the new swtchPoolTp
   */

    public void  setSwtchPoolTp(String newSwtchPoolTp) {
        swtchPoolTp = newSwtchPoolTp;
    }	  
  /**
   * Returns the swtchTp
   * 
   * @return the swtchTp
   */
    @Column(name = "SWTCHTP")
    public String getSwtchTp() {
        return swtchTp;
    }	 
     
  /**
   * Sets the swtchTp
   *
   * @param newSwtchTp the new swtchTp
   */

    public void  setSwtchTp(String newSwtchTp) {
        swtchTp = newSwtchTp;
    }	  
  /**
   * Returns the wtchMmbId
   * 
   * @return the wtchMmbId
   */
    @Column(name = "WTCHMMBID")
    public String getWtchMmbId() {
        return wtchMmbId;
    }	 
     
  /**
   * Sets the wtchMmbId
   *
   * @param newWtchMmbId the new wtchMmbId
   */

    public void  setWtchMmbId(String newWtchMmbId) {
        wtchMmbId = newWtchMmbId;
    }	  
  /**
   * Returns the avlblWrngVal
   * 
   * @return the avlblWrngVal
   */
    @Column(name = "AVLBLWRNGVAL")
    public Double getAvlblWrngVal() {
        return avlblWrngVal;
    }	 
     
  /**
   * Sets the avlblWrngVal
   *
   * @param newAvlblWrngVal the new avlblWrngVal
   */

    public void  setAvlblWrngVal(Double newAvlblWrngVal) {
        avlblWrngVal = newAvlblWrngVal;
    }	  
  /**
   * Returns the wrngPlusMnsTp
   * 
   * @return the wrngPlusMnsTp
   */
    @Column(name = "WRNGPLUSMNSTP")
    public String getWrngPlusMnsTp() {
        return wrngPlusMnsTp;
    }	 
     
  /**
   * Sets the wrngPlusMnsTp
   *
   * @param newWrngPlusMnsTp the new wrngPlusMnsTp
   */

    public void  setWrngPlusMnsTp(String newWrngPlusMnsTp) {
        wrngPlusMnsTp = newWrngPlusMnsTp;
    }	  
  /**
   * Returns the mmbId
   * 
   * @return the mmbId
   */
    @Column(name = "MMBID")
    public String getMmbId() {
        return mmbId;
    }	 
     
  /**
   * Sets the mmbId
   *
   * @param newMmbId the new mmbId
   */

    public void  setMmbId(String newMmbId) {
        mmbId = newMmbId;
    }	  
  /**
   * Returns the pldgFincgId
   * 
   * @return the pldgFincgId
   */
    @Column(name = "PLDGFINCGID")
    public String getPldgFincgId() {
        return pldgFincgId;
    }	 
     
  /**
   * Sets the pldgFincgId
   *
   * @param newPldgFincgId the new pldgFincgId
   */

    public void  setPldgFincgId(String newPldgFincgId) {
        pldgFincgId = newPldgFincgId;
    }	  
  /**
   * Returns the startingPt
   * 
   * @return the startingPt
   */
    @Column(name = "STARTINGPT")
    public Double getStartingPt() {
        return startingPt;
    }	 
     
  /**
   * Sets the startingPt
   *
   * @param newStartingPt the new startingPt
   */

    public void  setStartingPt(Double newStartingPt) {
        startingPt = newStartingPt;
    }	  
  /**
   * Returns the dbtr
   * 
   * @return the dbtr
   */
    @Column(name = "DBTR")
    public String getDbtr() {
        return dbtr;
    }	 
     
  /**
   * Sets the dbtr
   *
   * @param newDbtr the new dbtr
   */

    public void  setDbtr(String newDbtr) {
        dbtr = newDbtr;
    }	  
  /**
   * Returns the cdtr
   * 
   * @return the cdtr
   */
    @Column(name = "CDTR")
    public String getCdtr() {
        return cdtr;
    }	 
     
  /**
   * Sets the cdtr
   *
   * @param newCdtr the new cdtr
   */

    public void  setCdtr(String newCdtr) {
        cdtr = newCdtr;
    }	  
  /**
   * Returns the prtcolNb
   * 
   * @return the prtcolNb
   */
    @Column(name = "PRTCOLNB")
    public String getPrtcolNb() {
        return prtcolNb;
    }	 
     
  /**
   * Sets the prtcolNb
   *
   * @param newPrtcolNb the new prtcolNb
   */

    public void  setPrtcolNb(String newPrtcolNb) {
        prtcolNb = newPrtcolNb;
    }	  
  /**
   * Returns the fctvId
   * 
   * @return the fctvId
   */
    @Column(name = "FCTVID")
    public String getFctvId() {
        return fctvId;
    }	 
     
  /**
   * Sets the fctvId
   *
   * @param newFctvId the new fctvId
   */

    public void  setFctvId(String newFctvId) {
        fctvId = newFctvId;
    }	  
    
    
}    
    
