package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Saps61600101Hdr generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_SAPS_616_HDR")
public class Saps61600101Hdr  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="netgListDwnLd.grpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="netgListDwnLd.grpHdr.creDtTm")
    private Date creDtTm;
    
    @JaxbMapping(objPath="netgListDwnLd.grpHdr.instgPty.instgDrctPty")
    private String instgDrctPty;
    
    @JaxbMapping(objPath="netgListDwnLd.grpHdr.instgPty.instgPty")
    private String instgIndrctPty;
    
    @JaxbMapping(objPath="netgListDwnLd.grpHdr.instdPty.instdDrctPty")
    private String instdDrctPty;
    
    @JaxbMapping(objPath="netgListDwnLd.grpHdr.instdPty.instdPty")
    private String instdIndrctPty;
    
    @JaxbMapping(objPath="netgListDwnLd.grpHdr.sysCd")
    private String sysCd;
    
    @JaxbMapping(objPath="netgListDwnLd.grpHdr.rmk")
    private String rmk;
    
    @JaxbMapping(objPath="netgListDwnLd.netgListDwnLdInf.mgrId")
    private String mgrId;
    
    @JaxbMapping(objPath="netgListDwnLd.netgListDwnLdInf.nbOfTx")
    private String nbOfTx;
    
    @JaxbMapping(objPath="netgListDwnLd.netgListDwnLdInf.ttlAmt.value")
    private Double ttlAmt;
    
    @JaxbMapping(objPath="netgListDwnLd.netgListDwnLdInf.txList[0]")
    private java.util.Set<Saps61600101> txList;
    
    
	
    /** default constructor */
    public Saps61600101Hdr() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
    @Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public Date getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(Date newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the instgDrctPty
   * 
   * @return the instgDrctPty
   */
    @Column(name = "INSTGDRCTPTY")
    public String getInstgDrctPty() {
        return instgDrctPty;
    }	 
     
  /**
   * Sets the instgDrctPty
   *
   * @param newInstgDrctPty the new instgDrctPty
   */

    public void  setInstgDrctPty(String newInstgDrctPty) {
        instgDrctPty = newInstgDrctPty;
    }	  
  /**
   * Returns the instgIndrctPty
   * 
   * @return the instgIndrctPty
   */
    @Column(name = "INSTGINDRCTPTY")
    public String getInstgIndrctPty() {
        return instgIndrctPty;
    }	 
     
  /**
   * Sets the instgIndrctPty
   *
   * @param newInstgIndrctPty the new instgIndrctPty
   */

    public void  setInstgIndrctPty(String newInstgIndrctPty) {
        instgIndrctPty = newInstgIndrctPty;
    }	  
  /**
   * Returns the instdDrctPty
   * 
   * @return the instdDrctPty
   */
    @Column(name = "INSTDDRCTPTY")
    public String getInstdDrctPty() {
        return instdDrctPty;
    }	 
     
  /**
   * Sets the instdDrctPty
   *
   * @param newInstdDrctPty the new instdDrctPty
   */

    public void  setInstdDrctPty(String newInstdDrctPty) {
        instdDrctPty = newInstdDrctPty;
    }	  
  /**
   * Returns the instdIndrctPty
   * 
   * @return the instdIndrctPty
   */
    @Column(name = "INSTDINDRCTPTY")
    public String getInstdIndrctPty() {
        return instdIndrctPty;
    }	 
     
  /**
   * Sets the instdIndrctPty
   *
   * @param newInstdIndrctPty the new instdIndrctPty
   */

    public void  setInstdIndrctPty(String newInstdIndrctPty) {
        instdIndrctPty = newInstdIndrctPty;
    }	  
  /**
   * Returns the sysCd
   * 
   * @return the sysCd
   */
    @Column(name = "SYSCD")
    public String getSysCd() {
        return sysCd;
    }	 
     
  /**
   * Sets the sysCd
   *
   * @param newSysCd the new sysCd
   */

    public void  setSysCd(String newSysCd) {
        sysCd = newSysCd;
    }	  
  /**
   * Returns the rmk
   * 
   * @return the rmk
   */
    @Column(name = "RMK")
    public String getRmk() {
        return rmk;
    }	 
     
  /**
   * Sets the rmk
   *
   * @param newRmk the new rmk
   */

    public void  setRmk(String newRmk) {
        rmk = newRmk;
    }	  
  /**
   * Returns the mgrId
   * 
   * @return the mgrId
   */
    @Column(name = "MGRID")
    public String getMgrId() {
        return mgrId;
    }	 
     
  /**
   * Sets the mgrId
   *
   * @param newMgrId the new mgrId
   */

    public void  setMgrId(String newMgrId) {
        mgrId = newMgrId;
    }	  
  /**
   * Returns the nbOfTx
   * 
   * @return the nbOfTx
   */
    @Column(name = "NBOFTX")
    public String getNbOfTx() {
        return nbOfTx;
    }	 
     
  /**
   * Sets the nbOfTx
   *
   * @param newNbOfTx the new nbOfTx
   */

    public void  setNbOfTx(String newNbOfTx) {
        nbOfTx = newNbOfTx;
    }	  
  /**
   * Returns the ttlAmt
   * 
   * @return the ttlAmt
   */
    @Column(name = "TTLAMT")
    public Double getTtlAmt() {
        return ttlAmt;
    }	 
     
  /**
   * Sets the ttlAmt
   *
   * @param newTtlAmt the new ttlAmt
   */

    public void  setTtlAmt(Double newTtlAmt) {
        ttlAmt = newTtlAmt;
    }	  
  /**
   * Returns the txList
   * 
   * @return the txList
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "fid")
    public java.util.Set<Saps61600101> getTxList() {
        return txList;
    }	 
     
  /**
   * Sets the txList
   *
   * @param newTxList the new txList
   */

    public void  setTxList(java.util.Set<Saps61600101> newTxList) {
        txList = newTxList;
    }	  
    
    
}    
    
