package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * Saps73800101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_C2_SAPS_738")
public class Saps73800101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="balWorkDayChckngRspn.balWorkDayChckngRspnInf.umtchdList[0].mmbId")
    private String mmbId;
    
    @JaxbMapping(objPath="balWorkDayChckngRspn.balWorkDayChckngRspnInf.umtchdList[0].acsInitlAmt")
    private String aCSInitlAmt;
    
    @JaxbMapping(objPath="balWorkDayChckngRspn.balWorkDayChckngRspnInf.umtchdList[0].sapsInitlAmt")
    private String sAPSInitlAmt;
    
    private Saps73800101Hdr fid;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="FID", nullable=false, updatable=false)
    public Saps73800101Hdr getFid() {
		return fid;
	}


	public void setFid(Saps73800101Hdr fid) {
		this.fid = fid;
	}


	/** default constructor */
    public Saps73800101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the mmbId
   * 
   * @return the mmbId
   */
    @Column(name = "MMBID")
    public String getMmbId() {
        return mmbId;
    }	 
     
  /**
   * Sets the mmbId
   *
   * @param newMmbId the new mmbId
   */

    public void  setMmbId(String newMmbId) {
        mmbId = newMmbId;
    }	  
  /**
   * Returns the aCSInitlAmt
   * 
   * @return the aCSInitlAmt
   */
    @Column(name = "ACSINITLAMT")
    public String getACSInitlAmt() {
        return aCSInitlAmt;
    }	 
     
  /**
   * Sets the aCSInitlAmt
   *
   * @param newACSInitlAmt the new aCSInitlAmt
   */

    public void  setACSInitlAmt(String newACSInitlAmt) {
        aCSInitlAmt = newACSInitlAmt;
    }	  
  /**
   * Returns the sAPSInitlAmt
   * 
   * @return the sAPSInitlAmt
   */
    @Column(name = "SAPSINITLAMT")
    public String getSAPSInitlAmt() {
        return sAPSInitlAmt;
    }	 
     
  /**
   * Sets the sAPSInitlAmt
   *
   * @param newSAPSInitlAmt the new sAPSInitlAmt
   */

    public void  setSAPSInitlAmt(String newSAPSInitlAmt) {
        sAPSInitlAmt = newSAPSInitlAmt;
    }	  
    
    
}    
    
