//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.03 at 08:46:17 ÏÂÎç CST 
//


package com.xml.cnaps2.nets.v40600101;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NetgQQryRspn" type="{urn:cnaps:std:nets:2010:tech:xsd:nets.406.001.01}NetgQQryRspnV01"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "netgQQryRspn"
})
public class Document {

    @XmlElement(name = "NetgQQryRspn", required = true)
    protected NetgQQryRspnV01 netgQQryRspn;

    /**
     * Gets the value of the netgQQryRspn property.
     * 
     * @return
     *     possible object is
     *     {@link NetgQQryRspnV01 }
     *     
     */
    public NetgQQryRspnV01 getNetgQQryRspn() {
        return netgQQryRspn;
    }

    /**
     * Sets the value of the netgQQryRspn property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetgQQryRspnV01 }
     *     
     */
    public void setNetgQQryRspn(NetgQQryRspnV01 value) {
        this.netgQQryRspn = value;
    }

}
