package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Beps12700101CstmrDrctDbtInf generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_MSG_BEPS_127_001_01___CstmrDrctDbtInf")
public class Beps12700101CstmrDrctDbtInf  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].txId")
    private String txId;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].agrmtNb")
    private String agrmtNb;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].dbtr.nm")
    private String dbtrNm;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].dbtrAcct.id.othr.id")
    private String dbtrAcctId;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].dbtrAcct.id.othr.issr")
    private String dbtrAcctIssr;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].dbtrAgt.brnchId.id")
    private String dbtrAgtBrnchId;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].cdtrAgt.brnchId.id")
    private String cdtrAgtBrnchId;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].cdtr.nm")
    private String cdtrNm;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].cdtrAcct.id.othr.id")
    private String cdtrAcctId;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].cdtrAcct.id.othr.issr")
    private String cdtrAcctIssr;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].amt.value")
    private Double intrBkSttlmAmt;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].pmtTpInf.ctgyPurp.prtry")
    private String prtryTpCd;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].purp.prtry")
    private String prtryTcCd;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].addtlInf")
    private String addtlInf;
    
    
	
    /** default constructor */
    public Beps12700101CstmrDrctDbtInf() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the txId
   * 
   * @return the txId
   */
    @Column(name = "TXID")
    public String getTxId() {
        return txId;
    }	 
     
  /**
   * Sets the txId
   *
   * @param newTxId the new txId
   */

    public void  setTxId(String newTxId) {
        txId = newTxId;
    }	  
  /**
   * Returns the agrmtNb
   * 
   * @return the agrmtNb
   */
    @Column(name = "AGRMTNB")
    public String getAgrmtNb() {
        return agrmtNb;
    }	 
     
  /**
   * Sets the agrmtNb
   *
   * @param newAgrmtNb the new agrmtNb
   */

    public void  setAgrmtNb(String newAgrmtNb) {
        agrmtNb = newAgrmtNb;
    }	  
  /**
   * Returns the dbtrNm
   * 
   * @return the dbtrNm
   */
    @Column(name = "DBTRNM")
    public String getDbtrNm() {
        return dbtrNm;
    }	 
     
  /**
   * Sets the dbtrNm
   *
   * @param newDbtrNm the new dbtrNm
   */

    public void  setDbtrNm(String newDbtrNm) {
        dbtrNm = newDbtrNm;
    }	  
  /**
   * Returns the dbtrAcctId
   * 
   * @return the dbtrAcctId
   */
    @Column(name = "DBTRACCTID")
    public String getDbtrAcctId() {
        return dbtrAcctId;
    }	 
     
  /**
   * Sets the dbtrAcctId
   *
   * @param newDbtrAcctId the new dbtrAcctId
   */

    public void  setDbtrAcctId(String newDbtrAcctId) {
        dbtrAcctId = newDbtrAcctId;
    }	  
  /**
   * Returns the dbtrAcctIssr
   * 
   * @return the dbtrAcctIssr
   */
    @Column(name = "DBTRACCTISSR")
    public String getDbtrAcctIssr() {
        return dbtrAcctIssr;
    }	 
     
  /**
   * Sets the dbtrAcctIssr
   *
   * @param newDbtrAcctIssr the new dbtrAcctIssr
   */

    public void  setDbtrAcctIssr(String newDbtrAcctIssr) {
        dbtrAcctIssr = newDbtrAcctIssr;
    }	  
  /**
   * Returns the dbtrAgtBrnchId
   * 
   * @return the dbtrAgtBrnchId
   */
    @Column(name = "DBTRAGTBRNCHID")
    public String getDbtrAgtBrnchId() {
        return dbtrAgtBrnchId;
    }	 
     
  /**
   * Sets the dbtrAgtBrnchId
   *
   * @param newDbtrAgtBrnchId the new dbtrAgtBrnchId
   */

    public void  setDbtrAgtBrnchId(String newDbtrAgtBrnchId) {
        dbtrAgtBrnchId = newDbtrAgtBrnchId;
    }	  
  /**
   * Returns the cdtrAgtBrnchId
   * 
   * @return the cdtrAgtBrnchId
   */
    @Column(name = "CDTRAGTBRNCHID")
    public String getCdtrAgtBrnchId() {
        return cdtrAgtBrnchId;
    }	 
     
  /**
   * Sets the cdtrAgtBrnchId
   *
   * @param newCdtrAgtBrnchId the new cdtrAgtBrnchId
   */

    public void  setCdtrAgtBrnchId(String newCdtrAgtBrnchId) {
        cdtrAgtBrnchId = newCdtrAgtBrnchId;
    }	  
  /**
   * Returns the cdtrNm
   * 
   * @return the cdtrNm
   */
    @Column(name = "CDTRNM")
    public String getCdtrNm() {
        return cdtrNm;
    }	 
     
  /**
   * Sets the cdtrNm
   *
   * @param newCdtrNm the new cdtrNm
   */

    public void  setCdtrNm(String newCdtrNm) {
        cdtrNm = newCdtrNm;
    }	  
  /**
   * Returns the cdtrAcctId
   * 
   * @return the cdtrAcctId
   */
    @Column(name = "CDTRACCTID")
    public String getCdtrAcctId() {
        return cdtrAcctId;
    }	 
     
  /**
   * Sets the cdtrAcctId
   *
   * @param newCdtrAcctId the new cdtrAcctId
   */

    public void  setCdtrAcctId(String newCdtrAcctId) {
        cdtrAcctId = newCdtrAcctId;
    }	  
  /**
   * Returns the cdtrAcctIssr
   * 
   * @return the cdtrAcctIssr
   */
    @Column(name = "CDTRACCTISSR")
    public String getCdtrAcctIssr() {
        return cdtrAcctIssr;
    }	 
     
  /**
   * Sets the cdtrAcctIssr
   *
   * @param newCdtrAcctIssr the new cdtrAcctIssr
   */

    public void  setCdtrAcctIssr(String newCdtrAcctIssr) {
        cdtrAcctIssr = newCdtrAcctIssr;
    }	  
  /**
   * Returns the intrBkSttlmAmt
   * 
   * @return the intrBkSttlmAmt
   */
    @Column(name = "INTRBKSTTLMAMT")
    public Double getIntrBkSttlmAmt() {
        return intrBkSttlmAmt;
    }	 
     
  /**
   * Sets the intrBkSttlmAmt
   *
   * @param newIntrBkSttlmAmt the new intrBkSttlmAmt
   */

    public void  setIntrBkSttlmAmt(Double newIntrBkSttlmAmt) {
        intrBkSttlmAmt = newIntrBkSttlmAmt;
    }	  
  /**
   * Returns the prtryTpCd
   * 
   * @return the prtryTpCd
   */
    @Column(name = "PRTRYTPCD")
    public String getPrtryTpCd() {
        return prtryTpCd;
    }	 
     
  /**
   * Sets the prtryTpCd
   *
   * @param newPrtryTpCd the new prtryTpCd
   */

    public void  setPrtryTpCd(String newPrtryTpCd) {
        prtryTpCd = newPrtryTpCd;
    }	  
  /**
   * Returns the prtryTcCd
   * 
   * @return the prtryTcCd
   */
    @Column(name = "PRTRYTCCD")
    public String getPrtryTcCd() {
        return prtryTcCd;
    }	 
     
  /**
   * Sets the prtryTcCd
   *
   * @param newPrtryTcCd the new prtryTcCd
   */

    public void  setPrtryTcCd(String newPrtryTcCd) {
        prtryTcCd = newPrtryTcCd;
    }	  
  /**
   * Returns the addtlInf
   * 
   * @return the addtlInf
   */
    @Column(name = "ADDTLINF")
    public String getAddtlInf() {
        return addtlInf;
    }	 
     
  /**
   * Sets the addtlInf
   *
   * @param newAddtlInf the new addtlInf
   */

    public void  setAddtlInf(String newAddtlInf) {
        addtlInf = newAddtlInf;
    }	  
    
    
}    
    
