package com.topfinance.ebo.msg;

import com.topfinance.ebo.msg.JaxbMapping;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;


/**
 * Beps12700101 generated by ParseSampleXml
 */
 
@Entity
@Table(name = "T_MSG_BEPS_127_001_01__")
public class Beps12700101  implements java.io.Serializable {

    // Fields 
    @JaxbMapping(objPath="")
    private Integer id;
    
    @JaxbMapping(objPath="cstmrDrctDbt.pKGGrpHdr.msgId")
    private String msgId;
    
    @JaxbMapping(objPath="cstmrDrctDbt.pKGGrpHdr.creDtTm")
    private Date creDtTm;
    
    @JaxbMapping(objPath="cstmrDrctDbt.pKGGrpHdr.instgPty.instgDrctPty")
    private String instgDrctPty;
    
    @JaxbMapping(objPath="cstmrDrctDbt.pKGGrpHdr.instdPty.instdDrctPty")
    private String instdDrctPty;
    
    @JaxbMapping(objPath="cstmrDrctDbt.pKGGrpHdr.nbOfTxs")
    private String nbOfTxs;
    
    @JaxbMapping(objPath="cstmrDrctDbt.pKGGrpHdr.ctrlSum.value")
    private Double ctrlSum;
    
    @JaxbMapping(objPath="cstmrDrctDbt.pKGGrpHdr.sysCd")
    private String sysCd;
    
    @JaxbMapping(objPath="cstmrDrctDbt.pKGGrpHdr.rmk")
    private String rmk;
    
    @JaxbMapping(objPath="cstmrDrctDbt.pKGRtrLtdInf.pKGRtrLtd")
    private String pKGRtrLtd;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0]")
    private java.util.Set<Beps12700101CstmrDrctDbtInf> cstmrDrctDbtInf;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].cstmrDrctDbtAddtlInf.ntlTrsrCdtInf")
    private java.util.Set<Beps12700101NtlTrsrCdtInf> ntlTrsrCdtInf;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].cstmrDrctDbtAddtlInf.ntlTrsrCdtInf.txsDtls[0]")
    private java.util.Set<Beps12700101TxsDtls> txsDtls;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].cstmrDrctDbtAddtlInf.ntlTrsrInf")
    private java.util.Set<Beps12700101NtlTrsrInf> ntlTrsrInf;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].cstmrDrctDbtAddtlInf.ntlTrsrInf.txsDtls[0]")
    private java.util.Set<Beps12700101TxsDtls> txsDtls1;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].cstmrDrctDbtAddtlInf.chqInf")
    private java.util.Set<Beps12700101ChqInf> chqInf;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].cstmrDrctDbtAddtlInf.chqInf.endrsrDtl[0]")
    private java.util.Set<Beps12700101EndrsrDtl> endrsrDtl;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].cstmrDrctDbtAddtlInf.bllInf")
    private java.util.Set<Beps12700101BllInf> bllInf;
    
    @JaxbMapping(objPath="cstmrDrctDbt.cstmrDrctDbtInf[0].cstmrDrctDbtAddtlInf.bllInf.endrsrDtl[0]")
    private java.util.Set<Beps12700101EndrsrDtl> endrsrDtl1;
    
    
	
    /** default constructor */
    public Beps12700101() {
    }
	
	
  /**
   * Returns the id
   * 
   * @return the id
   */
	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name = "CFG_SEQUNCE_GEN", sequenceName = "S_CFG_SEQUNCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "CFG_SEQUNCE_GEN")
    public Integer getid() {
        return id;
    }	 
     
  /**
   * Sets the id
   *
   * @param newid the new id
   */

    public void  setid(Integer newid) {
        id = newid;
    }	  
  /**
   * Returns the msgId
   * 
   * @return the msgId
   */
    @Column(name = "MSGID")
    public String getMsgId() {
        return msgId;
    }	 
     
  /**
   * Sets the msgId
   *
   * @param newMsgId the new msgId
   */

    public void  setMsgId(String newMsgId) {
        msgId = newMsgId;
    }	  
  /**
   * Returns the creDtTm
   * 
   * @return the creDtTm
   */
    @Column(name = "CREDTTM")
    public Date getCreDtTm() {
        return creDtTm;
    }	 
     
  /**
   * Sets the creDtTm
   *
   * @param newCreDtTm the new creDtTm
   */

    public void  setCreDtTm(Date newCreDtTm) {
        creDtTm = newCreDtTm;
    }	  
  /**
   * Returns the instgDrctPty
   * 
   * @return the instgDrctPty
   */
    @Column(name = "INSTGDRCTPTY")
    public String getInstgDrctPty() {
        return instgDrctPty;
    }	 
     
  /**
   * Sets the instgDrctPty
   *
   * @param newInstgDrctPty the new instgDrctPty
   */

    public void  setInstgDrctPty(String newInstgDrctPty) {
        instgDrctPty = newInstgDrctPty;
    }	  
  /**
   * Returns the instdDrctPty
   * 
   * @return the instdDrctPty
   */
    @Column(name = "INSTDDRCTPTY")
    public String getInstdDrctPty() {
        return instdDrctPty;
    }	 
     
  /**
   * Sets the instdDrctPty
   *
   * @param newInstdDrctPty the new instdDrctPty
   */

    public void  setInstdDrctPty(String newInstdDrctPty) {
        instdDrctPty = newInstdDrctPty;
    }	  
  /**
   * Returns the nbOfTxs
   * 
   * @return the nbOfTxs
   */
    @Column(name = "NBOFTXS")
    public String getNbOfTxs() {
        return nbOfTxs;
    }	 
     
  /**
   * Sets the nbOfTxs
   *
   * @param newNbOfTxs the new nbOfTxs
   */

    public void  setNbOfTxs(String newNbOfTxs) {
        nbOfTxs = newNbOfTxs;
    }	  
  /**
   * Returns the ctrlSum
   * 
   * @return the ctrlSum
   */
    @Column(name = "CTRLSUM")
    public Double getCtrlSum() {
        return ctrlSum;
    }	 
     
  /**
   * Sets the ctrlSum
   *
   * @param newCtrlSum the new ctrlSum
   */

    public void  setCtrlSum(Double newCtrlSum) {
        ctrlSum = newCtrlSum;
    }	  
  /**
   * Returns the sysCd
   * 
   * @return the sysCd
   */
    @Column(name = "SYSCD")
    public String getSysCd() {
        return sysCd;
    }	 
     
  /**
   * Sets the sysCd
   *
   * @param newSysCd the new sysCd
   */

    public void  setSysCd(String newSysCd) {
        sysCd = newSysCd;
    }	  
  /**
   * Returns the rmk
   * 
   * @return the rmk
   */
    @Column(name = "RMK")
    public String getRmk() {
        return rmk;
    }	 
     
  /**
   * Sets the rmk
   *
   * @param newRmk the new rmk
   */

    public void  setRmk(String newRmk) {
        rmk = newRmk;
    }	  
  /**
   * Returns the pKGRtrLtd
   * 
   * @return the pKGRtrLtd
   */
    @Column(name = "PKGRTRLTD")
    public String getPKGRtrLtd() {
        return pKGRtrLtd;
    }	 
     
  /**
   * Sets the pKGRtrLtd
   *
   * @param newPKGRtrLtd the new pKGRtrLtd
   */

    public void  setPKGRtrLtd(String newPKGRtrLtd) {
        pKGRtrLtd = newPKGRtrLtd;
    }	  
  /**
   * Returns the cstmrDrctDbtInf
   * 
   * @return the cstmrDrctDbtInf
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "parent")
    public java.util.Set<Beps12700101CstmrDrctDbtInf> getCstmrDrctDbtInf() {
        return cstmrDrctDbtInf;
    }	 
     
  /**
   * Sets the cstmrDrctDbtInf
   *
   * @param newCstmrDrctDbtInf the new cstmrDrctDbtInf
   */

    public void  setCstmrDrctDbtInf(java.util.Set<Beps12700101CstmrDrctDbtInf> newCstmrDrctDbtInf) {
        cstmrDrctDbtInf = newCstmrDrctDbtInf;
    }	  
  /**
   * Returns the ntlTrsrCdtInf
   * 
   * @return the ntlTrsrCdtInf
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "parent")
    public java.util.Set<Beps12700101NtlTrsrCdtInf> getNtlTrsrCdtInf() {
        return ntlTrsrCdtInf;
    }	 
     
  /**
   * Sets the ntlTrsrCdtInf
   *
   * @param newNtlTrsrCdtInf the new ntlTrsrCdtInf
   */

    public void  setNtlTrsrCdtInf(java.util.Set<Beps12700101NtlTrsrCdtInf> newNtlTrsrCdtInf) {
        ntlTrsrCdtInf = newNtlTrsrCdtInf;
    }	  
  /**
   * Returns the txsDtls
   * 
   * @return the txsDtls
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "parent")
    public java.util.Set<Beps12700101TxsDtls> getTxsDtls() {
        return txsDtls;
    }	 
     
  /**
   * Sets the txsDtls
   *
   * @param newTxsDtls the new txsDtls
   */

    public void  setTxsDtls(java.util.Set<Beps12700101TxsDtls> newTxsDtls) {
        txsDtls = newTxsDtls;
    }	  
  /**
   * Returns the ntlTrsrInf
   * 
   * @return the ntlTrsrInf
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "parent")
    public java.util.Set<Beps12700101NtlTrsrInf> getNtlTrsrInf() {
        return ntlTrsrInf;
    }	 
     
  /**
   * Sets the ntlTrsrInf
   *
   * @param newNtlTrsrInf the new ntlTrsrInf
   */

    public void  setNtlTrsrInf(java.util.Set<Beps12700101NtlTrsrInf> newNtlTrsrInf) {
        ntlTrsrInf = newNtlTrsrInf;
    }	  
  /**
   * Returns the txsDtls1
   * 
   * @return the txsDtls1
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "parent")
    public java.util.Set<Beps12700101TxsDtls> getTxsDtls1() {
        return txsDtls1;
    }	 
     
  /**
   * Sets the txsDtls1
   *
   * @param newTxsDtls1 the new txsDtls1
   */

    public void  setTxsDtls1(java.util.Set<Beps12700101TxsDtls> newTxsDtls1) {
        txsDtls1 = newTxsDtls1;
    }	  
  /**
   * Returns the chqInf
   * 
   * @return the chqInf
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "parent")
    public java.util.Set<Beps12700101ChqInf> getChqInf() {
        return chqInf;
    }	 
     
  /**
   * Sets the chqInf
   *
   * @param newChqInf the new chqInf
   */

    public void  setChqInf(java.util.Set<Beps12700101ChqInf> newChqInf) {
        chqInf = newChqInf;
    }	  
  /**
   * Returns the endrsrDtl
   * 
   * @return the endrsrDtl
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "parent")
    public java.util.Set<Beps12700101EndrsrDtl> getEndrsrDtl() {
        return endrsrDtl;
    }	 
     
  /**
   * Sets the endrsrDtl
   *
   * @param newEndrsrDtl the new endrsrDtl
   */

    public void  setEndrsrDtl(java.util.Set<Beps12700101EndrsrDtl> newEndrsrDtl) {
        endrsrDtl = newEndrsrDtl;
    }	  
  /**
   * Returns the bllInf
   * 
   * @return the bllInf
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "parent")
    public java.util.Set<Beps12700101BllInf> getBllInf() {
        return bllInf;
    }	 
     
  /**
   * Sets the bllInf
   *
   * @param newBllInf the new bllInf
   */

    public void  setBllInf(java.util.Set<Beps12700101BllInf> newBllInf) {
        bllInf = newBllInf;
    }	  
  /**
   * Returns the endrsrDtl1
   * 
   * @return the endrsrDtl1
   */
  	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL, mappedBy = "parent")
    public java.util.Set<Beps12700101EndrsrDtl> getEndrsrDtl1() {
        return endrsrDtl1;
    }	 
     
  /**
   * Sets the endrsrDtl1
   *
   * @param newEndrsrDtl1 the new endrsrDtl1
   */

    public void  setEndrsrDtl1(java.util.Set<Beps12700101EndrsrDtl> newEndrsrDtl1) {
        endrsrDtl1 = newEndrsrDtl1;
    }	  
    
    
}    
    
